### ISSUE TITLE
Fix warning from statistics (was #244)

### ISSUE THREAD

**Issue by sspghost** [simplesamlphp/simplesamlphp#10]
_From [olavmrk@gmail.com](https://code.google.com/u/olavmrk@gmail.com/) on November 25, 2009 15:21:22_

The statistics processing currently causes warnings:
>SimpleSAML_Error_Exception: Error 2048 - mktime(): The is_dst parameter is deprecated
>Backtrace:
>7 .../www/_include.php:48 (SimpleSAML_error_handler)
>6 [builtin] (mktime)
>5 .../modules/statistics/lib/DateHandlerMonth.php:35 
>(sspmod_statistics_DateHandlerMonth::fromSlot)
>4 .../modules/statistics/lib/Aggregator.php:246 
>(sspmod_statistics_Aggregator::store)
>3 .../modules/statistics/hooks/hook_cron.php:28 (statistics_hook_cron)
>2 .../lib/SimpleSAML/Module.php:176 (SimpleSAML_Module::callHooks)
>1 .../modules/cron/www/cron.php:28 (require)
>0 .../www/module.php:137 (N/A)

_Original issue: http://code.google.com/p/simplesamlphp/issues/detail?id=244_

**Comment by jaimeperez** [comment]
This was fixed recently in commit 2c8e6be7e8d4e665a8a96133018c77152bb77817.

Removing the `is_dst` parameter was actually enough, since the old behaviour was buggy. Right now, in the `Europe/Oslo` timezone it is 09:45. Setting the timezone (as we do in `www/_include.php`) to `Europe/Oslo` and calling `mktime()` with `is_dst` set to `false` will yield an incorrect date with `gmdate()`: `2016-04-12T08:45:00Z`. Zulu time is one hour less, though. Ommitting `is_dst` yields the correct zulu time: `2016-04-12T07:45:00Z`.

We can therefore safely close this.
