### ISSUE TITLE
newUI: newUI switch broken for negotiate-module

### ISSUE THREAD

**Issue by tvdijen** [simplesamlphp/simplesamlphp#1009]
**Describe the bug**
On `master`, setting `newui=false` will work for `ldap`-authentication, but fails on `negotiate`.

**To Reproduce**
1. Checkout master
2. Set newui=false
3. Set `'auth'='ldap'` in saml20-idp-hosted and try authflow (works)
4. Set `'auth'='negotiate'` in saml20-idp-hosted and try authflow (fails)

**Expected behavior**
Both `ldap` and `negotiate` should just work on the old UI.

**Screenshots or logs**
```
Dec  2 17:45:36 webapp-1 simplesamlphp-idp[3171]: 4 [c07813e1b5] The class or interface 'SimpleSAML_Utilities' is now using namespaces, please use 'SimpleSAML\Utilities'.
Dec  2 17:45:36 webapp-1 simplesamlphp-idp[3171]: 6 [c07813e1b5] SAML2.0 - IdP.SSOService: incoming authentication request: 'https://engine.openconext.moo-archive.nl/authentication/sp/metadata'
Dec  2 17:45:36 webapp-1 simplesamlphp-idp[3171]: 4 [c07813e1b5] The class or interface 'sspmod_core_Stats_Output_Log' is now using namespaces, please use 'SimpleSAML\Module\core\Stats\Output\Log' instead.
Dec  2 17:45:36 webapp-1 simplesamlphp-idp[3171]: 5 [c07813e1b5] EVENT {"spEntityID":"https:\/\/engine.openconext.moo-archive.nl\/authentication\/sp\/metadata","idpEntityID":"https:\/\/idp.moo-archive.nl\/saml2\/idp\/metadata.php","forceAuthn":false,"isPassive":false,"protocol":"saml2","idpInit":false,"op":"saml:idp:AuthnRequest","time":1543769136.32209,"_id":"000000005c040c30bf470509ebb0c5db58687c2b672eb979"}
Dec  2 17:45:36 webapp-1 simplesamlphp-idp[3171]: 7 [c07813e1b5] Session: 'AD-KERBEROS' not valid because we are not authenticated.
Dec  2 17:45:36 webapp-1 simplesamlphp-idp[3171]: 7 [c07813e1b5] Negotiate - SP disable flag not found
Dec  2 17:45:36 webapp-1 simplesamlphp-idp[3171]: 7 [c07813e1b5] Negotiate - authenticate(): looking for Negotiate
Dec  2 17:45:36 webapp-1 simplesamlphp-idp[3171]: 7 [c07813e1b5] Negotiate - authenticate(): Sending Negotiate.
Dec  2 17:45:36 webapp-1 simplesamlphp-idp[3171]: 7 [c07813e1b5] Negotiate - fallback: AD-LDAP
Dec  2 17:45:36 webapp-1 simplesamlphp-idp[3171]: 7 [c07813e1b5] Saved state: '_083c76a2c7b59eeb8a50c540ab8cb4853da1abec09:https://idp.moo-archive.nl/saml2/idp/SSOService.php?spentityid=https.openconext.moo-archive.nl&cookieTime=1543769136'
Dec  2 17:45:36 webapp-1 simplesamlphp-idp[3171]: 7 [c07813e1b5] Localization: using old system
Dec  2 17:45:36 webapp-1 simplesamlphp-idp[3171]: 7 [c07813e1b5] Localization: load domain 'negotiate' at '/apps/installation/simplesamlphp/simplesamlphp/modules/negotiate/locales'
Dec  2 17:45:36 webapp-1 simplesamlphp-idp[3171]: 7 [c07813e1b5] Trying langpath for 'nl' as '/apps/installation/simplesamlphp/simplesamlphp/modules/negotiate/locales/nl/LC_MESSAGES/'
Dec  2 17:45:36 webapp-1 simplesamlphp-idp[3171]: 3 [c07813e1b5] SimpleSAML\Error\Exception: Error 1 - Call to a member function loadTranslations() on null at /apps/installation/simplesamlphp/simplesamlphp/lib/SimpleSAML/Locale/Localization.php:245
Dec  2 17:45:36 webapp-1 simplesamlphp-idp[3171]: 3 [c07813e1b5] Backtrace:
Dec  2 17:45:36 webapp-1 simplesamlphp-idp[3171]: 3 [c07813e1b5] 2 /apps/installation/simplesamlphp/simplesamlphp/www/_include.php:48 (SimpleSAML_error_handler)
Dec  2 17:45:36 webapp-1 simplesamlphp-idp[3171]: 3 [c07813e1b5] 1 /apps/installation/simplesamlphp/simplesamlphp/www/_include.php:25 (SimpleSAML_exception_handler)
Dec  2 17:45:36 webapp-1 simplesamlphp-idp[3171]: 3 [c07813e1b5] 0 [builtin] (N/A)
Dec  2 17:45:36 webapp-1 simplesamlphp-idp[3171]: 6 [c07813e1b5] SAML2.0 - IdP.SSOService: Accessing SAML 2.0 IdP endpoint SSOService
Dec  2 17:45:36 webapp-1 simplesamlphp-idp[3171]: 4 [c07813e1b5] The class or interface 'sspmod_negotiate_Auth_Source_Negotiate' is now using namespaces, please use 'SimpleSAML\Module\negotiate\Auth\Source\Negotiate' instead.
Dec  2 17:45:36 webapp-1 simplesamlphp-idp[3171]: 7 [c07813e1b5] saving key idp.session.826486838655d0e2f67a177b60518e54 to memcache
```

**Comment by tvdijen** [comment]
@jaimeperez the harder I try, the less I understand this 'flow' from the logs...  Can you make sense out of it?

**Comment by jaimeperez** [comment]
Uhm, actually, it was the other way around. Before, the two systems didn't coexist and whenever a twig template was in place, that was always used, regardless of the value of `usenewui`. Now, both the new and the old UI can coexist, and they are in fact isolated, so that if `usenewui` is `false`, the new translation subsystem is not even initialized (leading to the error you are seeing here).

That's precisely the problem here. Twig was in fact initialized because the original idea was to facilitate people to migrate their templates to twig, so `SimpleSAML\XHTML\Template::setupTwig()` was always run regardless of `usenewui`. From there, we have the following chain of calls: `SimpleSAML\Locale\Localization::addModuleDomain()` -> `SimpleSAML\Locale\Localization::addDomain()` -> `SimpleSAML\Locale\Localization::loadGettextGettextFromPo()` -> `\Gettext\Translator::loadTranslations()`. The last one is the one failing, because `\SimpleSAML\Locale\Localization::$translator` is `null`, and that one is `null` because `\SimpleSAML\Locale\Localization::setupTranslator()` is never called in `\SimpleSAML\Locale\Localization::setupL10N()`, as the localization backend is the old one.

In any case, I've just committed a fix for it. Now, twig is not initialized unless `usenewui` is `true`. I also enforced that config option for the sandbox page (`SSPROOT/admin/sandbox.php`) to help make that page available always, so that people can have a sneak peak at it even if they don't dare to try the new UI.

**Comment by tvdijen** [comment]
Thanks, I'll run a few tests tonight to confirm the fix

**Comment by tvdijen** [comment]
I had to make a small change to the negotiate-module.. Now it works for both UI's again

**Comment by jaimeperez** [comment]
What change was that Tim? If it was still broken and needed a change to work, we might need to look at that to avoid further breakage of other modules...

**Comment by jaimeperez** [comment]
I see. That's reassuring then 😄
