### ISSUE TITLE
Invalid ALTER query to upgrade logout table schema in simplesamlphp/modules/saml/lib/SP/LogoutStore.php

### ISSUE THREAD

**Issue by ghost** [simplesamlphp/simplesamlphp#1118]
The query used to alter the _authSource type from VARCHAR(30) to VARCHAR(255), at line 32 of simplesamlphp/modules/saml/lib/SP/LogoutStore.php (branch 1.17) is incompatible with SQLite and will produce  a syntax error. Therefore, the table schema versions is never upgraded when upgrading from an older version. This seems to have been changed in commit 1681c295210b1966462a90b0606288b83882e9c1, which was commited on 16 Apr 2017.

You can not use the ALTER TABLE statement to modify a column in SQLite. Instead you will need to rename the table, create a new table, and copy the data into the new table.

Fortunately this bug appears to be non-breaking unless your authSource hostname is longer than 30 characters and you're using SQLite as your session db engine.

**Comment by ygirouard** [comment]
Quick workaround: changing the table prefix in config/config.php and initiating a new session to create new tables.

Then performing a 'select * from PREFIX_tableVersion;' should show version 2 for saml_LogoutStore.

**Comment by tvdijen** [comment]
This has some relation to https://github.com/simplesamlphp/simplesamlphp/issues/963.. Do we support SQLlite yes/no.. If yes, we shouldn't use ALTER anywhere, of not we may mark this as a wontfix..

**Comment by ygirouard** [comment]
> This has some relation to #963.. Do we support SQLlite yes/no.. If yes, we shouldn't use ALTER anywhere, of not we may mark this as a wontfix.. I would say yes!
> 
> @ygirouard A PR would be very much appreciated!!

There's references to sqlite as the engine for store.sql.dsn in the config template and several of the lib files do have explicit code for sqlite, so I would say it is definitely supposed to be supported.

As for a PR, I'm not a developer although I knew enough of PHP and SQLite to find the bug. Since the session database has nothing that needs to be kept forever however in most cases, I would say that simply dropping/recreating it should be enough. It was fine in my case anyway. Don't know if there are cases where you would want to keep a history of the session data?

If it can help, this is where I got the info from: https://www.techonthenet.com/sqlite/tables/alter_table.php

**Comment by tvdijen** [comment]
Session data is non-persistent if you ask me.. Thanks for the feedback, we will address this in a future release!

**Comment by tvdijen** [comment]
Any chance you could test #1156 for me, @ygirouard ? I don't have a database around ATM..
