### ISSUE TITLE
Old translation system not deprecated

### ISSUE THREAD

**Issue by ghalse** [simplesamlphp/simplesamlphp#1187]
I've just learnt from #463 and #465  that the `includeInlineTranslation()` call I used in #1084 is being phased out. Consequently, the changes in #1084 do not work in the new UI.

Should calls to the old translation system not be marked as @deprecated to avoid people developing new code based on them?

**Comment by jaimeperez** [comment]
Hi Guy!

I'd say it should be quite obvious, since translations are now done in the templates by using any of the mechanisms available (tags or filters). On the other hand, you are right, it should be marked as deprecated.

**Comment by ghalse** [comment]
Hmm, this might be more complex than I understand.

The calls to \SimpleSAML\XHTML\Template::includeInlineTranslation() are already marked @depricated with a note that they will be removed in 2.0, however they both refer to and now just directly call \SimpleSAML\Locale\Translate::includeInlineTranslation() which is not.

That means either \SimpleSAML\Locale\Translate::includeInlineTranslation() is not deprecated, or the comment on the other method is misleading?

**Comment by tvdijen** [comment]
I think we've had some discussion about this at some point... I think at that time we discussed making a Twig Filter of it instead of deprecating it, but I don't remember the outcome..
I have no real preference here, this use-case can be solved without this method and/or a Twig-filter... We do this in several places already with dynamic IDP/SP names, where we do the translation in the controller instead of in the template. A quick grep shows me that discopower is the only module that still needs work in this regard.

**Comment by thijskh** [comment]
I think this can now be closed. And even remove includeInlineTranslation()?

**Comment by tvdijen** [comment]
There are a few more references to this method;  https://github.com/simplesamlphp/simplesamlphp-module-consentadmin/issues/1
