### ISSUE TITLE
SameSite issues w/ Safari

### ISSUE THREAD

**Issue by JohnMaguire** [simplesamlphp/simplesamlphp#1198]
# **Help us to keep this issue-tracker clean!  For questions or support, please refer to our [mailing lists](https://simplesamlphp.org/lists)**

**Describe the bug**
This is more of a heads up than anything else... recently SameSite support was added, which works great. In particular, users might need to set this to `'None'` to get Chrome 80+ to work with SimpleSAMLphp (I believe it affects situations such as beginning SP-initiated auth to SSP, and then redirected to a SAML IdP and then back to SSP) due to Chrome's default changing to 'Lax': https://www.chromestatus.com/feature/5088147346030592

Unfortunately, if users set this to 'None', Safari will instead set the flag to 'Strict' as it does not recognize 'None' and will not recognize it until the next major version of Safari, if I understand this thread correctly: https://bugs.webkit.org/show_bug.cgi?id=198181

I don't have a suggested solution, and while this probably doesn't affect SSP maintainers today, it may once Chrome 80 ships, so I wanted to give you a heads up.

**Comment by jornane** [comment]
We've discussed this a bit offline already. I don't think there is a perfect solution to this; by doing nothing things will break when Chrome 80 ships, but the obvious fix breaks current Safari.

So far the best solution I could come up with is to add a `if chrome` somewhere in the code that handles cookies. But we should do that before Chrome 80 ships, because SimpleSAMLphp must still be updated by admins before that.

**Comment by jaimeperez** [comment]
Thanks for the heads up @JohnMaguire!

Note also that [we now have the possibility to configure the `SameSite` option](https://github.com/simplesamlphp/simplesamlphp/pull/1161).

**Comment by jeremyfrench** [comment]
I'm not sure if this issue is closed. 

The changes made to SimpleSamlPhp in #1161 will get the cookie to work in chrome, but enabling this will break in a number of other browsers/platforms. (see https://www.chromium.org/updates/same-site/incompatible-clients for details)

I've written a [small library](https://packagist.org/packages/fullfatthings/samesiteexceptions#dev-master) which I'm using to handle these exceptions for myself with SimpleSamlPhp I'm happy to roll a patch if it would be welcome

**Comment by jaimeperez** [comment]
Hi @jeremyfrench!

Thanks a lot for your contribution! We discussed a lot about this in #1153 as you can see. Back at the time, there wasn't a good-enough knowledge around the issue to suggest proper solutions. We discussed your approach, but identifying browsers by their user agent string is really evil and we would like to avoid that. Still, that's perfectly doable by configuration, and compatible with the changes introduced in #1161.

The latest approach that many people is taking is doubling cookies, one with the `SameSite` parameter set to `none`, and one without it, so that you can cover all web browsers (if one cookie is not present, try look for the alternative). This is probably the path we'll take, but it needs a bit more hacking around in the codebase.

**Comment by Joe-U-Questionmark** [comment]
@jaimeperez 
I think the industry has now agreed that the only way to resolve the backwards compatibility issue is to change the behavior based on user agent. 
Microsoft also recommend the same in a number of places. Here is their recommended approach: (Just read the function called DisallowsSameSiteNone)
https://devblogs.microsoft.com/aspnet/upcoming-samesite-cookie-changes-in-asp-net-and-asp-net-core/

Is there a plan to make this change? Is there a workaround in the meantime?

**Comment by jeremyfrench** [comment]
@Joe-U-Questionmark I can send you a patch that will do this with the library I wrote if you need urgently. While I agree that browser sniffing is not an ideal solution we have used it and as far as we can test it works as expected.

**Comment by Joe-U-Questionmark** [comment]
> @Joe-U-Questionmark I can send you a patch that will do this with the library I wrote if you need urgently. While I agree that browser sniffing is not an ideal solution we have used it and as far as we can test it works as expected.

@jeremyfrench yes please!

**Comment by jaimeperez** [comment]
Hi @Joe-U-Questionmark!

I'm not sure what you expect from us here. Our decision is to use the double cookie approach, as that's the only one that's guaranteed to be reliable for all browsers. However, if your idea is to still use user-agent detection, that you can already do without any modification to SimpleSAMLphp. Just detect the browser in the configuration file and change the `session.cookie.samesite` configuration option depending on the browser. You even have multiple examples of how to do that in #1153.
