### ISSUE TITLE
Validate post requests via the errorreport.php

### ISSUE THREAD

**Issue by roland-d** [simplesamlphp/simplesamlphp#1211]
**Is your feature request related to a problem? Please describe.**
The problem is that you can create a spam attack via the errorreport.php

**Describe the solution you'd like**
Add a form token to the error report form. This form token can be checked on submission, if it is invalid no email is send out.

**Describe alternatives you've considered**
The only real alternative is to turn off the error report form.

**Additional context**
I posted this first in the Google group, here is my post for reference:
https://groups.google.com/forum/#!topic/simplesamlphp/ccy6fN0PslI

**Comment by jaimeperez** [comment]
Hi @roland-d!

Although I see your point, I'm afraid there's little we can do here. We can of course add a nonce to the form to make sure emails are only sent after effectively triggernig an error, but what's the advantage there? I mean, the same way you can automate it in a loop to send a thousand post requests to the page, you can also automate it to trigger an error (e.g. page not found), grab the nonce and then send the email.

Also, the attack surface is quite unclear here. You cannot control the recipient of the emails, and you can't include HTML in that email either, so the only viable attack that I can see is flood the mailbox with error reports. Of course a denial of service is not good, but a nonce wouldn't really be effective against an attacker with minimum knowledge...

**Comment by roland-d** [comment]
Hello @jaimeperez 

The other issue I guess I see here is not only flooding a mailbox but also hitting rate-limits on your mailserver causing actual mails not to go out.

Yes, I agree, it won't help against any kind of DDOS as that will still happen.

I am also not sure if we should do something about this, just I ran into it and wanted to share this.

**Comment by jaimeperez** [comment]
Yes, I was essentially assuming that (rate limiting) as part of the denial of service scenario.

I honestly don't know. Adding a nonce to the form should be trivial, but I really don't see that offering much. I think essentially the only way to avoid this is to have proper DoS protection measures in front of the server.

**Comment by tvdijen** [comment]
I'm not a fan of captcha's, but in this case they could offer a solution.
If we could implement them in a generic way, people could easily add one to their templates..

**Comment by BAGELreflex** [comment]
This is often handled by IPS on the server, rather than within the application itself. Using something like [fail2ban](https://www.fail2ban.org/wiki/index.php/Main_Page), you could prevent this flooding attack vector for any request going through your web server, not just these email requests.

https://samnicholls.net/2016/06/06/fail2ban-apache-dos/

**Comment by jaimeperez** [comment]
I agree, there are ways to prevent these issues per-deployment, rather than software. I'm closing the issue, but feel free to keep discussing or reopen if needed.

**Comment by mrseeker** [comment]
Hello,

I came across this issue due to a similar problem I am experiencing. We are currently being flooded with bots that constantly trigger Exceptions before spamming us with their error reports. Since we have around 1000-1500 emails per day coming in this mailbox, there is no way for us to validate each and every error report.
Fail2ban works only AFTER they have triggered the exception, not before. So they constantly trigger an exception, send out a spam report to the Admin, then get banned.
My proposal would be this: 
1. Limit "known" errors from sending an error message to the admin. I have 2 that constantly keep popping up in my logs (and are caused by bots):
- BADREQUEST - 'Missing AuthState parameter.'
- Exception: Missing parameter: entityID
2. Only send emails from a certain "whitelist". Since I have only 2 auth providers that I use, the error messages coming from those domains are the onliest ones I am actually interested in. The rest can be dumped into a black hole since they are basically spam...
