### ISSUE TITLE
Add support for environment variables

### ISSUE THREAD

**Issue by hemorej** [simplesamlphp/simplesamlphp#1231]
# Problem description  

We have different targets with automated deployment tools, a staging server and a production server. This is not a uncommong setup. 
The issue arises because of the different configurations on staging and production. 

A basic example is the DB passwords which now have to be in the code so we can deploy it without manual intervention. Or for example the log level which is more verbose on staging to help debugging. 

A more complex example, is the metadata set which on staging has to support a bunch of different development machines all of which are totally irrelevant in production.

# Solution  

Ideally, a `env('variable_name', 'default_value')` solution, not unlike what Laravel has. 
The config file would reference these variables and the `.env` file remains unchanged outside the deployable directory.

# Alternatives  

We could use Apache variables which we could pick up in PHP but that's a rather impractical solution. Every time we need to check our config values we'd have to `sudo` open the Apache config, which really is a server config file unrelated to any application config. And anytime we need to update the config values an Apache restart is required.

Another option is an elaborate and brittle deployment script that swaps out files and `sed`s values based on target deployment. This is what we're doing now and it's hard to maintain and integrate updates from SSP

**Comment by tvdijen** [comment]
Hi @hemorej 

Have you read about the [Apache ENVs](https://github.com/simplesamlphp/simplesamlphp/blob/ea6b948d5c7eea546cd3096c2ebf862c6b2c06d1/docs/simplesamlphp-install.md#alternative-location-for-configuration-files) we support?

You can have one install, with several configs based on the vhost.. Isn't that what you're looking for?
I guess with the way we're going we might support symfony env vars in the future, but we're really not close to reaching that point..

**Comment by jaimeperez** [comment]
Hi @hemorej!

What you are asking for is already possible. The configuration is PHP code, so you can programmatically do whatever you want. For example, you can have config files for each instance, and point at them with the `SIMPLESAMLPHP_CONFIG_DIR` environment variable that Tim was pointing to. If you have any common configuration, you can always load that first by requiring that configuration file from the deployment-specific files, and then refine the configuration.

Also, note that you should never put passwords in environment variables. When you do that, the password becomes readable for everyone having shell access to the machine, since the environment of a process is publicly readable by all users.
