### ISSUE TITLE
authproc in authsources.php for multiauth source no longer working

### ISSUE THREAD

**Issue by michael-dev** [simplesamlphp/simplesamlphp#1232]
I used to have 'authproc' => [ ... ] entries in authsources.php attached to multiauth providers (e.g. with SimpleSAMLphp 1.14). After upgrading to 1.17.7, these are no longer called. Though, the authproc filters attached to a saml:SP providers are still called.

**To Reproduce**
Create a multiauth source which references a saml:SP source. Attach an authproc to the multiauth source and to the saml:SP source.
The authproc filter for the saml:SP source is called, but the filter for the multiauth source (snippet below) not.

```
 36   'sp-wayfinder-name' => array(
 37     'multiauth:MultiAuth',
 38     'sources' => array(
 39       'default-sp' => array(
 40         'text' => array(
 41           'de' => 'some SAML SP',
 42         ),
 43       ),
 44     ),
 45     'authproc' => array(
 46       20 => array('class' => 'authorize:Authorize','eduPersonScopedAffiliation'=>'student@tu-ilmenau.de','regex'=>FALSE,'deny'=>FALSE),
```

**Expected behavior**
Both authproc filters should be called.

**Comment by tvdijen** [comment]
Thanks for reporting @michael-dev !
Would you be able to help us further pinpoint the moment this was broken? We are over 2750 commit beyond 1.14 and a whole lot has changed since..

**Comment by BAGELreflex** [comment]
I believe this has been broken since at least version 1.15.x. I have tried a few times in the past to implement authproc's on my authsources and have never been successful in getting them to execute. I just assumed I was mis-interpreting the documentation or doing something wrong. I was able to handle them them all on IdP or SP level, so I didn't dive further into this. I say 1.15 because that's the first version I implemented, and I'm 80% sure I tried authproc on authsources prior to my initial release.

**Comment by jaimeperez** [comment]
Hi @michael-dev!

This has never been supported. Authproc filters can be configured in different places, but you cannot define authprocs for random authentication sources (`config/authsources.php`). Each auth source must support running authproc filters, and the only one that supports that is the SAML SP. [The documentation](https://simplesamlphp.org/docs/stable/simplesamlphp-authproc#section_1) might not be crystal clear, but it does say so:

> * On the SP: Specific for only the SP in authsources.php
