### ISSUE TITLE
Broken Cron-controller class

### ISSUE THREAD

**Issue by tvdijen** [simplesamlphp/simplesamlphp#1248]
The cron-controller doesn't seem to work as reported by @restena-sw on the mailling list:
https://groups.google.com/d/msg/simplesamlphp/R7d29OrMxoQ/UYbjc8qKAgAJ

**Comment by Steltek** [comment]
Seeing the same issue with my installation:

https://servername/module.php/cron/run/daily/secret

fails with "The given page was not found. The reason was: The URL wasn't found in the module"

The old URL style, https://servername/module.php/cron/cron.php?key=secret&tag=daily, works.

**Comment by tvdijen** [comment]
I believe changes to `master` may have fixed this.. Would it be easy for you to run a test with that?
It would really help us

**Comment by Steltek** [comment]
Tried it (but can't run composer/npm here so had to build on a different system and then zip that up).
Old UI shows me only the documentation link (even when logged in). New UI fails with:
`PHP Fatal error:  Trait 'Symfony\\Bundle\\FrameworkBundle\\Kernel\\MicroKernelTrait' not found in xxx\\simplesaml\\lib\\SimpleSAML\\Kernel.php on line 21
`
(I'm guessing my build process messed it up.)

**Comment by justcaldwell** [comment]
Updated to 1.18.5. I see that routes.yaml was moved, but still have the same issue as described by Steltek [above](#issuecomment-573549352).

**Comment by tvdijen** [comment]
I can confirm that the old ui shows the links for new ui (which don't work)

**Comment by uhi67** [comment]
I'm using 1.18.7, and the displayed new style url still not works.

**Comment by tvdijen** [comment]
That's because we haven't fixed it yet

**Comment by uhi67** [comment]
I tried old style url (1.18.7) ".../module.php/cron/cron.php?key=secret&tag=hourly&output=xhtml"
and it did not produce any output. In fact the main job has run, as I can see in the log, and there is an exception:
"SimpleSAML\Error\Exception: Error 1 - Call to a member function render() on null at .../vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/XHTML/Template.php:515"
The backtrace in the log after the exception line is unusable, because it shows only the backtrace of the error handler, but not the call stack of the exception.

**Comment by tvdijen** [comment]
The issue has been fixed an will be in 1.18.8 or 1.19, whichever comes first
