### ISSUE TITLE
SSP refuses to use temp dir if it doesn't own it, even though it can write to it

### ISSUE THREAD

**Issue by mstrelan** [simplesamlphp/simplesamlphp#1272]
SimpleSAMLphp expects the temp directory to be owned by the current user, when it should really only worry if it can read and write to the temp directory.

**To Reproduce**
1. Create /tmp/simplesaml as root with 777 permissions
2. Try run metarefresh
3. See error `Temporary directory /tmp/simplesaml does not belong to the current user.`

**Expected behavior**
SimpleSAMLphp checks it can read/write to the directory and proceeds.

**Comment by BAGELreflex** [comment]
The current implementation: https://github.com/simplesamlphp/simplesamlphp/blob/master/lib/SimpleSAML/Utils/System.php#L77

It seems like there has been work specifically completed to ensure the tempdir is owned by the user running SimpleSAMLphp. It has been that way since atleast 2015:

- https://github.com/simplesamlphp/simplesamlphp/commits/master/lib/SimpleSAML/Utils/System.php
- https://github.com/simplesamlphp/simplesamlphp/blob/7582458c3156f60e60f23687b71a67b97c00e702/lib/SimpleSAML/Utils/System.php

It seems to me that the `[is_writable()](https://www.php.net/manual/en/function.is-writable.php)` function may be preferred as it also supports checking for if the user can write to a directory. I believe this method would also account for SELinux preventing the user from writing to the directory as well.

**Comment by jaimeperez** [comment]
Hi @mstrelan, @BAGELreflex!

I'm afraid it has been like this [almost since the beginning](https://github.com/simplesamlphp/simplesamlphp/commit/3d29520b3d49bec3e5495c7cd342cb6c09b576d0#diff-bf45ac4e640725e0448b9c7a2ec58498), 10 years ago.

I agree that checking that the directory is writable is preferable in this case. There's no need for SSP to actually own the directory, as long as it can write to it. Would any of you be able to provide a PR for it?

**Comment by BAGELreflex** [comment]
@jaimeperez PR created: https://github.com/simplesamlphp/simplesamlphp/pull/1314
