### ISSUE TITLE
Access the full http request of the SAML authnrequest from auth modules

### ISSUE THREAD

**Issue by szabogyula** [simplesamlphp/simplesamlphp#1340]
Hi all,

In the federated Microsoft 365 authentication flow first request the IdP (idp/SSOService.php) set the a `username` field with value of the MS login form username next to the `SAMLRequest` and `RelayState` field.

It would be great to access this info by the auth modules, avoid to get username twice (first the microsoft login form, and second on the IdP login form) annoying the user.

Is there any way to access the full http request, not only the SAML request from the auth modules? I guess in the state array or somewhere else?

**Comment by jaimeperez** [comment]
Hi @szabogyula!

If I recall correctly, it might be possible to inspect the request from the authentication source, since I believe there are no redirections in between. However, that could be fragile. I would assume the right way to do this would be to grab the entire request in the `SAML2\IdP` class, and then save it to the state, so that the auth source can later inspect it and use it.

This is tricky, though, as saving the request to the state implies the state array becomes heavier, potentially very heavy. So we would need either to trim it to avoid a lot of clutter or any malicious attempts to perform a DoS, or at least a configuration option to enable/disable this.

**Comment by szabogyula** [comment]
Hi @jaimeperez !

> If I recall correctly, it might be possible to inspect the request from the authentication source, since I believe there are no redirections in between. 

That was true, i can get and use the username and fill the username in my login form.

Thanks a lot!
