### ISSUE TITLE
Symfony 5

### ISSUE THREAD

**Issue by bjoerne2** [simplesamlphp/simplesamlphp#1342]
I'd like to use simplesamlphp in a Laravel 7 project. Laravel 7 uses Symfony 5 libs, but simplesamlphp's composer.json references ^4.0. Now I have a version conflict I can't resolve.

Is there a plan to migrate simplesamlphp to Symfony 5 libs?

**Comment by tvdijen** [comment]
Hi @bjoerne2 ! You're way ahead of us, as `^4.0` is the tag on our `master` branch, which you should never use in production.. Stable versions are still at `^3.0|^4.0`.. We're in the process of migrating to Symfony, but it's a true struggle and our resources are slim. The latter may hopefully change in the near future due to changes in the SimpleSAMLphp organization..

Even though I discourage the use of our master-branch, I don't mind changing the composer.json to require Symfony `^4.0|^5.0`, as 5.0 is probably where we're going to end once we're ready to release SSP 2.0.. Would that help you?

**Comment by tvdijen** [comment]
There seem to be no real upgrade notes for Symfony 4.4 > 5.0.. At least no BC breaks.. Do you seem any harm in targeting `^4.0||^5.0` or even `^5.0` for SSP 2.0?

**Comment by bjoerne2** [comment]
`^4.0||^5.0` sounds great to me! Thanks a lot for your quick reply!

**Comment by tvdijen** [comment]
Ok, done that on master

**Comment by bjoerne2** [comment]
@tvdijen I created a PR for the simplesamlphp-1.19 branch: https://github.com/simplesamlphp/simplesamlphp/pull/1358
