### ISSUE TITLE
Package tests do not pass

### ISSUE THREAD

**Issue by astec-mra** [simplesamlphp/simplesamlphp#1390]
Hello,
I downloaded the latest version of simplesamlphp package (1.18.8) and after installing Composer dependencies I tried to run phpunit tests, but I see 3 failures:

> There were 3 failures:
> 
> 1) SimpleSAML\Test\Utils\ReduceSpillOverTest::testStateRemoved
> Expected config configured in other tests to no longer be valid
> 
> C:\Users\dev\Downloads\simplesamlphp-1.18.8\tests\Utils\ReduceSpillOverTest.php:37
> 
> 2) SimpleSAML\Test\ConfigurationTest::testLoadDefaultInstance
> Failed asserting that exception of type "SimpleSAML\Error\CriticalConfigurationError" is thrown.
> 
> 3) SimpleSAML\Test\ConfigurationTest::testCriticalConfigurationError
> Exception expected
> 
> C:\Users\dev\Downloads\simplesamlphp-1.18.8\tests\lib\SimpleSAML\ConfigurationTest.php:45

What should I configure to make these tests work for me?
Many thanks for help.

**Comment by tvdijen** [comment]
I think these tests may need repair, but I wonder why they work when run through CI...

**Comment by tvdijen** [comment]
The issue here is that these tests rely on missing / non-existing configuration and during the build-process we bootstrap a basic configuration and package it in the tarball..
I think it's very unusual to run unit tests on a packaged version and frankly I believe we shouldn't even package the dev-dependencies.. Marking this as a wont-fix.
