### ISSUE TITLE
Support for SQL Server as Data Store for Sessions

### ISSUE THREAD

**Issue by tashbaugh** [simplesamlphp/simplesamlphp#141]
Inside of config.php I have parameters setup like this:

'store.type'                    => 'sql',
'store.sql.dsn'                => 'sqlsrv:Server=DBServer-1,1433;Database=SAMLDB',
'store.sql.username'     => 'dbuser',
'store.sql.password'      => 'dbpassword',
'store.sql.prefix'            => 'SAML',

I have other PHP applications on the same server as SimpleSAMLPHP that are communicating with this specific SQL Server database and do not have any issues. 

With this configuration, when I utlize the Test Authentication Sources and click on my named SP I am appropriately redirected to the IDP. When I login to the IDP I am then redirected back to the SP but am presented with a State Information Lost page. 

When I inspect the database no new tables have been added with a prefix of SAML. No PHP errors are logged and nothing is in the logs directory of SimpleSAMLPHP. 

If I switch the store type back to phpsession then I the redirect back to the SP works and I have a valid session. 

Upon reviewing the Windows Event Log I found this error occurring multiple times when simplesamlphp attempts to store session information in the database:

"SQLSTATE[42000]: [Microsoft][SQL Server Native Client 11.0][SQL Server]Implicit conversion from data type nvarchar to timestamp is not allowed. Use the CONVERT function to run this query."

**Comment by kpugazh** [comment]
I have the same issue with MySQL
I did configured the SAML to store session in DB with teh following configuration in config/config.php

'store.type' => 'sql',
'store.sql.dsn' => 'mysql:host=localhost;dbname=samldb',
'store.sql.username' => 'root',
'store.sql.password' => 'dbpassword',
'store.sql.prefix' => 'simpleSAMLphp',

Yet I am getting the same error. I did not create any table in this db since the link 
https://simplesamlphp.org/docs/1.10/simplesamlphp-maintenance#section_2
but I see not tables are created

I am able to create tabels from PhP code through mysql PDO.

**Comment by jaimeperez** [comment]
Hi @kpugazh,

Are you getting a Microsoft's SQL Server specific error while using a MySQL backend? :open_mouth:

**Comment by tvdijen** [comment]
@close since no response in 3yrs
