### ISSUE TITLE
Remove ability to set adminpw in cleartext?

### ISSUE THREAD

**Issue by thijskh** [simplesamlphp/simplesamlphp#1420]
We currently support setting the admin password in config.php as cleartext or as a hash. The hash option was one time introduced for those who felt less comfortable with putting the cleartext admin pw in a config file, that they e.g. check in into version control.

The question has been raised whether we want to keep this as-is or deprecate the cleartext version (i.e. remove support for it in 2.0, or later).

**Comment by niallfleming** [comment]
These changes currently prevent any password from being able to login, hashed or not. (SSP 1.18, PHP 7.1). I had to comment out your check in Utils/Crypto pwValid function.

My password was hashed - {SSHA256}xT+lqWvYD...

Although I do note that bin/pwgen.php doesn't give you the option to choose the hash anymore, and just returns a crypted version, which I tried, but got the same result.

Exception cannot use a hash value for authentication.

**Comment by tvdijen** [comment]
I also noticed an issue and posted a fix [here](https://github.com/simplesamlphp/simplesamlphp/commit/f8428e07513e5373d53d4681023ad36c6830744d), but I see we also supported hashed password... It's a bit messy with plain-text, hashed and encrypted passwords.

My suggestion would be to undo the change to 1.18 and add an upgrade note to 1.19 that people should regenerate their admin-password if they used a hash, effectively migrating them to encrypted passwords.

**Comment by niallfleming** [comment]
Yeah I saw your fix, and tested it, but the major issue seems to lie with is_null

Always returns bad:
php > if (!is_null(password_get_info('horse')['algo'])) { echo "bad"; }
bad
php > if (!is_null(password_get_info('$2y$10$sxR7AjGaUx3MMshcdz9eo.YLquKARqctueAf8.EKzOv4hH7FA9kLm')['algo'])) { echo "bad"; }
bad

php > var_dump(is_null(password_get_info('$2y$10$sxR7AjGaUx3MMshcdz9eo.YLquKARqctueAf8.EKzOv4hH7FA9kLm')['algo']));
bool(false)
php > var_dump(is_null(password_get_info('horse')['algo']));
bool(false)

But checking the actual thing with the php function:
php > var_dump(password_get_info('horse')['algo']);
int(0)
php > var_dump(password_get_info('$2y$10$sxR7AjGaUx3MMshcdz9eo.YLquKARqctueAf8.EKzOv4hH7FA9kLm')['algo']);
int(1)

The function returns a 0 not a null on 7.1, 7.2 and 7.3

**Comment by tvdijen** [comment]
Exactly, that's what I figured out as well... It _does_ however return `null` on PHP 7.4, hence my fix to test for both.
I could backport that to 1.18, but that would cause problems for existing setups with hashed passwords.. The migration to 1.19 seems the logical moment to reset the admin password to encrypted passwords, that's why I'm suggesting to revert the last commit on 1.18 and add an upgrade note to 1.19

**Comment by niallfleming** [comment]
It sounds like the best approach to me.

**Comment by thijskh** [comment]
I'm not sure we should revert the change to 1.18 wholesale since it's actually a bug. The whole hashing is moot if you can use it as a password? So I'd prefer we fix 1.18 that at least you cannot use the hash. Indeed it seems a PHP version issue. We can just fix that to work with all versions, right?

**Comment by tvdijen** [comment]
Also fine with me

**Comment by thijskh** [comment]
I have fixed 1.18 now with the same fix that was in 1.19. The testsuite covers this but I didn't get any notification about a build failure.

I do not understand why this would cause problems for existing installs with hashed passwords. These remain working and the testsuite verifies that.

I am not sure what you refer to with 'encrypted passwords' as an option. At least I cannot find this in the documentation of the adminpassword option, or in the test suite. So where is this?

**Comment by tvdijen** [comment]
You won't get any notification because Travis doesn't process our build anymore and the 1.18 branch has not been migrated to Actions.

What I meant is that we have three different types of passwords... Not encrypted of course (my mistake), but different kind of hashes:

// Plaintext
secret

// Hashed - pre 1.17
{SSHA256}62cXZufe4VufLeq0FAAkoh1Py2BKQ/65h4WC2m9EW79mcC8qIDmUzw==

// Hashed 1.17+ generated using password_hash() build-in
$2y$10$2tfNVkf7tRMbkvUhGtoxA.q6ZqWYJ2GTvClGEoJo1rJNZvCLvsS12

The Pre-1.17 hashes should still work and I'm not sure they do after the changes we've made.. Should double-check this.. I don't think we have any tests in place for the new style hashes.

**Comment by niallfleming** [comment]
Can confirm your fix works on ancient PHP ;)

Cheers!

**Comment by thijskh** [comment]
> I don't think we have any tests in place for the new style hashes.

In fact we do - our tests verify that something generated with our current hashing method is accepted by the verification method.

Indeed this is not very complete but the other way around: we do not verify that hashes we generated in the past are still currently accepted. So we could add some of those to the testsuite.

**Comment by tvdijen** [comment]
@thijskh I think this one can be closed, right?
