### ISSUE TITLE
can not install 

### ISSUE THREAD

**Issue by Tome55** [simplesamlphp/simplesamlphp#1461]
I got this error, what I have to do?
Fatal error: Uncaught Error: Undefined constant "SimpleSAML\Error\ASSERT_QUIET_EVAL" in C:\xampp\htdocs\testsso\vendor\simplesamlphp\simplesamlphp\lib\SimpleSAML\Error\Assertion.php:62 Stack trace: #0 C:\xampp\htdocs\testsso\vendor\simplesamlphp\simplesamlphp\www\_include.php(7): SimpleSAML\Error\Assertion::installHandler() #1 C:\xampp\htdocs\testsso\vendor\simplesamlphp\simplesamlphp\www\index.php(3): require_once('C:\\xampp\\htdocs...') #2 {main} thrown in C:\xampp\htdocs\testsso\vendor\simplesamlphp\simplesamlphp\lib\SimpleSAML\Error\Assertion.php on line 62

**Comment by tvdijen** [comment]
This means you are running PHP8, am I right?

**Comment by Krisell** [comment]
That's definitely cause by this package not (yet) being compatible with PHP8. I ran in to the same problem and was a bit confused by the fact that PHP8-problems seems to have been resolved in Januari (https://github.com/simplesamlphp/simplesamlphp/commit/3f31e7d1ef3510905cacd306730b862788e4fe54), but those changes are not included in the latest release (published just a few weeks ago).

We manually made the same changes as https://github.com/simplesamlphp/simplesamlphp/commit/3f31e7d1ef3510905cacd306730b862788e4fe54 and it runs great in PHP8 now for our use case.

Two questions arise here:
 1. Is PHP8 support going to be official in the next release?
 2. Could perhaps the PHP version support be stated more clearly at https://simplesamlphp.org/? `composer.json` does state `< 8.0` but since the release is a zip-files with all vendor packages already included, `composer install` might not actually be run.

**Comment by tvdijen** [comment]
It was not included in 1.19.1 because it is a backwards-incompatible change, so it will only land in 2.0.0 at some point in the future.
We can definitely work on the docs to clearly mark PHP 8.0 as incompatible.

**Comment by Krisell** [comment]
I see – if that is the only reason PHP8 is not supported, couldn't the removed code be put under a php-version guard to allow the next patch/minor version to add support? I do however understand there might be more potential issues with PHP8, we only use a small subset of all features.

I think however this might be a common issue now – with PHP8 being > 6 months old and 7.3 reaching EOL this year.

**Comment by tvdijen** [comment]
@Krisell I don't have PHP 8.0 available...   Would https://github.com/simplesamlphp/simplesamlphp/commit/219ba51b0cc087c78c7ee949f0ccc389728eff39 fix things for you?

**Comment by Krisell** [comment]
> @Krisell @Tome55 I don't have PHP 8.0 available... Would [219ba51](https://github.com/simplesamlphp/simplesamlphp/commit/219ba51b0cc087c78c7ee949f0ccc389728eff39) fix things for you guys?

I definitely think so. I applied https://github.com/simplesamlphp/simplesamlphp/commit/3f31e7d1ef3510905cacd306730b862788e4fe54 to resolve our issues, which was simply that `ASSERT_QUIET_EVAL` was undefined.

**Comment by tvdijen** [comment]
I had to do a little bit more to preserve bc compatibility, but the fix will land in the next bugfix release

**Comment by Krisell** [comment]
Thank you @tvdijen for this and all your work!
