### ISSUE TITLE
core:AttributeMap not applied before SP attribute filtering

### ISSUE THREAD

**Issue by mrvanes** [simplesamlphp/simplesamlphp#1540]
When an SP has a list of requested attributes in it's metadata, these are translated to an `attributes` key in the SP metadata config equivalent. These attributes are then used as an _outgoing_ filter.

If an SP asks for e.g. `urn:oid:1.3.6.1.4.1.5923.1.1.1.6` and we internally set `eduPersonPrincipalName` and apply authproc `100 => ['class' => 'core:AttributeMap', 'name2oid']` on the IdP side of simpleSAMLphp, the attribute is _not_ released, contrary to my expectation.

Setting _internal_ attribute `urn:oid:1.3.6.1.4.1.5923.1.1.1.6` correctly outputs the test attribute to the requesting SP.

My _workaround_, for now, is to remove the generated `attributes` and `attributes.required` keys from the SP metadata and let it be.
This solution correctly sends the _requested_ attributes, _in oid format using the correct attributes.NameFormat_, to the SP. So I'm quite sure the AttributeMap authproc is correctly configured and applied, albeit too late.

**Expected behavior**
I would expect the IdP `core:AttributeMap` to be applied _before_ the SP `attribute` filter is applied.

Tested with simplesamlphp-1.19.1

**Comment by tvdijen** [comment]
It took me a while to figure this out, because we don't specifically apply any attribute-filters.
The reason here is probably that there is a filter in the config-template [here](https://github.com/simplesamlphp/simplesamlphp/blob/master/config-templates/config.php#L978) with a priority of `50` that is enabled by default.

From the docs:

```
When Auth Proc Filters is configured in multiple places, in example both globally, in the hosted IdP and remote SP metadata, then the list is interleaved sorted by priority.
```

@mrvanes I know it's been a while, but do you perhaps still have this environment up and running? Could you try and verify that this is a matter of priority of the filters?

**Comment by mrvanes** [comment]
I don't even remember in what environment I encountered this problem, let alone have it lying around. Sorry.

**Comment by tvdijen** [comment]
No problem! I think we just have to close this issue then..
