### ISSUE TITLE
2.0: metadata.sign-settings no longer work on metadata

### ISSUE THREAD

**Issue by tvdijen** [simplesamlphp/simplesamlphp#1791]
**Describe the bug**
The [`metadata.sign`](https://github.com/simplesamlphp/simplesamlphp/blob/master/docs/simplesamlphp-advancedfeatures.md#metadata-signing)-settings should be configurable both globally in config.php as in the metadata for a specific entity. The global setting still works, but the metadata-local one is no longer working.

**To Reproduce**
Try using the setting in a metadata-section

**Expected behavior**
See signed metadata in the admin federation-tab.

**Additional context**
This is probably the result of some refactoring between 1.19 and 2.0.

**Comment by thijskh** [comment]
Before we re-add this, what is the use case where you’d want to sign some metadata you produce but not sign other? Does it hurt? It seems a bit like a corner case.

**Comment by tvdijen** [comment]
It's not my use-case but @ghalse his case. I would be fine with it, but in this case we have to a) fix the docs and b) add a proper upgrade note that this has changed in 2.0

**Comment by ghalse** [comment]
We sign metadata on one side of a protocol bridge, since that's consumed automatically by the downstream; the other side is manually curated in our federation. So we don't need it signed, which is why I was only doing this in saml20-idp-hosted.php

I'm happy to change my practice if that's the decision. There's no harm for me in signing all the metadata (just wasted CPU cycles occasionally). It is how I am currently working around the problem.

However, the crux of this issue is that behaviour that worked in 1.19.4 has stopped working, and that's not documented in the release notes. In addition the documentation still suggests it should work. So either we need to fix the regression, or we need to decide it is by design and fix the documentation and release notes :)

**Comment by ghalse** [comment]
Just to note by way of an aside, the 1.19.4 behaviour allows you to use different signing keys for different metadata. I don't have a use case for doing that, but I thought I'd mention it anyway since removing the metadata level options would mean you could only use one key.
