### ISSUE TITLE
Timeframe to release Symfony 6 support?

### ISSUE THREAD

**Issue by RoSk0** [simplesamlphp/simplesamlphp#1798]
First of all thanks for all the work .

I can see that Symfony 6 support is already merged and I went through related issues and PRs , but there is no clear indication of when do you think it would be possible to release that work.

Sometime soon in 2.1 (hopefully) or is that something that really will wait till v3 ?

**Comment by tvdijen** [comment]
There currently is no roadmap or release schedule, so there is no way to tell right now.
Consider installing SSP _separate_ from your Symfony 6 application, so our dependencies do not conflict with your apps' dependencies.

**Comment by RoSk0** [comment]
Thanks for the quick reply. 

Unfortunately for us, decoupling isn't possible because SSP is part of the application. We built a Drupal based IdP for client where Drupal acts as a UI and user self-service portal, and authentication source based on https://github.com/drupalauth/simplesamlphp-module-drupalauth and https://www.drupal.org/project/drupalauth4ssp . Drupal is bootstrapped from inside authn source plugin.

With Drupal 10 requiring Symfony 6 and Drupal 9 EOL this December we are in a very interesting position. Well, we have a bit of time will then.

**Comment by tvdijen** [comment]
None of these drupal modules are compatible with SSP 2.0, so you have more challenges..

**Comment by markfullmer** [comment]
Thanks for responding to this issue, @tvdijen . I would like to request more technical information, however, on what the motivation for not declaring multiple compatibility with Symfony 5 or 6 in the 2.x version of simplesamlphp is.

Symfony 6 drops support for PHP 7. I can understand that the maintainers of `simplesamlphp`, wishing to provide ongoing support for the broader community of PHP users, are not yet ready to drop PHP 7 support. However, by using a Composer requirement of `"^5.4 || ^6"` for `symfony` components, as is done in the `master` branch, applications can still require PHP 7 and use simplesamlphp by using Symfony 5.

Is there any other technical reason that the 2.x version cannot declare `"^5.4 || ^6"` compatibility?

Anecdotally, I can offer that our organization has been using the `master` branch of this library with a Symfony 6-based application (Drupal 10) since February 2023 without issue.

In the absence of a Symfony 6-compatible release of `simplesamlphp` our team is considering temporarily forking this library and creating a tag from the `master` branch so that we can use it with Symfony 6 until `simplesamlphp` provides its own release that is Symfony-6 compatible. Do you have any opinions on this? We would prefer not to do this, and I assume there are many other Drupal 10 developers who are in the same situation.

Thanks in advance for your input!

**Comment by tvdijen** [comment]
> Is there any other technical reason that the 2.x version cannot declare `"^5.4 || ^6"` compatibility?

I simply couldn't get both versions to work simultaneously due to signature changes. Feel free to contribute.

**Comment by Berdir** [comment]
See https://github.com/simplesamlphp/simplesamlphp/pull/1675#issuecomment-1216778610 and following comments for context. It was reverted because the changes were incompatible with PHP 7.4.

The reason to not include Symfony 6 support in 2.0 was because it is only possible to be Symfony 6 compatible when dropping PHP 7 support, it is no problem at all to be compatible with Symfony 5 and 6 at the same time, that is the case now in master.
