### ISSUE TITLE
2.0: UIInfo not shown in SSP-metadata for hosted SP

### ISSUE THREAD

**Issue by tvdijen** [simplesamlphp/simplesamlphp#1808]
**Describe the bug**
UIInfo not shown in SSP-style metadata array for the hosted SP

**To Reproduce**
1. Go to the admin page of an SP-instance of SimpleSAMLphp
2. Click on the Federation-tab
3. Drop down the metadata for the hosted SP
4. See that UIInfo is shown in the XML metadata, but not in the SSP-metadata array

**Expected behavior**
The UIInfo should be there.

**Comment by thijskh** [comment]
The fix is simple because this is done explititly in https://github.com/simplesamlphp/simplesamlphp/blob/1a911ce99946df994af0163b73a528a15502cace/modules/admin/src/Controller/Federation.php#L361

Tracing this back, it has been in the admin module from the first commit, and it seems likely to be copied from the 1.x way of generating SSP metadata which also has this removal of UIInfo from the array from the very first commit: 132a0dd2bfbdd8646161c68d244c504eadbc14a2. I do not know why this was done then, @jaimeperez maybe remembers? But it seems safe to just remove the unset since we do add UIInfo for IdP generated array form metadata.
