### ISSUE TITLE
Needed D10 or higher support for simplesamlphp for multiple websites.

### ISSUE THREAD

**Issue by arnabcse2013** [simplesamlphp/simplesamlphp#1820]
**Is your feature request related to a problem? Please describe.**
I am currenly using simplesamlphp/simplesamlphp for my multiple websites. Now I have migrated to D10.1 version and unable to install the package due to multiple package issues.

**Describe the solution you'd like**
Please share an update for this package and after migration we are stuck and is unable to install simplesamlphp and its related contrib modules.

**Describe alternatives you've considered**
I tried using lenient. But still I failed because of multiple packages of symfony using older versions. Please release a new update for

**Comment by tvdijen** [comment]
What _on earth_ is D10?

**Comment by arnabcse2013** [comment]
Drupal 10 my friend. :)

**Comment by tvdijen** [comment]
OK, and what appears to be the issue? "unable to install the package due to multiple package issues" is not something I can work with.. Error messages? Screenshots?

**Comment by sofiaolinda** [comment]
Hi, 
I have a compatibility problem with Drupal 10, I can't install simplesamlphp/simplesamlphp : dev-master because it requires the
symfony/psr-http-message-bridge : ^2.3, however Drupal 10.1 requires symfony/psr-http-message-bridge : ^2.1. Does anyone have a solution for this?
If I install simpleamlphp/simplesamlphp : ^2.5 it requires symfony/console version : ^5, but Drupal 10 requires version ^6.2.

**Comment by tvdijen** [comment]
Try `dev-simplesamlphp-2.1` instead.
