### ISSUE TITLE
Support Assertion without NameID in subject (was #289)

### ISSUE THREAD

**Issue by sspghost** [simplesamlphp/simplesamlphp#19]
_From [olavmrk@gmail.com](https://code.google.com/u/olavmrk@gmail.com/) on February 05, 2010 09:43:38_

The Subject element does not require a NameID.

_Original issue: http://code.google.com/p/simplesamlphp/issues/detail?id=289_

**Comment by SurendraYellu** [comment]
Hi, i am getting the below error
Exception: Missing <saml:NameID> or <saml:EncryptedID> in <saml:Subject>.

Is it coming because of this issue? Thanks.

**Comment by thijskh** [comment]
Most likely. You can verify by examining the assertion exchanged (using e.g. the Firefox SAML Tracer plugin) to see if they contain a NameID.

A fix would be to configure the involved IdP to actually do send a NameID. It's recommended by http://saml2int.org afterall ("SHOULD").

**Comment by jaimeperez** [comment]
Hi!

I've just committed a fix for this, which was unfortunately not easy since it involves both SimpleSAMLphp and the SAML2 library. In order to solve the issue, those affected should upgrade to bcd7240, and run `composer update` to get the latest 1.9 version of the SAML2 library.

In any case, this is a fix that intends to be *graceful*, allowing SPs to still work with assertions that are valid according to the SAML standard, but invalid according to the [SAML2 Interoperability profile](http://saml2int.org/). It is important to note that even things will now work and you won't see any more exceptions about this, **it comes with side effects**. Basically, **the SAML2 logout profile requires a `NameID`** to be present. This means if no `NameID` was provided by the IdP authenticating the user, logout will be disabled for it. Therefore, **if the user tries to log out, only a local logout will be performed, and the IdP session will still be in place**.

This has security consequences, so please, instead of just relying on this fix and forgetting about the problem, **make sure the IdP sends a `NameID` in the assertions**.

**Comment by pitbulk** [comment]
I don't know why in the new versión of samlint the NameID is not mandatory. In my opinión it should be.
I will keep that requirement on my toolkits, as you mention jaimeperez, this change turn the environment less stsble.

**Comment by thijskh** [comment]
I can see the use case: we have quite a significant number of IdP's which do not send it by default (ADFS); they can configure it but also in many times it's not used in our setup so we know it's just busywork. We live with that, but I can see the case for making it optional.

Especially because this is the receiving end: SSP should be strict in sending NameID by default, but can be liberal in what it accepts on incoming assertions.

**Comment by jaimeperez** [comment]
Couldn't agree more :+1:

**Comment by thijskh** [comment]
So use the like button ;)

**Comment by jaimeperez** [comment]
Uhm, I saw reactions some time ago but didn't bother to click on it and check what was possible... Nice!

**Comment by trscavo** [comment]
> SSP should be strict in sending NameID by default, but can be liberal in what it accepts on incoming assertions.

Be careful what you ask for. If the SP asks for a specific NameID, then that's what it gets (or an error). If the SP is prepared to be "liberal in what it accepts," then it should omit NameIDPolicy in the request.

**Comment by gardenia** [comment]
@jaimeperez apologies for following-up on a closed issue but I tried the latest code and while I can verify that NameIDPolicy is optional in the response I'm not clear how to make it optional on the request side.

previously I had been doing this:
`'NameIDPolicy' => null,`

in the config/authsources.php but this now fails with the following exception:

```
Exception during login:
Exception: [ARRAY]: The option 'Format' is not a valid string value.
Backtrace:
8 /var/www/saml/simplesamlphp/lib/SimpleSAML/Configuration.php:660 (SimpleSAML_Configuration::getString)
7 /var/www/saml/simplesamlphp/modules/saml/lib/Message.php:421 (sspmod_saml_Message::buildAuthnRequest)
6 /var/www/saml/simplesamlphp/modules/saml/lib/Auth/Source/SP.php:187 (sspmod_saml_Auth_Source_SP::startSSO2)
5 /var/www/saml/simplesamlphp/modules/saml/lib/Auth/Source/SP.php:316 (sspmod_saml_Auth_Source_SP::startSSO)
4 /var/www/saml/simplesamlphp/modules/saml/lib/Auth/Source/SP.php:390 (sspmod_saml_Auth_Source_SP::authenticate)
3 /var/www/saml/simplesamlphp/lib/SimpleSAML/Auth/Source.php:193 (SimpleSAML_Auth_Source::initLogin)
2 /var/www/saml/simplesamlphp/lib/SimpleSAML/Auth/Simple.php:141 (SimpleSAML_Auth_Simple::login)
1 /var/www/saml/simplesamlphp/modules/core/www/authenticate.php:41 (require)
0 /var/www/saml/simplesamlphp/www/module.php:127 (N/A)
```

however when I don't try to set NameIDPolicy to null but rather just leave it at the default but comment out $ar->setNameIdPolicy($policy); in modules/saml/lib/Message.php then I can see that the response is now handled even though it lacks a nameidpolicy.

it looks like NameIDPolicy is now expected to be a dictionary (in modules/saml/lib/Message.php) but it isn't clear to me how I would mandate that it should be omitted.  one way would be to wrap the nameIdPolicy in 

```
if ($nameIdPolicy === null) {
    // 
}

```
but I don't want to propose that if there is already a better defined way.

Apologies if I'm off base with this.  I'm pretty new to this project so I might be just off on one here.
