### ISSUE TITLE
Is tempdir still used

### ISSUE THREAD

**Issue by thijskh** [simplesamlphp/simplesamlphp#1933]
We have a tempdir setting next to a cachedir setting.

Is it still needed to have two writable directories?

It seems that we use it in one place: writeFile():
https://github.com/simplesamlphp/simplesamlphp/blob/0dbf3d7b0914fead3926b612604f1fea6721cd10/src/SimpleSAML/Utils/System.php#L212
But this approach is flawed - it seemed originally designed with the assumption that the tempdir was still under SSP's own dir. But since we default the tempdir now to `/tmp` the whole atomicity is gone and we should rewrite that function to get it back.

In any case, besides writeFile(), do we have any other need for the tempdir?

**Comment by tvdijen** [comment]
Currently two uses of the tempdir-setting:
- the saml2-lib uses the temp-dir inside the SOAPClient to store certificates.
  I think this is more of a cache-purpose than actual temp-file purpose.
- The aggregator2-module uses it as a fallback for when the (module local) cachedir setting doesn't exist.

Maybe instead of my PR #1932 we should rename tempdir to cachedir and set the default to `/var/cache/simplesamlphp`.

**Comment by thijskh** [comment]
Good suggestion!

**Comment by tvdijen** [comment]
Changed tempdir to cachedir in a backwards-compatible way. Marked tempdir as deprecated in the config template and added a not in the upgrade notes.
