### ISSUE TITLE
SCIM Support

### ISSUE THREAD

**Issue by BarnumD** [simplesamlphp/simplesamlphp#2050]
**Is your feature request related to a problem? Please describe.**
Some service providers do not allow for user manual user provisioning or JIT provisioning, but instead have switched to supporting the SCIM protocol.  Is there any plan to support SCIM? https://developer.okta.com/docs/concepts/scim/

**Comment by tvdijen** [comment]
We would have called our software SimpleSCIM if we would.
Feel free to implement SCIM in a custom module.

**Comment by jaimeperez** [comment]
To elaborate a bit more on Tim's response, SCIM is specific to the actual user storage in use. SimpleSAMLphp is agnostic when it comes to this, meaning you can use whatever user storage you want, and it provides several modules that allow you to authenticate against the most typical (e.g. a SQL database).

This means SSP cannot really offer SCIM support on its own, neither for provisioning users into it from external applications, nor for provisioning of its own users into service providers. If anything, those modules that add support for specific backends (to follow the previous example, [simplesamlphp-module-sqlauth](https://github.com/simplesamlphp/simplesamlphp-module-sqlauth)) would need to implement SCIM instead, and the most logical thing would be that they implement support for a SCIM server, not a client. That's not in our roadmap (and we don't even maintain all those modules), but contributions are always welcome, of course.

If you just need to be able to push users from SSP acting as an IdP into a given SP, for now you will need to implement that yourself. Since you control the backend, that should be relatively simple, though.
