### ISSUE TITLE
replace mcrypt by openssl

### ISSUE THREAD

**Issue by gfaust-qb** [simplesamlphp/simplesamlphp#228]
That what now is called aesDecrypt and aes Encrypt is not AES256!
This happens because Rijndael-256 is not AES-256. (See also http://www.leaseweblabs.com/2014/02/aes-php-mcrypt-key-padding/)
You could replace mcrypt by openssl which is more performant, easier to use and better supported. 
Here is an example (just a poc) how to replace mcrypt by openssl and reduce the dependencies:

    function opensslAesEncrypt($clear) {
        assert('is_string($clear)');

        if (!function_exists("openssl_digest")) {
            throw new Exception("o_aesEncrypt needs openssl php module.");
        }

        $key    = openssl_digest('defaultsecretsalt', 'sha256');
        $method = 'AES-256-CBC';
        $ivSize = openssl_cipher_iv_length($method);
        $iv     = openssl_random_pseudo_bytes($ivSize);
        $data   = openssl_encrypt ($clear, $method, $key,    'OPENSSL_RAW_DATA'|'OPENSSL_ZERO_PADDING', $iv);
        return $iv.$data;
    }

    function opensslAesDecrypt($encData) {
        assert('is_string($encData)');

        if (!function_exists("openssl_decrypt")) {
            throw new Exception("aesDecrypt needs openssl php module.");
        }

        $key    = openssl_digest('defaultsecretsalt', 'sha256');
        $method = 'AES-256-CBC';
        $ivSize = openssl_cipher_iv_length($method);
        $iv     = substr($encData,0,$ivSize);
        $data   = substr($encData,$ivSize);
        $clear  = openssl_decrypt ($data, $method, $key, 'OPENSSL_RAW_DATA'|'OPENSSL_ZERO_PADDING', $iv);

        return $clear;
    }

**Comment by jaimeperez** [comment]
Hi @gfaust-qb!

Thanks a lot for your suggestion. You are right about the name for both `aesEncrypt()` and `aesDecrypt()` being quite unfortunate. Even though AES is basically Rijndael, the implementation by *mcrypt* uses the numerical suffix in the algorithm name to refer to the block size (which is fixed to 128 in AES), instead of the key size, and hence the confusion.

Fortunately, that's not a big issue since both functions are mainly for internal use (actually, I only see them used in one place), and both parties (the one encrypting and the one encrypting) are the same, so there's no risk of incompatible encryption/decryption.

However, I see two advantages on moving to OpenSSL. One is getting rid of the *mcrypt* requirement. I don't see any other place where it is used, except for modules (like InfoCard, no longer in the code base, nor even in use, I think) and external libraries like xmlseclibs (and the functionalities there requiring *mcrypt* are not in use by SSP, I think, again). Performance is the other obvious advantage. I've made a quick test involving chained encryption and decryption with both OpenSSL and *mcrypt* implementations. After a hundred thousand executions, the mean time elapsed with *mcrypt* was 0.0011401176452637, for 0.00019418417453766 on average used by OpenSSL. It might seem really negligible time, but the difference is actually of one order of magnitude.

So I'm going to take a look into reimplementing this with OpenSSL :wink:

**Comment by gfaust-qb** [comment]
@jaimeperez I developed a Version without using Mcrypt totally. There is some work left until I make a PR for this Version in robrichards/xmlseclibs, but his support is very slow - even for accepted PRs.
If you want to have a look now, just look at https://github.com/gfaust-qb/xmlseclibs/tree/Specified_Exception (and integrated in simplesamlphp -> https://github.com/gfaust-qb/simplesamlphp).

**Comment by jaimeperez** [comment]
Hi @gfaust-qb!

Rob is a busy guy and we need to help him making everything as smooth as possible, then he's able to reply faster. In this particular case, the decision is tough. We already depend on `phpseclib`, so your solution would fit easily, but performance could be an issue.

I'd recommend you to make a full PR with your implementation, make it as easy to digest as possible, and even attach some performance tests. Then let's see what Rob thinks.

**Comment by gfaust-qb** [comment]
Hi @jaimeperez !

I tried to avoid phpseclib/phpseclib but ran into troubles with Zero-Padding and PHP 5.3 when using pure openssl. At the moment I had no more time to look for the pure openssl-solution and built this as a temporary solution - with the goal to replace it by a pure openssl-Solution.

Thanks for your comments & Kind Regards

Guido

**Comment by jaimeperez** [comment]
That's great then. If you manage to get a pure-openssl solution I'm pretty sure Rob will be happy with it. Just let me know if I can help somehow.
