### ISSUE TITLE
Redundant replay attack protection in modules/saml/www/sp/saml2-acs.php?

### ISSUE THREAD

**Issue by aas395** [simplesamlphp/simplesamlphp#230]
This is for version 1.13.2. 

I'm a big fan of simplesamlphp so far, but I ran into an issue with a partner of ours that I couldn't get past.

They're using the IdP-initiated flow to allow their users to authenticate into our application, and the first time a user clicks on the link on their side to authenticate, everything works fine. The authentication happens in a new window, leaving the original window where they authenticated open (without changing the SAML data). If a user goes back to that page after authentication and tries to authenticate again without reloading the page, they see an "unhandled exception" error on our side (error number 99d0369cc7), which I traced back to line 116 of /saml/www/sp/saml2-acs.php, where it's rightly seeing the same data being passed and throwing an exception to prevent replay attacks.

What I didn't understand, though, was that there seems to be some code around line 39 of the same file doing the same replay attack check in a more intelligent way, and some comments indicating that this was put in place to try to prevent the exact scenario I'm describing, where a user tries to auth from the same place twice and sees an error.

Our partner is asking me to fix this, but I wasn't sure whether the error being thrown is intended behavior and I wasn't quite grasping the flow of the file, or whether this second check that throws the error for me was redundant.

Please let me know if you need any other information from me.

**Comment by aas395** [comment]
Looking at this a bit more I wonder whether the problem is that the $prevAuth variable on line 38 of saml2-acs.php can't ever be non-empty in IdP-first flows. As far as I can tell, the $state['SimpleSAML_Auth_Default.ReturnURL'] value is only ever set in certain login functions (like in lib/SimpleSAML/Auth/Default::initLogin()) that are only called in SP-originating flows. The ReturnURL parameter needs to be set for the check on line 191 of saml2-acs.php to pass, which sets $state['saml:sp:prevAuth'], which populates $prevAuth the next time the saml response is sent.

**Comment by aas395** [comment]
I got this to work by adding the stuff being done on line 210 of saml2-acs.php to the "unsolicited response" section around line 81:

$relayState = SimpleSAML_Utilities::checkURLAllowed($response->getRelayState());

	if(empty($relayState)) {
		$authSourcesConfig = SimpleSAML_Configuration::getConfig('authsources.php');
		$spConfig = $authSourcesConfig->getValue($sourceId);

		if($spConfig['RelayState']) {
			$relayState = $spConfig['RelayState'];
		}
	}

	$state = array(
		'saml:sp:isUnsolicited' => TRUE,
		'saml:sp:AuthId' => $sourceId,
		'saml:sp:RelayState' => $relayState,
		'saml:sp:prevAuth' => array(
			'id' => $response->getId(),
			'issuer' => $idp,
			'redirect' => $relayState,
		)
	);

	$state['PersistentAuthData'][] = 'saml:sp:prevAuth';

This sets the $prevAuth variable so that next time the IdP sends an unsolicited response, it recognizes that this was a duplicate response from that host and no longer throws the error. This works for me for now but I'd love to hear whether this might create any security vulnerabilities that I couldn't foresee.

**Comment by jaimeperez** [comment]
Hi @aas395!

Thanks a lot for reporting this issue! You are absolutely correct, there's a bug in the Assertion Consumer Service leading to the exception your customer is experiencing. The problem here is that the code setting information about the current auth (which is later used as the previous auth to discern if the response is a duplicate) is only being executed if `'SimpleSAML_Auth_Default.ReturnURL'` is set in the state array. Since this URL is set in the `SimpleSAML_Auth_Default` class, it is never set when dealing with unsolicited responses. No information at all is stored then, leading to the code detecting the duplicate not being executed.

Additionally, the code saving the RelayState when an unsolicited response is found was using the RelayState parameter coming in the response, ignoring the one possibly configured in the SP's metadata. The latter should definitely have precedence, since it's something the SP controls, rather than something coming from a third party. The RelayState accompanying the response may not even be an URL (it shouldn't, indeed, though in SimpleSAMLphp we kind of ignored the specs a bit for convenience), so it should not be trusted blindly, and therefore we should use it as a last resort.

I've made some changes to the file that should hopefully fix your issue. Could you please apply this patch  (may not apply directly, since it was generated from master, not 1.13.2) and confirm that it works as intended?

Thanks!

```patch
---
 modules/saml/www/sp/saml2-acs.php | 31 ++++++++++++++++++++-----------
 1 file changed, 20 insertions(+), 11 deletions(-)

diff --git a/modules/saml/www/sp/saml2-acs.php b/modules/saml/www/sp/saml2-acs.php
index 68751e3..ff49590 100644
--- a/modules/saml/www/sp/saml2-acs.php
+++ b/modules/saml/www/sp/saml2-acs.php
@@ -60,7 +60,12 @@ if ($prevAuth !== NULL && $prevAuth['id'] === $response->getId() && $prevAuth['i
 	 * instead of displaying a confusing error message.
 	 */
 	SimpleSAML_Logger::info('Duplicate SAML 2 response detected - ignoring the response and redirecting the user to the correct page.');
-	\SimpleSAML\Utils\HTTP::redirectTrustedURL($prevAuth['redirect']);
+	if (isset($prevAuth['redirect'])) {
+		\SimpleSAML\Utils\HTTP::redirectTrustedURL($prevAuth['redirect']);
+	}
+
+	SimpleSAML_Logger::info('No RelayState or ReturnURL available, cannot redirect.');
+	throw new SimpleSAML_Error_Exception('Duplicate assertion received.');
 }
 
 $idpMetadata = array();
@@ -90,7 +95,11 @@ if (!empty($stateId)) {
 	$state = array(
 		'saml:sp:isUnsolicited' => TRUE,
 		'saml:sp:AuthId' => $sourceId,
-		'saml:sp:RelayState' => \SimpleSAML\Utils\HTTP::checkURLAllowed($response->getRelayState()),
+		'saml:sp:RelayState' => \SimpleSAML\Utils\HTTP::checkURLAllowed($spMetadata->getString(
+				'RelayState',
+				$response->getRelayState()
+			)
+		),
 	);
 }
 
@@ -196,17 +205,17 @@ if ($expire !== NULL) {
 	$state['Expire'] = $expire;
 }
 
+// note some information about the authentication, in case we receive the same response again
+$state['saml:sp:prevAuth'] = array(
+	'id'     => $response->getId(),
+	'issuer' => $idp,
+);
 if (isset($state['SimpleSAML_Auth_Default.ReturnURL'])) {
-	/* Just note some information about the authentication, in case we receive the
-	 * same response again.
-	 */
-	$state['saml:sp:prevAuth'] = array(
-		'id' => $response->getId(),
-		'issuer' => $idp,
-		'redirect' => $state['SimpleSAML_Auth_Default.ReturnURL'],
-	);
-	$state['PersistentAuthData'][] = 'saml:sp:prevAuth';
+	$state['saml:sp:prevAuth']['redirect'] = $state['SimpleSAML_Auth_Default.ReturnURL'];
+} elseif (isset($state['saml:sp:RelayState'])) {
+	$state['saml:sp:prevAuth']['redirect'] = $state['saml:sp:RelayState'];
 }
+$state['PersistentAuthData'][] = 'saml:sp:prevAuth';
 
 $source->handleResponse($state, $idp, $attributes);
 assert('FALSE');
```

**Comment by aas395** [comment]
Great, thanks so much!

I had to tweak the patch a bit but the logic works. Just to make sure, do you think this is safe from a security standpoint? I know the library protects from replay attacks in the sp-initiated flow, but I just want to make sure we're safe in IdP-initiated flows, too.

**Comment by pmeulen** [comment]
Hi,

> On 21 Jul 2015, at 18:18, aas395 <notifications@github.com> wrote:
> 
> Great, thanks so much!
> 
> I had to tweak the patch a bit but the logic works. Just to make sure, do you think this is safe from a security standpoint? I know the library protects from replay attacks in the sp-initiated flow, but I just want to make sure we're safe in IdP-initiated flows, too.

AFAIK the only protection agains a replay attack in SSP when using the IdP initiated flow is the limited validity specified in the assertion NotBefore / NotAfter. The problem is that there is no nice way of implementing replay protection in the IdP initiated flow. In the SP Initiated flow the ID of the AuthnRequest generated by the SP is matched agains the InResponseTo in the Assertion from the IdP to prevent against replay. When using the IdP initiated flow that is not possible. The only way I can think off you can offer similar protection (dependant on the reliability of SPs storage) is to store the ID of the Assertions the SP received at the SP and use this as a blacklist for incoming Assertions. When NotAfter + some slack has passed IDs can be removed from the blacklist.

> —
> Reply to this email directly or view it on GitHub.

Pieter.

**Comment by jaimeperez** [comment]
Hi!

Not exactly, Pieter. SSP does indeed what you are suggesting. It protects against replay attacks further than checking the `NotBefore` / `NotAfter` fields, by getting the `xs:ID` of every assertion received (regardless of whether it was an IdP-first flow or not) and stores it in persistent storage, using `NotOnOrAfter` (or a 60 secs default) as expiration time. Before saving the ID to storage, it checks if that ID was used before, triggering the exception @aas395 is reporting, if so. This is the code handling the situation:

```php
foreach ($assertions as $assertion) {

	/* Check for duplicate assertion (replay attack). */
	$store = SimpleSAML_Store::getInstance();
	if ($store !== FALSE) {
		$aID = $assertion->getId();
		if ($store->get('saml.AssertionReceived', $aID) !== NULL) {
			$e = new SimpleSAML_Error_Exception('Received duplicate assertion.');
			SimpleSAML_Auth_State::throwException($state, $e);
		}

		$notOnOrAfter = $assertion->getNotOnOrAfter();
		if ($notOnOrAfter === NULL) {
			$notOnOrAfter = time() + 24*60*60;
		} else {
			$notOnOrAfter += 60; /* We allow 60 seconds clock skew, so add it here also. */
		}

		$store->set('saml.AssertionReceived', $aID, TRUE, $notOnOrAfter);
	}
```

In any case, I think we should distinguish two different scenarios here. One is **accidental duplicate responses**, triggered by a bad implementation or erratic behaviour of the user, and the other is a **replay attack**. Both are different and therefore cannot be treated equally, and that's why there's two pieces of code doing something very similar.

### Accidental duplicate responses

These are the consequence of a faulty implementation in the IdP or the user's browser, or a sum of unfortunate coincidences together with the user doing something wrong, leading to a `SAMLResponse` being sent again to the Service Provider. There's no security issues here, since the same user is involved both in the first authentication and the duplicate. This is therefore a **usability** issue, given that we don't want users to get an ugly exception if we can recover from it and let them continue their work.

The issue you are reporting @aas395 falls into this category.

#### How does it happen?

In this case, the same `SAMLResponse` is sent twice. When the second response arrives, there's an existing, valid session (just created by the first response received), since it's the same user triggering the resend.

#### How to solve it?

The first time we authenticate, we create a session. We can then save the ID of the response just received in the session. When the user triggers a resend somehow, we can then check an existing session. If the session contains information about the previous authentication, and the ID of the previous response **plus** its issuer is the same as in the current response, then we can assume the current response is a duplicate, ignore it, and try to fail gracefully (i.e.: redirect the user to wherever we can). This is the code handling this situation:

```php
$session = SimpleSAML_Session::getSessionFromRequest();
$prevAuth = $session->getAuthData($sourceId, 'saml:sp:prevAuth');
if ($prevAuth !== NULL && $prevAuth['id'] === $response->getId() && $prevAuth['issuer'] === $idp) {
	/* OK, it looks like this message has the same issuer
	 * and ID as the SP session we already have active. We
	 * therefore assume that the user has somehow triggered
	 * a resend of the message.
	 * In that case we may as well just redo the previous redirect
	 * instead of displaying a confusing error message.
	 */
	SimpleSAML_Logger::info('Duplicate SAML 2 response detected - ignoring the response and redirecting the user to the correct page.');
	\SimpleSAML\Utils\HTTP::redirectTrustedURL($prevAuth['redirect']);
}
```

#### What's the issue?

The problem here is that the code was taking into account SP-initiated flows, but not IdP-initiated ones. In both cases, a duplicate is a duplicate, and it should be ignored. However, the code saving information about a response to later discern if we have a duplicate or not, was only executed for SP-initiated flows. My patch addresses this issue by considering both flows, saving the information in both cases, and using a different URL where to redirect to, depending on the case.

This is the problematic code. Note that `$state['SimpleSAML_Auth_Default.ReturnURL']` **won't be set** for IdP-first flows:

```php
if (isset($state['SimpleSAML_Auth_Default.ReturnURL'])) {
	/* Just note some information about the authentication, in case we receive the
	 * same response again.
	 */
	$state['saml:sp:prevAuth'] = array(
		'id' => $response->getId(),
		'issuer' => $idp,
		'redirect' => $state['SimpleSAML_Auth_Default.ReturnURL'],
	);
	$state['PersistentAuthData'][] = 'saml:sp:prevAuth';
}
```

### Replay attacks

These ones involve an attacker managing to capture a `SAMLResponse`, and trying to use it again to obtain a valid session from the recipient SP, impersonating the victim's identity. In this case, we have two users (with their different browsers), the victim and the attacker, and the same IdP and SP.

#### How does it happen?

An attacker captures somehow a valid `SAMLResponse` sent from an IdP to an SP after the victim having successfully authenticated. Then the attacker *replays* that response from his own system to get a valid session, being authenticated as the victim. If the SP does not have appropriate security measures, the attack would be successful.

#### How to solve it?

The only way to protect against this attack, as Pieter is saying, is to have a persistent, common storage for all users in the SP. When an SP receives a `SAMLResponse`, it must grab the assertion and save its ID to make sure that one is never seen again (at least while it's valid). Why the assertion? Because that's the meaningful part of the protocol. A `SAMLResponse` **may not** be authenticated, while a `SAMLAssertion` **should**. Therefore, if we just keep track of the response ID, an intelligent attacker could leverage the fact that responses may not be authenticated, wrap the captured assertion inside a new response with a new ID, and get through. The first code excerpt is the one handling this situation.

Why can't we use the session and need a persistent storage? Because we have two users, the victim and the attacker, and therefore they don't share the session, so the values you save into the session for the victim are not in the session of the attacker (if any at all). Of course we are assuming the attacker captures the response somehow without being able to see the exchange of the user with the SP. If he or she manages to get the same session in the SP, then we don't care about replay attacks because the attacker already can get a valid session anyway.

----

To summarize:

* This issue is a usability issue, not a security one.
* The patch allows detection of duplicate SAML responses in IdP-first flows, which was not possible before.
* If the code handling accidental duplicates is triggered, that's because we have a session with information about a previous authentication, so it cannot be a replay attack.
* Replay attacks are still not covered by the code handling accidental duplicates, as there's no previous session (or no previous authentication information in it).
* However, they are indeed covered by a later check in the code. In order to create a valid session, assertions will always be examined. If a duplicate assertion is found, an exception will be thrown.

So of course I could have made some mistake, but I'm pretty confident that the patch should not introduce any security issues :smiley:

**Comment by aas395** [comment]
Wow, thank you so much for the thorough explanation, Jaime.

**Comment by jaimeperez** [comment]
No prob! It was actually helpful for me too to make sure I was not missing anything :wink:

**Comment by pmeulen** [comment]
Thanks for the though description Jaime, very useful!

Good to realise that when using a setup when servers do not share the storage (e.g. in a cookie based setup) you won't benefit from this protection.
