### ISSUE TITLE
how to get username/password in auth proc filter

### ISSUE THREAD

**Issue by spaceone** [simplesamlphp/simplesamlphp#231]
https://simplesamlphp.org/docs/stable/simplesamlphp-authproc#section_3

The documentation says that the &$request argument of SimpleSAML_Auth_ProcessingFilter->process() is an array which contains attributes and metadata of the SP.
I could not find the username and pasword of that user in the array. I could find them in $_REQUEST but I am wondering if it is safe to use $_REQUEST to get these data?!

**Comment by spaceone** [comment]
The documentation could also directly mention what schema that array has.

**Comment by thijskh** [comment]
That's definitely not safe because the user may have been authenticated by a method that doesn't have  passwords at all, e.g. the authX509 module.

I would pose your question to the mailing list detailing what it is that you want to achieve, because I think you may be barking up the wrong tree here.

**Comment by jaimeperez** [comment]
An authproc filter is not supposed to handle usernames and passwords. When the documentation talks about attributes, it refers to the attributes describing the user **after** being authenticated (affiliation, entitlements, mail, etc), not to the username and password.

As Thijs says, you may authenticate a user by other means instead of typical password authentication, so your filter should never depend on that. Additionally, authproc filters may redirect to other pages or alter the flow in many unforeseeable ways, so depending on your configuration (and the order your filters are executed), your filter may have a completely different set of data available in $_REQUEST.

Please, refer to the [users or developers mailing lists](https://simplesamlphp.org/lists) to describe your use case and ask for advice on how to achieve your specific goals.

**Comment by spaceone** [comment]
What is the mail address of the mailing list? I successfully registered but there is nowhere the mail address on https://simplesamlphp.org/lists. Is it simplesamlphp+noreply@googlegroups.com ?

**Comment by thijskh** [comment]
It's indeed that, but without the `+noreply` part.
