### ISSUE TITLE
Clean up jQuery versions (was #316)

### ISSUE THREAD

**Issue by sspghost** [simplesamlphp/simplesamlphp#24]
_From [olavmrk@gmail.com](https://code.google.com/u/olavmrk@gmail.com/) on May 20, 2010 13:05:56_

There is now two different versions of jQuery in simpleSAMLphp. It would be 
better to only support the latest version.

_Original issue: http://code.google.com/p/simplesamlphp/issues/detail?id=316_

**Comment by jaimeperez** [comment]
There is only one version of jQuery now. However, it is terribly outdated. We need to update it and make sure everything keeps working.

**Comment by joostd** [comment]
Note that the [currently included version of query](https://github.com/simplesamlphp/simplesamlphp/blob/master/www/resources/jquery-16.js) is vulnerable. See for instance [CVE-2011-4969](https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2011-4969).

I don't know if this means SSP is exploitable, but jquery still seems to be used in several places (e.g. in logout-iframe and modules like statistics, oauth, discopower), and also in external SSP-modules outside this repo.

I'd like to update to a more recent version of jQuery, but the "make sure everything keeps working" is a bit tricky. OTOH, at some point, possibly breaking things may be a better option than being vulnerable.

**Comment by jaimeperez** [comment]
I've updated to the latest jQuery 1.8.x version (with some difficulties, why Mondays need to be this hard?) and that should avoid the security issue. I don't think it was exploitable anyway (at least not by the main code base), since we are not using the vulnerable function `location.hash()`, but better safe than sorry.

At some point we should also upgrade to a modern, 2.x version, but I'm leaving that for the future as I don't want to break (more) things now.
