### ISSUE TITLE
search.filter for LDAP config (was #325)

### ISSUE THREAD

**Issue by sspghost** [simplesamlphp/simplesamlphp#25]
_From [olavmrk@gmail.com](https://code.google.com/u/olavmrk@gmail.com/) on June 21, 2010 08:44:23_

Should be possible to specify a custom filter for LDAP search.

See: http://groups.google.com/group/simplesamlphp/browse_thread/thread/3239315ccfb4aeee

_Original issue: http://code.google.com/p/simplesamlphp/issues/detail?id=325_

**Comment by randomfire** [comment]
mcsj, do you mind sending me the patch you have?  Really need the filter feature.  :)  Thanks

**Comment by thijskh** [comment]
Because of the import I don't think mcsj will be notified of your question. But his/her patch is in the original link above: https://groups.google.com/forum/#!topic/simplesamlphp/MjkxXM-0ru4

If it works for you you may want to consider to make it into a pull request so it can be merged into simpleSAMLphp proper.

**Comment by randomfire** [comment]
Thanks Thijs.  Patched source and everything tested out.  Pull request submitted.

**Comment by tvdijen** [comment]
Is there a reason this one's still open?

**Comment by thijskh** [comment]
Nope, this was merged indeed.
