### ISSUE TITLE
Set-Cookie is set twice with same cookie name

### ISSUE THREAD

**Issue by spaceone** [simplesamlphp/simplesamlphp#256]
The session cookie is sent twice in the HTTP response from any HTTP resource (e.g. /simplesamlphp/saml2/idp/SSOService.php).

store.type == memcache
```
Set-Cookie: SimpleSAMLSessionID=537fc77633fa325ff0688e7ae786d6d9; path=/; httponly
Set-Cookie: SimpleSAMLSessionID=a21b74e576dc9b81c1d4d98ff420d948; path=/; httponly
```
(Set-Cookie header are following immediately after each other).

store.type == phpsession
```
Set-Cookie: PHPSESSID=33c054a80e8ed6cb8b1a390bbf311801; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Set-Cookie: PHPSESSID=f28e5a44e88c7ff3f11b962d8963711f; path=/
```
(there are some headers between those two Set-Cookie headers).

PHP 5.4.36-0.210.201502031505 (cli) (built: Feb  3 2015 21:35:55)
simplesamlphp 1.13.2-1.13.201508111050

**Comment by jaimeperez** [comment]
Hi @spaceone, thanks a lot for your report!

This is a known issue, and actually I would swear I fixed this long time ago. It might be forgotten somewhere in my local git repo, who knows.

In any case, this is a problem related to logging, surprisingly enough. When you land at any SimpleSAMLphp web page that requires a session to be fetched for the current user:

```php
$session = SimpleSAML_Session::getSessionFromRequest();
```

the method will call the internal `getSession()` method without passing a session identifier (as that's unknown). `getSession()` will then ask the session handler to fetch the session identifier from the cookie:

```php
$sessionId = $sh->getCookieSessionId();
```

which of course will return `null` as there's no session cookie. Now, here comes the problem. `getSession()` will continue and ask the session handler to load a session with ID `null`:

```php
 $session = $sh->loadSession($sessionId);
```

`loadSession()` will again try to fetch the session ID from the nonexistent cookie, and since it doesn't make any sense to load a session with ID `null`, it assumes it got some other value and actually *tries* to load it. Then we end up with a failure to either load the session or an assertion failing, which triggers a log message. The `SimpleSAML_Logger` class tries to fetch the current session to obtain a track identifier that it can log, but we have no session at all! So it goes ahead creating a loop, which is broken by a recursion detection mechanism:

```php
        if (self::$trackid === self::$TRACKID_FETCHING) {
            // recursion detected!
            return 'NA';
        }
```

Then, the second call to `getSessionFromRequest()` made by the `SimpleSAML_Logger` class continues, up to the point where a session is created:

```php
self::$instance = new SimpleSAML_Session();
```

That finally triggers the first `Set-Cookie` header. Then we can pull the string all the way back and continue the execution of the first call to `getSessionFromRequest()`, effectively creating a session again because `getSession()` returned null. There you have the second `Set-Cookie` header.

I'm providing all this detail just to give an overview of how complex this is, meaning my fix could just work, or it could break many different things in totally horrible and unexpected ways. So I'd like to ask you to apply this patch and tell me after some testing if it works fine for you:

```patch
diff --git a/lib/SimpleSAML/Session.php b/lib/SimpleSAML/Session.php
index 71326dd..a8ef4b2 100644
--- a/lib/SimpleSAML/Session.php
+++ b/lib/SimpleSAML/Session.php
@@ -215,6 +215,9 @@ class SimpleSAML_Session
         if ($sessionId === null) {
             $checkToken = true;
             $sessionId = $sh->getCookieSessionId();
+            if ($sessionId === null) {
+                return null;
+            }
         } else {
             $checkToken = false;
         }
```

Thanks!

**Comment by jaimeperez** [comment]
The fix works for me and I haven't seen any side effects, so I just merged it.

**Comment by jaimeperez** [comment]
Actually, it didn't work. I must have had some mess in my test instance, because it worked back then, but while I was working on #264 I noticed it doesn't work at all.

Hopefully, a0407d1 should finally solve this issue.

**Comment by spaceone** [comment]
Yes, this works!

**Comment by jaimeperez** [comment]
Great, thanks for confirming!
