### ISSUE TITLE
Security Report: Remote File Include Alert

### ISSUE THREAD

**Issue by dialogik** [simplesamlphp/simplesamlphp#265]
I've been reported about a security issue by our data security officers (who ran some kind of penetration tool on my service) that refers to SimpleSAMLphp. See the attached screenshot for full information.

![RFI suspicion](https://cloud.githubusercontent.com/assets/1260548/10302736/f46d4416-6c0e-11e5-9140-b647ab3cf495.png)

Long story short, that report says that passing a URL to `disco.php`s `return` parameter or to `discoresp.php`s `AuthID` parameter would invoke a [Remote File Inclusion](https://en.wikipedia.org/wiki/File_inclusion_vulnerability). I checked both and what happens is, that in both scenarios the user is *redirected*  to those URLs but no file inclusion takes place whatsoever. I also took a look into the sourcecode which confirmed this assumption.

Now two questions remaining:

1. I am no security expert, so I'd like to ask the community: **Is there a way to inject remote code anyhow by this?** (I'd be very surprised btw as SimpleSAMLphp is a security relevant library and I assume will be well audited.)
1. **Why is it necessary to pass those values via the URI, why can't they be read from the config files?** Wouldn't that be more secure? Because, while I don't see a RFI problem, at least this might be used in order to perform some kind of phishing or clickjacking attack.

**Comment by thijskh** [comment]
Unlikely that code injection is possible. Open redirects are considered a security risk though because it can be used in phishing to obscure the real URL the user is sent to (see OWASP).

My first question would be whether you've set `trusted.url.domains` in config.php? See the bottom of that file (if you copied the template from config-templates/) for the setting and explanation.

**Comment by dialogik** [comment]
No, I haven't yet. Thanks for pointing me there. Have set it to an empty array as recommended in order to disallow all redirections).

But still: Wouldn't it be better to configure any redirection path via configuration instead of passing them via the URI?

**Comment by gfaust-qb** [comment]
Wouldn't it be better to generally set it to secure defaults?

**Comment by jaimeperez** [comment]
Hi!

You are quite right, there's no *remote file inclusion* in there. I wonder how the auditors ended up identifying an open redirect with an RFI...

Now, regarding why the `trusted.url.domains` does not default to an empty array to disallow all redirections except those targeting a known entity or the self host, the reason is backwards compatibility. When we addressed the open redirection issue we left the default to be *unsafe* in order to avoid breaking installations that might rely on redirections to other URLs. Given the time this feature has been in place, and the importance of having this security check, I think next release is adequate to switch this over to secure defaults.

Finally, regarding why there are URLs carrying redirection information, that depends on the case. Most redirections happen to a known, self URL. Others point to URLs given by metadata. Some redirections can be managed in the configuration. But there are cases where the only thing you might have left is an state identifier carrying a URL to restart the authentication process, for instance. So the answer is basically that if we are carrying a URL in a parameter, that's because we actually need it.

**Comment by thijskh** [comment]
I very much agree that the next release should default the setting to `array()` instead of `null`. Anything against changing that in master right now?

**Comment by jaimeperez** [comment]
Not from me!

:+1:

**Comment by dialogik** [comment]
I created a PR, feel free to merge. Thanks for you help and your comments!
