### ISSUE TITLE
Open redirect security issue

### ISSUE THREAD

**Issue by moffe42** [simplesamlphp/simplesamlphp#275]
A normal installation of SimpleSMALphp contains a open redirect issue via the AuthState parameter

```
https://ssp.example.com/module.php/core/loginuserpass.php?AuthState=:http://evil.com
```

The above URL will redirect the user to evil.com

It seems that there is no or little validation of the content fo what is parsed within the AuthState parameter.

**Comment by thijskh** [comment]
To what value have you set `trusted.url.domains`?

See #265.

**Comment by moffe42** [comment]
The trusted.url.domains are set to empty array, but still redirects to evil.com is possible.

**Comment by moffe42** [comment]
I think that the issue is already solved here 2970e12a48cb5fbddc36835a5b41c69671c992a5. 

But there have not been any new tags since november 2014!!!!! That is a long time to go without security updates on a project that is mainly about security.

It would be good practice to tag a new release when security issues is identified and fixed.

**Comment by jaimeperez** [comment]
Hi Jacob!

The issue was solved way before that, in January 2014, 57acd83. That means the issue was already solved in 1.12.0, so the 1.13 branch and the latest stable version 1.13.2 are not vulnerable.

The only problem regarding this issue is the **default** configuration, which we keep backwards-compatible between minor versions. This means you need to properly configure your 1.13.2 installation to solve the issue, for example, setting `trusted.url.domains` to an empty array. Not setting that option or setting it to `null` reverts to the old behaviour, making your installation vulnerable. Shipping software that's secure by default is of course something we are committed to, but at the same time the security of a particular installation is the responsibility of the users themselves.

With this particular issue we have decided to make our exception to our backwards-compatibility policy, so 1.14.0 will **not** ship with vulnerable configuration templates. We haven't released any new version solving the default behaviour yet for three reasons:

* We don't want to break existing configurations in point releases.
* We are short on resources to work on SimpleSAMLphp (contributions welcome, as always).
* And finally, because this issue doesn't pose a risk on the SimpleSAMLphp installation itself, but just opens the possibility for phishing attacks.

Since this is not a critical vulnerability and it can be solved with proper configuration, we decided not to give priority to this.

**Comment by moffe42** [comment]
The issue is not fixed.

In a test setup: 'trusted.url.domains' => array('cbx.xyz'),

But still the following

https://test-login.cbx.xyz/module.php/core/loginuserpass.php?AuthState=:http://evil.com

Will redirect to http://evil.com

**Comment by thijskh** [comment]
When I try this in my installation of ssp master:
```
Caused by: SimpleSAML_Error_Exception: URL not allowed: http://evil.com
```

Just to confirm, are you running latest master or something else?

**Comment by moffe42** [comment]
I am running latest tag 1.13.2.

**Comment by thijskh** [comment]
I cannot reproduce it with that tag either I'm afraid.

I also tried the following:
* Download simplesamlphp-1.13.2.tar.gz and unpack.
* Change only baseurlpath to make it work.
* Going to &lt;mybaseurl&gt;`module.php/core/loginuserpass.php?AuthState=:http://evil.com` indeed results in the redirect;
* Changed `trusted.url.domains` in `config/config.php` from `null` to `array()`;
* Going to same URL now fails with "URL not allowed" exception;
* Changes `trusted.url.domains` in `config/config.php` from `array()` to `array('cbx.xyz')`;
* Going to same URL still fails with "URL not allowed" exception.

What could be different about your installation that you're not seeing this behaviour?

**Comment by jaimeperez** [comment]
No, it won't redirect, neither in master nor in 1.13.2. It will throw an exception and show an error. I double checked when I closed the issue, and I have double checked again right now, both in master and 1.13.2. It works as expected.

There must be some kind of problem on your side. How did you install SSP? Where do you have the `trusted.url.domains` configuration option? Are you sure the `config.php` file where you should have this option is the one you are using?

**Comment by moffe42** [comment]
It seems it is because of nested exceptions. I get an error, that calls my templete, that calls my getLanguage function, that uses the AuthState. The authstate is not found and a redirect is performed. Exactly why is happening i do not know...

**Comment by moffe42** [comment]
finally found the root cause of this issue. 

The issue is that use the AuthState in my getLanguage function which looks like this:

```
public static function getLanguage()
{
    try {
        if (!isset($_REQUEST['AuthState'])) {
            throw new Exception('AuthState is missing, not good :-(');
        }
        $state = SimpleSAML_Auth_State::loadState($_REQUEST['AuthState'], sspmod_core_Auth_UserPassBase::STAGEID);
    } catch (Exception $e) {
        return 'en';
    }
    return sspmod_cbx_LanguageSelector::getLanguageForService($state['service']);
}
````

The ```loadState``` is called with AuthState = ':http://evil.com', this leads to a redirect in line 228 in SimpleSAML_Auth_State

```
SimpleSAML_Utilities::redirectTrustedURL($sid['url']);
```

For some reason SSP just redirect to what ever is placed in the AuthState blindly. If I replace this redirect with throwing an Exception everything works as expected.

I can use the $allowMissing optional parameter to handle the exception my self, but I wouldhave expected this method to throw an exception on a missing AuthState. 
I do not understand why this behaviour was selected to work this way, but at least I would have run this through redirectUntrustedURL instead.

Thanks for all the feedback. Keep up the good work on SSP.

**Comment by jaimeperez** [comment]
That kind of makes sense. The `AuthState` is a mix of an identifier of the current state, plus a URL that you can use in case everything goes wrong and you need to restart the process. That's the URL you are redirecting to, ignoring the configuration.

Now, regarding the reason for the redirect actually happening, it's probably in your code. If you have your own `getLanguage()` (I'm curious about why you need that, but anyway...), it might be that you are performing a redirection on your own. The code that checks for allowed domains does not get executed magically, you need to tell SimpleSAMLphp to explicitly do that, since it wouldn't make sense to perform such a check even with URLs that cannot be set by an attacker or be malicious in any way. If you are calling `SimpleSAML_Utilities::redirect()` directly, that's the reason for the behaviour you are experiencing. That method was deprecated in 1.12.0, and you shouldn't be using it, but the more recent `redirectUntrustedURL()`, which will validate the URL before performing the redirection.

**Comment by jaimeperez** [comment]
Ops, didn't see you additional response before commenting!

That's something we changed not far ago. The library was assuming that you would check the URL in the AuthState in case it was set by a third party. We fixed this to assume all URLs in the AuthState variable to be untrusted. This has the side effect of checking URLs that we don't need to check at some point, but on the other hand avoids problems like the one you are experiencing.

**Comment by moffe42** [comment]
I am doing my own getLanguage function, using the AuthState, because I need to choose a specific language based on the service using out SSO setup. We have one domain pr. language, so redirecting from a .de domain, means that we must show german on SSP, even if the browser says English.

**Comment by jaimeperez** [comment]
That's interesting, thanks for satisfying my curiosity! :smile:
