### ISSUE TITLE
SLO redirection to wrong service provider

### ISSUE THREAD

**Issue by spaceone** [simplesamlphp/simplesamlphp#280]
I am experiencing a redirection to the wrong service provider when doing a global logout in my SLO-service.
My setup consists of SP-A, SP-B and the simplesamlphp IDP:
1. I am accessing SP-A which redirects with AuthN-request to the IDP where i successfully authenticate/login
2. Now I am accessing SP-B which detects (via isPassive) that I am already logged in at the IDP and redirects me back to the SP-B.
3. Now I am logging out of SP-B which redirects me to simplesamlphp's resumelogout.php which redirects with the LogoutRequest to SP-A instead of back to SP-B
4. SP-A now cannot use the LogoutRequest as the "Destination" is unknown

**Comment by jaimeperez** [comment]
Hi @spaceone!

That's not an issue, that's the way Single Logout works. In your case, you have two service providers logged in. When one of them triggers SLO, the IdP needs to propagate logout to the other. That's why when you send a LogoutRequest from SP-B, what you see next is another LogoutRequest from the IdP to SP-A, because that one needs to logout too. The Destination in this second LogoutRequest must be, of course, SP-A. If that's not the case, I would need more information in order to assess what's happening (e.g. logs for every instance, traces captured with SAML tracer, etc).

**Comment by spaceone** [comment]
Ah okay! Then it's just a bug in my SP implementation. Thanks!

**Comment by spaceone** [comment]
@jaimeperez Can you explain what I should do as a service provider if I receive a <samlp:LogoutRequest> ? How can I know that I have to redirect the user back to SP-A (assuming I am SP-B)?

**Comment by jaimeperez** [comment]
Hi!

In general you don't need to do anything. When SimpleSAMLphp receives a SAML LogoutRequest on its SLO endpoint, it will log the user out from his/her session, and reply to the IdP with a SAML LogoutResponse.

It is therefore the IdP the only one that keeps track of the different SPs, and the one that redirects to every one of them to trigger logout. As an SP, you don't need to know (nor should know) what other SPs the user is logged into.

**Comment by spaceone** [comment]
Ah thank you. I am now redirecting back to the IDP with a <samlp:LogoutResponse>. Everything seems working now :)
