### ISSUE TITLE
syslog contains "Passive authentication not supported" tracebacks

### ISSUE THREAD

**Issue by spaceone** [simplesamlphp/simplesamlphp#281]
The syslog get spammed with tracebacks for each unauthorized SAML request using isPassive:

```
Caused by: SimpleSAML_Error_NoPassive: Passive authentication not supported.
Backtrace:
3 /usr/share/simplesamlphp/lib/SimpleSAML/IdP.php:325 (SimpleSAML_IdP::authenticate)
2 /usr/share/simplesamlphp/lib/SimpleSAML/IdP.php:390 (SimpleSAML_IdP::handleAuthenticationRequest)
1 /usr/share/simplesamlphp/modules/saml/lib/IdP/SAML2.php:389 (sspmod_saml_IdP_SAML2::receiveAuthnRequest)
0 /usr/share/simplesamlphp/www/saml2/idp/SSOService.php:18 (N/A)
Returning error to sp: 'https://master30.saml.dev/univention-management-console/saml/metadata'
sspmod_saml_Error: Responder/NoPassive: Passive authentication not supported.
```

Of course is passive authentication not supported but this doesn't have to be a traceback which occurs in syslog. afaik isPassive exists to check if the session exists/is valid.

**Comment by jaimeperez** [comment]
Hi @spaceone! Thanks for bringing this up to our attention!

While you can intuitively think there's no point in displaying the backtrace for this kind of exceptions, there's actually a reason. As you say, these are raised when a service provider asks for passive authentication but there's no valid session for the user. However, this exception is also raised at other different points, like *authproc* filters that need to perform some interaction with the user (ask for consent, for example) while the current SAML transaction was requested to be passive.

It then makes sense to know where this error was raised, as that allows you to identify potentially different problems.

In any case, it's true that there's no point on logging backtraces like this if we are not going to debug anything, and we just want to keep record of errors. Therefore, I've changed a bit the `SimpleSAML_Error_Exception` class so that the backtraces are logged with *debug* level, and only in case the `debug` configuration option is enabled.

Hope this helps.
