### ISSUE TITLE
Postrgres duplicate key violation error

### ISSUE THREAD

**Issue by zvonem** [simplesamlphp/simplesamlphp#285]
Hi, we have just switched store type from SQLite to Postgres and we started to recieve key violation error on insert into kvstore table:
ERROR:  duplicate key value violates unique constraint "simplesamlphp_kvstore_pkey"

Even if no users have reported that they failed to login, I don't like getting errors, so can you give us some hints about this? We use simplesamlphp 1.9.2.

Thanks in advance,
Zvonko

**Comment by jaimeperez** [comment]
Hi @zvonem!

Since this is an issue tracker and not a support forum, I believe you could get more feedback in the [mailing list](https://groups.google.com/forum/#!forum/simplesamlphp).

In any case, my first recommendation would be to update to the latest stable version (at this moment, 1.13.2). 1.9.2 is three years and a half old now, and there's been quite a few bug and security fixes since then.
