### ISSUE TITLE
Ability to enable more robust logging in Session.php

### ISSUE THREAD

**Issue by luvablemarmot** [simplesamlphp/simplesamlphp#329]
if ($_COOKIE[$authTokenCookieName] !== $session->authToken) {
                    SimpleSAML_Logger::warning('Invalid AuthToken cookie.');
                    return null;

The logger warning above, its possible to enable more verbose logging to what the state of the AuthToken is that would be helpful. We experienced an issue where we were getting Invalid AuthToken and the only way to fix was restarting memcached. Since the session state is encrypted we didn't really have a good way to troubleshoot what caused the invalid state.

**Comment by jaimeperez** [comment]
Hi @luvablemarmot!

I'm not really sure what you need here. The auth token is not encrypted at all, it's just a random identifier we put into a cookie to avoid [session fixation attacks](https://www.owasp.org/index.php/Session_fixation). Its value must match a value we store in the session, and this cookie is only set when the user gets authenticated.

If you ever get an "Invalid AuthnToken cookie", that means the value in the cookie does not match with the value stored in the session. It's the kind of error legitimate users should rarely see, at least provided they are not doing anything weird or their browser is not completely messed up.

If you are using memcache and that solved the issue, that's because the storage is flushed when the server is restarted, and therefore all sessions are gone. Then the user will need to login again, creating new session and auth token cookies, fixing the problem. This doesn't mean the problem was with memcache, and there's nothing you can really do to fix it (as a matter of fact you shouldn't restart memcache, as that will destroy the session for **all your users**).

So there's really not much more information to provide at that point, and even if we do, there's nothing you can do about it. The only solution is that the user cleans his/her cookies and logs in again.

**Comment by jaimeperez** [comment]
No feedback in a couple of weeks, and not much that we can do here, so closing the issue.
