### ISSUE TITLE
Fail to detect HTTPS when application is behind an Amazon AWS Elastic Load Balancer 

### ISSUE THREAD

**Issue by zmilan** [simplesamlphp/simplesamlphp#343]
Hi,

Thanks for this great tool. It works very good, but I found issue with detecting HTTPS when application is behind an Amazon AWS Elastic Load Balancer. Issue is because in that case we don't have $_SERVER['HTTPS'] set, but good thing is that we have other that can be used:
$_SERVER['HTTP_X_FORWARDED_PORT'] => 443
$_SERVER['[HTTP_X_FORWARDED_PROTO'] => https

For our need I add fix, but it will be good if this can be solved on project level. Here is my fix:

[SimpleSAML\Utils\HTTP::getServerHTTPS() function](https://github.com/simplesamlphp/simplesamlphp/blob/master/lib/SimpleSAML/Utils/HTTP.php#L76) I modify it to looks like this:
`
// add support for servers on aws behind load balancer
**if(isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') {
            $_SERVER['HTTPS']='on';
            return true;
}**

if (!array_key_exists('HTTPS', $_SERVER)) {
            // not an https-request
            return false;
}

if ($_SERVER['HTTPS'] === 'off') {
            // IIS with HTTPS off
            return false;
}
        
// otherwise, HTTPS will be a non-empty string
return $_SERVER['HTTPS'] !== '';
`

[SimpleSAML\Utils\HTTP::getServerPort() function](https://github.com/simplesamlphp/simplesamlphp/blob/master/lib/SimpleSAML/Utils/HTTP.php#L101) I modify it to looks like this:
`
$port = (isset($_SERVER['SERVER_PORT'])) ? $_SERVER['SERVER_PORT'] : '80';

if (self::getServerHTTPS()) {
     // modified first part of this case to support aws servers under loadbalancer
     if (**$port !== '80' &&**$port !== '443') {
          return ':'.$port;
     }
} else {
      if ($port !== '80') {
          return ':'.$port;
      }
}

return '';
`

Thanks again

**Comment by jaimeperez** [comment]
Hi @zmilan!

This has been discussed many times before, here and in the mailing list. That's not an issue with SimpleSAMLphp, but with your environment. The `X-Forwarded-*` headers should not be trusted, as they can contain values set by the end users. Therefore, the proper way to circumvent this issue is to set the `baseurlpath` configuration option appropriately, including not only the host (and port if necessary), but also the protocol (`https://` in this case).

**Comment by zmilan** [comment]
Hi @jaimeperez ,

Thanks for explaining this. I'm new to simplesamlphp and wasn't know that it was discussed (actually i was search trough issues and pull request but I wasn't found anything).
In my specific case `baseurlpath` is not option, since we change parameters dynamic, but this my fix will do job for now.

**Comment by jaimeperez** [comment]
Hi again!

I guess the problem is that github searches only for *open issues* by default, but if you remove the `is:open` from the search, you can get [more results](https://github.com/simplesamlphp/simplesamlphp/issues?utf8=%E2%9C%93&q=is%3Aissue+x-forwarded).

In any case, back to the original matter: remember that SimpleSAMLphp's configuration is written in PHP. Therefore, you don't have to configure it statically. If you really need to change part of the configuration depending on the request, you can do that by writing the appropriate code in the configuration file itself.

So if you have for instance a load balancer in front of you, sanitizing the `X-Forwarded-Proto` header and setting it for you, it can then be read and used in the configuration file in order to get dynamic configuration.

**Comment by zmilan** [comment]
Hi @jaimeperez , thanks for your suggestion. Yesterday I was just trying to solve issue, but yes this way I can escape to change original files. Our configuration files are already environment specific, so with little more code it can do same job, like my fix. 
Thanks again.
