### ISSUE TITLE
Conflict between session.cookie.secure and metarefresh

### ISSUE THREAD

**Issue by gollmann** [simplesamlphp/simplesamlphp#353]
Given the following excerpt in config/config.php

    'baseurlpath' => 'simplesaml/',
    'session.cookie.secure' => true, /* server is https-only */

metarefresh fails with:

> PHP Fatal error:  Uncaught exception 'SimpleSAML_Error_Exception' with message 'Session start with secure cookie not allowed on http.' in /var/simplesamlphp/lib/SimpleSAML/SessionHandlerPHP.php:78
> Stack trace:
> #0 /var/simplesamlphp/lib/SimpleSAML/Session.php(154): SimpleSAML_SessionHandlerPHP->newSessionId()
> #1 /var/simplesamlphp/lib/SimpleSAML/Session.php(328): SimpleSAML_Session->__construct(true)
> #2 /var/simplesamlphp/modules/metarefresh/bin/metarefresh.php(16): SimpleSAML_Session::useTransientSession()
> #3 {main}
> 

Should transient sessions even care about the _session.cookie.secure_ parameter ?

Kind regards, Georg

**Comment by jaimeperez** [comment]
Hi @gollmann.

I don't see a way this can happen unless you are actually not using HTTPS. I.e. a load balancer is performing TLS encapsulation, and your SSP is behind it, using plain HTTP. In that case, you should fix the value of `baseurlpath` to contain the full, canonical URL of your installation, using HTTPS.

**Comment by thijskh** [comment]
I think Georg is running metarefresh from something like cron, and there should be no concepts of load balancers etc, right?

**Comment by gollmann** [comment]
To make the problem clear: this is **not** about clients accessing the IdP but a cron job on the IdP is fetching metadata from the federation.
While changing `baseurlpath` would remove the error this spillover in the configuration from one area (metarefresh) into another (authentication) is not desirable.

I suspect the problem is with the function `newSessionId()` in
`lib/SimpleSAML/SessionHandlerPHP.php` which assumes it is called in the context of a HTTP(S) request which is not the case in the metarefresh scenario. I further conjecture that both tests in this function are at best meaningless in the context of **transient sessions** since those session IDs are not saved anyway. So I believe that `newSessionId()` should have a parameter that specifies whether the session is transient or not. Just like `__construct($transient = false)` in `lib/SimpleSAML/Session.php`

**Comment by jaimeperez** [comment]
Hi! Sorry Georg, I totally missed the last part of the trace.

The problem here, IMHO, is not that transient sessions shouldn't care about cookie parameters or other checks, the problem is that command line utilities shouldn't be using sessions at all. Actually, the exception you are getting is caused by `modules/metarefresh/bin/metarefresh.php` calling `SimpleSAML_Session::useTransientSession()`, and thus creating one even though it won't use it at all.

Even transient sessions should care about security properties, in my opinion. So instead of circumventing those checks, I would stop using sessions, or at least use a different check in `SimpleSAML_Session::__construct()`, making sure no session gets even created if we are running from the command line, as that wouldn't make any sense.

I've made a patch that should solve the issue. Could you please try it and tell me if everything works as expected? Thanks!

```patch
diff --git a/lib/SimpleSAML/Session.php b/lib/SimpleSAML/Session.php
index 5924141..67796da 100644
--- a/lib/SimpleSAML/Session.php
+++ b/lib/SimpleSAML/Session.php
@@ -139,6 +139,13 @@ class SimpleSAML_Session
     {
         $this->authData = array();

+        if (php_sapi_name() === 'cli') {
+            $this->trackid = 'CLI'.bin2hex(openssl_random_pseudo_bytes(4));
+            SimpleSAML\Logger::setTrackId($this->trackid);
+            $this->transient = true;
+            return;
+        }
+
         if ($transient) { // transient session
             $sh = SimpleSAML_SessionHandler::getSessionHandler();
             $this->trackid = 'TR'.bin2hex(openssl_random_pseudo_bytes(4));
```

**Comment by gollmann** [comment]
I had to change `SimpleSAML\Logger` to `SimpleSAML_Logger` to make it work. Otherwise preliminary tests look fine. Thanks!

**Comment by jaimeperez** [comment]
Thanks for the feedback! The fix is now in master.

**Comment by jorgecha** [comment]
Hello! I present the following error:
Uncaught exception 'SimpleSAML_Error_Exception' with message 'Setting secure cookie on plain HTTP is not allowed.' in /dcantv/appl/simplesamlphp/lib/SimpleSAML/Session.php:293 Stack trace: # 0 /dcantv/appl/simplesamlphp/lib/SimpleSAML/Auth/Simple.php(54): SimpleSAML_Session :: getSessionFromRequest () # 1 /dcantv/appl/svn_rau/trunk/templates/logout.php(8): SimpleSAML_Auth_Simple-> isAuthenticated () # 2 {main} thrown in /dcantv/appl/simplesamlphp/lib/SimpleSAML/Session.php on line 293

even adding the patch and changing SimpleSAML \ Loggera to SimpleSAML_Logger


Kind regards!!

**Comment by tvdijen** [comment]
Hi @jorgecha! Please upgrade to a less ancient version and refer to our mailing list if you still need support after that

**Comment by shailesh-mfs** [comment]
> Hello! I present the following error:
> Uncaught exception 'SimpleSAML_Error_Exception' with message 'Setting secure cookie on plain HTTP is not allowed.' in /dcantv/appl/simplesamlphp/lib/SimpleSAML/Session.php:293 Stack trace: # 0 /dcantv/appl/simplesamlphp/lib/SimpleSAML/Auth/Simple.php(54): SimpleSAML_Session :: getSessionFromRequest () # 1 /dcantv/appl/svn_rau/trunk/templates/logout.php(8): SimpleSAML_Auth_Simple-> isAuthenticated () # 2 {main} thrown in /dcantv/appl/simplesamlphp/lib/SimpleSAML/Session.php on line 293
> 
> even adding the patch and changing SimpleSAML \ Loggera to SimpleSAML_Logger
> 
> Kind regards!!

Hi @jorgecha ,
Did you find solution for your problem. I am also facing the same issue ? My application  is running on http behind load balancer that is on https so When I try to authenticate with IDP it give me relatState .i.e http://abc.com instead of https://abc.com. However my application is running on https://abc.com
