### ISSUE TITLE
Unable able to use Login page on iPhone devices

### ISSUE THREAD

**Issue by stevenao** [simplesamlphp/simplesamlphp#359]
The login button doesn't show up on iphone. The enter button on the keyboard wouldn't do a submit unlike the button on android devices. Therefore, there is no way the user can perform login.

**Comment by jaimeperez** [comment]
Hi @stevenao!

Thanks for reporting this. There was indeed a problem with the CSS and the login template that was preventing the button to be shown. I've hopefully fixed that issue and reorganized a bit the form so that it is displayed vertically, instead of horizontally. This should enhance the view in mobile devices.

Let me know if you see any other issue.
