### ISSUE TITLE
Timezone warning.

### ISSUE THREAD

**Issue by mitchit1** [simplesamlphp/simplesamlphp#374]
New install
Apache/2.4.6 (CentOS) PHP/5.4.16
simplesamlphp-1.14.3

Linux 3.10.0-327.13.1.el7.x86_64 #1 SMP Thu Mar 31 16:04:38 UTC 2016 x86_64
No matter what the setting is, this warning is received. 

'timezone' => 'America/New_York',

Warning: main(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /mnt/simplesaml/config/config.php on line 124

**Comment by jaimeperez** [comment]
Hi,

I just verified with 1.14.3, and can't see this logged anywhere. Where do you get this warning? Apache error log? SimpleSAMLphp log?

Besides, getting the warning should be impossible since it is triggered by `date_default_timezone_get()`, and when we call it, we set the error handler to a function that doesn't log anything, just for this call. If that wasn't enough, when you specify a timezone in the configuration SimpleSAMLphp will set it with `date_default_timezone_set()` and forget about it, so the `date_default_timezone_get()` function that generates this warning is not even called.

I don't know what could be the cause for this warning or the problem you are having with the logger class, but it must clearly be a local installation issue.
