### ISSUE TITLE
Test Auth. Sources incorrect logout URL when on reverse proxy

### ISSUE THREAD

**Issue by disccomp** [simplesamlphp/simplesamlphp#396]
Looks like HTTP::getSelfURLNoQuery() is generating the URL incorrectly. BaseURLPath is correct (https://example.com/SSO/) and other admin pages work correctly.

Generated: https://example.com/simplesaml//module.php/core/authenticate.php?as=authsource_name&logout
Expected: https://example.com/SSO/module.php/core/authenticate.php?as=authsource_name&logout

**Comment by disccomp** [comment]
(Called in modules/core/www/authenticate.php, second to last line of file.)

**Comment by jaimeperez** [comment]
Hi @disccomp!

What version of SimpleSAMLphp are you using? What's the value of the `baseurlpath` configuration option in your `config/config.php`?

**Comment by jaimeperez** [comment]
Hi again,

I've just verified it with a very simple script in both master and latest stable version (1.14.3), and it works fine as expected. Given that the `/simplesaml/` part is not hardcoded in any way, I would assume there's an issue with your web server configuration, which might be the one redirecting there.

In any case, it's impossible to replicate with more information, so I'm closing the issue. Please comment again if you still experience trouble and add more information so that we can try to replicate the problem.

**Comment by jaimeperez** [comment]
Hi again!

I've just noticed a possible source for your trouble. There is one case where you could get that `/simplesaml/` added to the URL, which is when the `baseurlpath` option is not given in the configuration. I would check that to make sure it is correctly set to whatever you need and there's no typos in the name of the option (remember it is written entirely in lowercase).

**Comment by disccomp** [comment]
Sorry for the slow response, I wasn't checking my email over the holiday break.

It looks like $_SERVER["SCRIPT_NAME"] is the source of the /simplesaml/ part of the URL.

**Comment by jaimeperez** [comment]
Hi! No problem at all!

If this extra `/simplesaml/` is coming from `$_SERVER`, then there must be some misconfiguration in your web server too. Take a look at your virtual host definition.

**Comment by disccomp** [comment]
It is correct for _that_ server. 
Internal server: /simplesaml/
Proxy server: /SSO/
The problem is that external URLs should be generated against baseurlpath, not the internal server's script path.

**Comment by jaimeperez** [comment]
Hi again!

You should have mentioned that you are running SimpleSAMLphp behind a reverse proxy and doing URL translation from the beginning. That's the reason for this issue, but of course, there's no way for us to guess that without such important information.

The problem, in this case, is that you are abusing `baseurlpath` for something it was not intended for. If you are doing URL mapping in your proxy (which you clearly are, since your proxy receives requests in a URL and you are sending requests to SimpleSAMLphp with a different URL), you should also be doing URL rewriting in the responses. In general, applications don't support this kind of setup, so you would need to do that anyway. The fact that SimpleSAMLphp provides `baseurlpath` as a way to customize the base URL does not mean this particular scenario will work out of the box.

Bear in mind also that those URLs are **not** external. An external URL would be a link to google.com. A link to some other script inside SimpleSAMLphp is definitely an internal URL and it should be built according to the current status as presented by the server.

In fact, the issue here is much larger here than just `getSelfURLNoQuery()`, affecting all `getSelfURL*()` methods in `SimpleSAML\Utils\HTTP`, and producing *"incorrect"* links all over the place in the web interface (basically, wherever we need to build an internal URL pointing to the current one and changing the parameters). Fixing this would take much more work, and means breaking the contract for all those methods, which is why I'm hesitant on whether we should change the behavior or not. Currently, the documentation for `getSelfURLNoQuery()` says:

```php
    /**
     * Retrieve the current URL without the query parameters.
     *
     * @return string The current URL, not including query parameters.
     *
     * @author Andreas Solberg, UNINETT AS <andreas.solberg@uninett.no>
     */
    public static function getSelfURLNoQuery()
```

The documentation for other similar methods is pretty much equivalent. Changing the way the methods behave is complicated because all of a sudden we need to start comparing file paths, URLs, and configuration options, and it would break the contract for those methods, IMHO. So if we are going to do this, we would need to document it very well and make sure backwards-compatibility is guaranteed, at least until 2.0.

I'll get back to this in the future with a decision.

**Comment by jaimeperez** [comment]
I just noticed the subject line, where you were explicitly talking about a reverse proxy. Still, no indication of URL translation in your message. Sorry about that in any case.

Anyway, the rest of my last message stays valid. "Fixing" this would involve a non-negligible amount of time and could break things, so I need to take a look at it deeply in order to make a decision.

**Comment by disccomp** [comment]
I think that is a wise to not change the contract of those methods, but I
would argue that you wouldn't have to; you just stop using them in favor of
ones that generate urls relative to baseurlpath.

I've only noticed a few places where the urls were broken, most of the
admin pages worked flawlessly, as do all the urls in the metadata itself.

**Comment by jaimeperez** [comment]
Hi @disccomp!

After reviewing the affected code, it looks like it is reasonably safe to change the contract of both `getSelfURL()` and `getSelfURLNoQuery()`. They were somehow broken anyway, since they were still trying to use `baseurlpath`, but ignoring the path component of the URL. Now setups like your would helpfully work fine.

Please tell me if you notice anything wrong.
