### ISSUE TITLE
Protocol override option when SSL is terminated upstream of SimpleSamlPHP

### ISSUE THREAD

**Issue by prolifico** [simplesamlphp/simplesamlphp#420]
SSP doesn't seem to be able to accommodate an environment where SSL is being handled by a device upstream of SSP. In this environment, clients access our SP links using HTTPS, but traffic from the SSL endpoint to our SSP server is using HTTP. 

In this scenario, when SSP detects the protocol being used, it detects HTTP. However, this causes RelayState, AssertionConsumerService, and any other URLs to be generated using HTTP instead of HTTPS, which causes the authentication to fail.

I know this can be overridden by using the full https:// URL in baseurlpath, but this is not suitable because we use multiple vhosts with this SSP installation, so we must use the relative path for baseurlpath.

In the current 1.14.6 version, HTTPS can be forced by manually overriding the $protocol variable in /lib/SimpleSAML/Utils/HTTP.php. This must be done within the getSelfURL() function as well as the getBaseURL() function (in previous versions, it could be overridden in different locations).

I would like to propose an option to be able to override the protocol either globally or for each authentication source in authsources.php.

**Comment by jaimeperez** [comment]
Hi @prolifico!

`baseurlpath` is the way to go for this. Since the configuration in SimpleSAMLphp is pure PHP code, having the same installation for different virtual hosts is not an issue, as you can always use your environment to set `baseurlpath`:

```php
    `baseurlpath` => `https://`.$_SERVER['SERVER_NAME`].'/simplesaml',
```

If you have different requirements depending on the virtual host, you can always add code before starting the definition of the `$config` array, using for example a `switch` statement to set a variable with the right `baseurlpath` depending on the current environment.

The code implementing the logic around URL guessing and building is quite complex, and trying to fulfill everyone's needs made it already prone to errors and caused a lot of trouble as you may have seen. Therefore, I'm hesitant to add more complexity to it, specially if the features to be added could be easily implemented via configuration.

**Comment by prolifico** [comment]
Your solution seems to work (although I'm confused by your use of backticks vs single quotes) but only seems to satisfy the getBaseURL function. This function accurately pulls the "https://" from the baseurlpath and therefore predicts the AssertionConsumerServiceURL correctly, but when determining the "RelayState" it seems that getSelfURL is being used. getSelfURL does not seem to consider the protocol that is used in baseurlpath (it uses getServerHTTPS instead), so the RelayState is being predicted as http:// instead of https://.

**Comment by jaimeperez** [comment]
Hi again!

I don't know what happened to end up in that mix of backticks and single quotes. I've fixed it anyway. Regarding `getSelfURL()`, [it **does** consider the protocol specified in `baseurlpath`](https://github.com/simplesamlphp/simplesamlphp/blob/simplesamlphp-1.14/lib/SimpleSAML/Utils/HTTP.php#L660), provided the current script being executed is part of SimpleSAMLphp. `getServerHTTPS()` is **only** used when `$current_path` (the absolute, canonical path to the script in execution) is equal to `$rel_path` (the computed relative path to the script in execution, from the base directory of SimpleSAMLphp's installation). If both are equal, that means the current script is **outside** SimpleSAMLphp, and therefore, we cannot assume `baseurlpath` is correct for the current script, so we just use the environment.

**Comment by jaimeperez** [comment]
By the way! If you need to change the `RelayState` in the SAML request so that you get back to an HTTPS URL instead of plain HTTP, you can either do that [by configuration](https://simplesamlphp.org/docs/stable/saml:sp), setting the `RelayState` configuration option in the SP configuration, or [programmatically](https://simplesamlphp.org/docs/stable/simplesamlphp-sp-api#section_4_1), passing an array to `requireAuth()` with the key `ReturnTo` holding the right URL you need to be returned to.

**Comment by rakicivan** [comment]
![image](https://cloud.githubusercontent.com/assets/17475034/25785500/493434b4-3382-11e7-9ae5-c75dbe62a438.png)
I have 2 problems.

1. problem is when SSL is active on domain nobody can't register..
2. problem is when random people can't register on the site... -> RANDOM.  Someone can, and some do not. The problem that arises is the same problem as shown in the image, with the continuation of httP: // because there is no active SSL certificate here.

HELP? :)
