### ISSUE TITLE
SimpleSAMLphp does not redirect properly back to authmemcookie (broken as of 1.14.5)

### ISSUE THREAD

**Issue by mediabounds** [simplesamlphp/simplesamlphp#446]
We're using authmemcookie and when we updated to 1.14.6 this morning, it stopped redirecting properly after a successful login. It tried to redirect to https://example.com/simplesaml/authmemcookie.phphp.

This seems to be caused by the changes to HTTP::getSelfURL() in #418. 

Authmemcookie.php uses getSelfURL() to redirect back to itself after successful authentication

    // redirect the user back to this page to signal that the login is completed
    \SimpleSAML\Utils\HTTP::redirectTrustedURL(\SimpleSAML\Utils\HTTP::getSelfURL());

However, `getSelfURL` seems to assume that `$_SERVER['SCRIPT_FILENAME']` and `$_SERVER['REQUEST_URI']` are going to contain a reference to the same file. However, when using authmemcookie, `$_SERVER['REQUEST_URI']` is going to be set to the originally requested resource. The string manipulation it performs is what resulted in the request being redirected to https://example.com/simplesaml/authmemcookie.phphp.

Downgrading to 1.14.4 resolves the issue.

**Comment by jaimeperez** [comment]
Hi @mediabounds.

What's the value in your `baseurlpath` configuration option? Are you behind a reverse proxy?

In 1.14.6, when the contents of `$_SERVER['SCRIPT_FILENAME']` do **not** point to the same resource as `$_SERVER['REQUEST_URI']`, we give up and assume we are called from a third-party script, using the execution environment to build the URL. If the URL is getting rewritten as you are showing, that must be because both point to the same resource, and therefore, we attempt to rewrite the current URL using `baseurlpath` as the canonical URL for SSP.

In any case, impossible to debug without more details, I'm afraid...

**Comment by jaimeperez** [comment]
Resolved in SimpleSAMLphp 1.14.8.

**Comment by mediabounds** [comment]
Thanks, @jaimeperez. Sorry for the delay (was out of town). We will try updating to 1.14.8 within the week.
