### ISSUE TITLE
Document required PHP modules

### ISSUE THREAD

**Issue by jornane** [simplesamlphp/simplesamlphp#459]
I've installed SimpleSAMLphp on a FreeBSD 10 host with PHP 7 and lighttpd. It works great, but I've had some trouble getting it to work due to lack of documentation about which PHP modules are required.

The following command fixed the welcome page:

	pkg install php70-json php70-openssl php70-session php70-xmlrpc

It might be a good idea to document these modules somewhere, for example when downloading the tgz file. It might also be a good idea to do some sanity checks in **modules/core/www/frontpage_welcome.php** in order to help the user find out what's wrong in case some modules are missing.

**Comment by jaimeperez** [comment]
Hi Jørn!

I'm surprised about `php70-xmlrpc`, I don't think we use it in any place. Does the welcome page break with that missing? I don't have it installed in any of my VMs and never noticed any issue.

Regarding `php70-session`, that one is only needed if you are using the PHP session handler, which is not the only option. I'm a bit surprised that this was extracted to an independent package in FreeBSD, TBH.

`php70-json` is needed for translations, though it will stop being needed for that in the (hopefully not so distant) future. Statistics and other modules also use this, so it's still a good idea to check it.

Regarding sanity checks, this kind of stuff is checked in `module.php/core/frontpage_config.php` (you need to be logged in). Did you check that? _OpenSSL_ is listed there, for instance.

**Comment by jornane** [comment]
I'll recheck the `php70-xmlrpc`-requirement.

Without `php70-session` and `php70-openssl`, the webUI doesn't work at all so `module.php/core/frontpage_config.php` won't work.

This is because the webUI wants to initialize a session, and uses an openssl function to generate a random identifier in `lib/SimpleSAML/Session{,HandlerPHP,HandlerCookie.php}.php`

**Comment by jaimeperez** [comment]
Yes, that makes full sense. Not so sure about _session_, though. The set of `session_*()` functions aren't used at all if you are not using PHP sessions (you can also use _memcache_ or a database. I believe if you change the session backend, it won't break at all if you don't have `php70-session` installed.

**Comment by jaimeperez** [comment]
I've just added some more checks in 561f76df423a540d94a33179ed804872f7d6e8be 😄

**Comment by jornane** [comment]
`php70-xmlrpc` is indeed not required. However, `php70-dom` and `php70-simplexml` are. The **Configuration** tab in de webUI doesn't complain about them missing unless you log in as admin. Which by itself requires `php70-session` and `php70-openssl`.

**Comment by jaimeperez** [comment]
The _DOM_ and _SimpleXML_ extensions are already marked as a requirement. However, I don't think _SimpleXML_ is really required, as I don't see it used except for the _InfoCard_ module. I'd rather put it as a requirement there.

_OpenSSL_ is always required, and it's marked as such in the [documentation](https://simplesamlphp.org/docs/stable/simplesamlphp-install#section_3). The _Session_ extension, again, is not required unless you use PHP sessions. I can add a note to the documentation though (and review the requirements specified there also, since I don't think we need _pcre_ or _SPL_, for instance). In any case, I think the configuration template is quite explicit with one of the values for `store.type` being `phpsession`, and I find it intuitive that the _session_ extension is then needed. It's odd enough that this extension is not included by default with PHP in FreeBSD, but I don't think we can anticipate every single error like this that may happen.

I'll review the requirements section in the configuration, move some requirements to wherever they are used, and modify `composer.json` to make sure both _required_ and _suggested_ PHP extensions are included.

Thanks for the feedback!

**Comment by jaimeperez** [comment]
I'll stand corrected: both _pcre_ and _SPL_ are absolutely required!

In any case, I've fixed the documentation, added the PHP extension requirements to the `composer.json` file, and polished the requirements check in the configuration page.

Thanks Jørn! I'm closing the issue now, but feel free to reopen if you find more dependencies that are not specified!
