### ISSUE TITLE
Get rid of Translate->getPreferredTranslation()

### ISSUE THREAD

**Issue by hmpf** [simplesamlphp/simplesamlphp#460]
Find a way to use `t()` instead. For #455

**Comment by hmpf** [comment]
This method receives an array of langcode => translation pairs, for some unknown tag. We will need a new version of this somewhere, for dynamically loaded translations. It is however necessary to move all uses of this out of the template and into the calling page. Make a note where doing so would be very tricky.

An alternative is to send in the array in the context, have the currently set language as a langcode in the default context, and look up the translation directly: `{{ dynamicstatus[langcode] }}` for instance.

**Comment by jaimeperez** [comment]
I'd say the best option, in this case, is to have a static method somewhere (`SimpleSAML\Locale\Translate`, maybe?) that we can add to the Twig context as a filter, so that we can do something like:

```Twig
{{ variable_holding_translations|translate }}
```

We could even tell the filter to default to some language:

```Twig
{{ variable_holding_translations|translate('en') }}
```

Or we could default ourselves to some given string:

```Twig
{{ variable_holding_translations|translate|default('Our preferred translation') }}
```

**Comment by tvdijen** [comment]
Isn't `\SimpleSAML\Locale\Translate::translateFromArray()` exactly what we need? It is already available as a Twig filter..

**Comment by tvdijen** [comment]
Four cases left:

simplesamlphp-module-consent - Was presumably fixed in 8f256aa3eddbc03d8be61e0657ba0825580b236d, but has not been tested yet
simplesamlphp-module-consentadmin
simplesamlphp-module-discopower
simplesamlphp-module-statistics

**Comment by thijskh** [comment]
It's also used in our own codebase: lib/SimpleSAML/Locale/Translate.php

translateFromArray is not a ready-to-use alternative because it does not fall back. So if my interface is NL and I search an entity with $entity['name'] = ['en' => "Example"];, I get null back, not "Example". Probably we need some Twig convenience function for displaying an entity name, something like return the first of this in order when found:
- entity[uiinfo.displayname][curlang] 
- entity[name][curlang]
- entity[uinfo.displayname[defaultlang]
- entity[name][defaultlang]
- entity[uinfo.displayname[en]
- entity[name][en]
- entity[organizationdisplaynamename][curlang]
- entity[organizationname[curlang]
- entity[organizationdisplayname[defaultlang]
- entity[organizationname[defaultlang]
- entity[organizationdisplayname[en]
- entity[organizationname[en]
- entityid

**Comment by thijskh** [comment]
This use case is also described in #1244

**Comment by thijskh** [comment]
All cases have fixes committed or a PR present so is tracked there. The code has already been removed from SSP itself in 4e5c779d80fd3777e8e5f6a3c90efbaaa57a9a05 so these modules will be fixed either way or the other. This can now be closed.
