### ISSUE TITLE
Syntax errors are not handled correctly on PHP 7

### ISSUE THREAD

**Issue by EdgarPE** [simplesamlphp/simplesamlphp#483]
If there is a syntax error for example in config.php then the SimpleSAML_exception_handler() will be called with an Error object. The new fix in #330 will then call the SimpleSAML_error_handler() but the **$errno integer will contain 0**, so this code will stop the handling:
```
    if ($errno & SimpleSAML_Utilities::$logMask || !($errno & error_reporting())) {
        // masked error
        return false;
    }
```
All this resulting in a simple white screen of death, without any information, where the error is.

**Comment by jaimeperez** [comment]
Thanks for reporting this @EdgarPE!

Actually, in master you would never reach that problem since we have a hook now called from the error handler, that would try to load the configuration again and yield a fatal error.

I've just committed a fix so that the `SimpleSAML_Configuration` class captures those `ParseError` errors and initializes some empty configuration right before throwing them further, so that we can get rid of the fatal error and display an informative message.
