### ISSUE TITLE
custom ConsumerServiceURL

### ISSUE THREAD

**Issue by jeremyfrench** [simplesamlphp/simplesamlphp#503]
Hi. I'm in the process of a ssp implementation that will be replacing an existing saml implementation. This uses some external IDPs, and there is a desire with my client to not have to talk to partners to change these.

I'm having to write some custom callbacks to listen for the URLS that are used for SSO, however one thing I can't seem to do without hacking the SSP code base is to change or remove the 'ConsumerServiceURL'

this is set in SP.php

`ar->setAssertionConsumerServiceURL(SimpleSAML_Module::getModuleURL('saml/sp/saml2-acs.php/' . $this->authId));`

I can see no way to change this without hacking the file, it is in theory possible to extend the class, but that would require even more hacking of the ssp code base.

Am I missing something or is this pretty much hard coded?

At the moment some of the partner sites are using the value of this for identification of the IDP so even with a valid cert etc they are refusing to process.

**Comment by jaimeperez** [comment]
Hi @jeremyfrench!

You are not missing something. The SAML endpoints are completely hardcoded, and there's one good reason for that: the SAML protocol messages must reach the SimpleSAMLphp endpoints, so you should always use those endpoints instead of using any other URL.

In theory, it's possible to use mod-rewrite, so that you keep the existing URLs, and have Apache rewrite requests to the old URLs with the new ones. The problem then is that SimpleSAMLphp will keep thinking that the AssertionConsumerService must have a different URL, and if I recall correctly, it will fail when it sees that the destination of the SAML response does not match what it thinks it should be. You can always try, anyway.

In any case, it's a bad idea to change the implementation and pretend to keep everything as it was before because you don't want to distribute new metadata. If there are applications identifying the IdP based on the endpoints, that's terribly wrong, as they should always use the entityID, which is the only valid identifier for that purpose.
