### ISSUE TITLE
PHP Fatal error:  Cannot redeclare class SimpleSAML_Logger

### ISSUE THREAD

**Issue by answeb** [simplesamlphp/simplesamlphp#517]
Hi,
When I use the autoloader, I have the error below when I call "requireAuth()". I strictly followed the howto in the documentation. The "backoffice" and the tests are all working, but the following code raises an error :

require_once('../../lib/_autoload.php');
$as = new SimpleSAML_Auth_Simple('default-sp');
$as->requireAuth(); <-- Fatal error here
$attributes = $as->getAttributes();
print_r($attributes);

PHP Fatal error:  Cannot redeclare class SimpleSAML_Logger in /var/www/simplesamlphp/lib/SimpleSAML/Logger.php on line 14,

I only have this error where using latest version (1.14.9). No problems with 1.14.8

**Comment by tvdijen** [comment]
I haven't been able to reproduce this on my 1.14.9 install, so this is most likely related to a specific configuration.

**Comment by thijskh** [comment]
Is a backtrace logged?

**Comment by answeb** [comment]
How can I get the backtrace ? It is a fatal error ...

**Comment by tvdijen** [comment]
Depending on your system and configuration you should be able to pull some extra logging from /var/log/httpd/error_log or /var/log/messages

**Comment by answeb** [comment]
In my apache error.log, I only have that line : "PHP Fatal error:  Cannot redeclare class SimpleSAML_Logger in /var/www/simplesamlphp/lib/SimpleSAML/Logger.php on line 13"

Please note that I used the alternative location installation procedure as described in https://simplesamlphp.org/docs/stable/simplesamlphp-install#section_13

Again, please note that using 1.14.8, the problem does not occur...

**Comment by 82rules** [comment]
I'm getting the same error trying to call isAuthenticated on SimpleSAML_Auth_Simple

Seems like the cause is here: https://github.com/simplesamlphp/simplesamlphp/blob/master/lib/SimpleSAML/SessionHandlerPHP.php#L55-L59

I tried changing SimpleSAML\Logger to SimpleSAML_Logger as it seems that's how its being called in other locations but this code has been in place some time and I'm not familiar enough to know the impact. That change did cause a subsequent bad reference to getCookieParams here: https://github.com/simplesamlphp/simplesamlphp/blame/master/lib/SimpleSAML/SessionHandlerPHP.php#L78

**Comment by answeb** [comment]
Looks like there's a misuse of namespaces and autoloader...

**Comment by tvdijen** [comment]
What happens when you go to the /simplesaml url? Can you get to the admin-page? Does the sanitycheck say anything?

**Comment by answeb** [comment]
Everything works well from the example page, the tests are working, Everything works good. Only when I integrate the php in my cms, it does this. 
Tomorrow I will try in a simple php file. 

Le 16 novembre 2016 17:46:10 GMT+01:00, Tim van Dijen <notifications@github.com> a écrit :
>What happens when you go to the /simplesaml url? Can you get to the
>admin-page? Does the sanitycheck say anything?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/simplesamlphp/simplesamlphp/issues/517#issuecomment-261000641

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by jaimeperez** [comment]
Hi guys,

There is a bug indeed, and you were unfortunate enough that you were hitting it due to a misconfiguration on your side 😉 

@82rules you were almost right:

>Seems like the cause is here: https://github.com/simplesamlphp/simplesamlphp/blob/master/lib/SimpleSAML/SessionHandlerPHP.php#L55-L59

Actually, you are pointing to master, while you should point to the `1.14.9` tag instead. The problem (and that's the bug) is that the 1.14.9 tag also has the same code:

https://github.com/simplesamlphp/simplesamlphp/blob/v1.14.9/lib/SimpleSAML/SessionHandlerPHP.php#L55-L59

Given that in `1.14.9` the `SimpleSAML_Logger` class has not yet been migrated to namespaces (that's only in `master`), you are getting the error.

In order to hit this bug, the following requirements must be met:

* SimpleSAMLphp must be used as an __SP__.
* The application you are protecting must be using __PHP sessions__.
* You must have configured SimpleSAMLphp to use PHP sessions too.
* The `session.phpsession.cookiename` configuration option of SimpleSAMLphp must be either unset or set to the same session name the application is using.

This configuration is **wrong** and **won't work anyway**. You just can't have both your application and SimpleSAMLphp to share the same PHP session, they need to have their sessions separated. If you use another session backend in SimpleSAMLphp or configure the `session.phpsession.cookiename` configuration option to something different than the application is using, you won't see this error again and it will work.

In any case, we may have a new bugfix release to resolve this error. **Note that that doesn't mean your current setup will work with the new version, it will just fail in a different way**.

**Comment by answeb** [comment]
Thanks for the bugfix, I should have read the message that the logger was trying to show ;-)
1.4.19 is now working for me, after having set a different cookiename for the session variable.

**Comment by jaimeperez** [comment]
Great! Thanks for the feedback @answeb, I'm glad you got it working 😄

**Comment by 82rules** [comment]
🍻 Thanks for the clarification  @jaimeperez, indeed I had to dig into my configs for session to get my app set up correctly. Thanks to everyone for their help
