### ISSUE TITLE
Prevent eduPersonTargetedID/SAML persistent NameID being generated on empty value

### ISSUE THREAD

**Issue by lhaemmerle** [simplesamlphp/simplesamlphp#519]
Last week an issue was made public on the REFEDS mailing list regarding an SP that discovered that different users from two IdPs all had the same eduPersonTargetedID/SAML persistent NameID.

It seems that in both cases the root cause was that this attribute/nameID was generated creating a hash of another attributes, which in these two cases was empty. In at least one case, SSP was involved.

To prevent similar issues, SSP should therefore ensure that eduPersonTargetedID/SAML persistent NameID cannot be generated based on empty values. The value of the "attribute" specified in https://simplesamlphp.org/docs/1.14/saml:nameid should be checked before generating a hash. If it is empty, this attribute should not be generated and/or an error should be shown.

**Comment by jaimeperez** [comment]
Hi Lukas!

The way I see this, it's more a configuration issue than anything else. In any case, it's probably a good idea to be picky in the ePTID generation filters so that an empty attribute cannot be used as a source for it.

Could you (or someone else) provide a PR that we can discuss?

**Comment by lonoak** [comment]
Hi,

   have to add to this... the problem was not caused by SimpleSAMLphp itself, but by a different IdP behind a SimpleSAMLphp gateway (running a different software piece).

But yes, having this in SimpleSAMLphp would be possitive... 

I'm afraid I don't have the time to provide a PR for now... I'll discuss this with other persons who could probably help with this.

**Comment by jaimeperez** [comment]
If that's the case, there's not much SSP can do.

What Lukas is suggesting makes sense and is a good addition, IMHO. However, that will only work when SSP is used as the IdP. If SSP sits in the middle acting as a proxy, there's no way for it to avoid an issue like this to happen again, since its role is basically moving attributes around from one place to another.

**Comment by lhaemmerle** [comment]
I think it already would help if SSP (as IdP) could check for the case where an attribute used to generate the ePTID/SAML NameID is empty. This should not be very difficult I assume.
Obviously, things are more difficult when SSP is used as proxy. So, probably not so much that can be done in that scenario reasonably.

**Comment by lonoak** [comment]
I think we all agree it's IdP-side were it makes more sense to do the checks... but... SSp SPs could also benefit from sanity checks, for instance not letting users with known bad values access the service provider and raising an alert (so far I have only identified the 'da39a3ee5e6b4b0d3255bfef95601890afd80709' value, corresponding with an SHA1 hash of an empty string).

Jaime, how would you implement this IdP-side? Maybe a 'sanitychecks' authproc to be used in saml20-idp-hosted.php?

Jose.

**Comment by thijskh** [comment]
At least our code that generates NameIDs should error when empty values are used for its input?

**Comment by jaimeperez** [comment]
I've been doing some testing myself, and here are the conclusions:

* SimpleSAMLphp does **not** allow generating a persistent NameID from a missing (not found), empty (present, but without values) or multivalued (present, more than one value) attribute. It will log a warning and refuse generation of the `NameID`, subsequently impeding the creation of an `eduPersonTargetedID` attribute.
* However, it **does** allow the creation of a persistent `NameID` out of a present attribute with an empty string as its only value.

We can add a check to avoid empty strings, of course, but still that doesn't offer any guarantees that a common `NameID` won't ever be generated. The same way an IdP could end up with empty strings in the values for their users, they could misconfigure SSP to use some common attribute or misconfigure their backend so that the attribute used has always the same, non-empty value.

**Comment by thijskh** [comment]
Of course it does not offer a guarantee, but using an empty string will never be intentional so if we can prevent that error, we should.
