### ISSUE TITLE
Should be possible to include translated terms from modules

### ISSUE THREAD

**Issue by andreassolberg** [simplesamlphp/simplesamlphp#525]
Let us take `errors.twig` as an example.

Writing a new module `module123` that implements a theme, includes a `theme/theme123/default/error.twig`. If this extends a base in the module, in example `@module123/modulebase.twig`. It would be useful if the `modulebase.twig` could include dictionary entries from the module, not only from the core simplesamlphp. In example the base may want to include `{module123:common:footerText}`, but that does not seem to work right now.

**Comment by tvdijen** [comment]
The other way around is also an issue.. i.e. getting translations for module-specific hooks, like the links on the `frontpage_config.php`

**Comment by jaimeperez** [comment]
Relying on translations from modules other than the current (or from base templates) is problematic. Modules can be enabled and disabled, so it could be that the translations required are not available. As a rule of thumb, I would say a module should never rely on translations out of itself or the base translations included in SimpleSAMLphp.

The strings in the `core` or `saml` modules should probably be moved to the base dictionary.

**Comment by tvdijen** [comment]
I think this is a closure since recent new hooks-code... @jaimeperez ?

**Comment by jaimeperez** [comment]
Yes, I think the most common cases are covered:

* [Using strings from a module in a theme](https://github.com/simplesamlphp/simplesamlphp/blob/master/lib/SimpleSAML/XHTML/Template.php#L269-L271). As Andreas was saying, if you implement a theme, it should be possible to use your own strings.
* [Using strings from a module from templates in that module](https://github.com/simplesamlphp/simplesamlphp/blob/master/lib/SimpleSAML/XHTML/Template.php#L266-L268). Many modules would have some kind of user interface, and as such, they'll need their own templates. In that case, you will most likely need your own strings as well, and it should be possible to include them in the module.
* [Using strings from a module that is hooking into another module](https://github.com/simplesamlphp/simplesamlphp/blob/master/modules/sanitycheck/hooks/hook_configpage.php#L13). In many cases hooks are intended for other modules to inject or modify data presented to the user (e.g. the _frontpage_ hook). In those cases, the translations for the strings added / modified by the hook should be in the hooking module. In this case, it's the responsibility of the latter to register its own translations, since we can't know if those are necessary.
