### ISSUE TITLE
Support for non-default session.sid_length and session.sid_bits_per_character

### ISSUE THREAD

**Issue by aberenyi** [simplesamlphp/simplesamlphp#566]
Hi,

Let's assume one is using non-default values in `php.ini` for [`session.sid-length`](http://php.net/manual/en/session.configuration.php#ini.session.sid-length)  and [`session.sid_bits_per_character`](http://php.net/manual/en/session.configuration.php#ini.session.sid-bits-per-character) as per http://php.net/manual/en/session.security.ini.php.

Would be nice if the session ID generated [here](https://github.com/simplesamlphp/simplesamlphp/blob/master/lib/SimpleSAML/SessionHandlerPHP.php#L166) could use the aforementioned config params otherwise users logging in via SSP will have a completely different session ID compared to users logging in via any other (e.g. simple form POST) way.

What do you think?

Cheers

**Comment by jaimeperez** [comment]
Hi @aberenyi!

This is an interesting discussion, and I see arguments both in favour and against it. The most important argument in favor would be to be coherent with users' expectations, because if I'm using custom configuration settings in `php.ini` and I tell SimpleSAMLphp to use the PHP session handler, I would definitely expect it to honour that.

On the other hand, I see several downsides:

1. These two config options are only available from PHP 7.1, so we can't rely on them being available, and very few people would be using them anyway.
2. Blindly honouring these options could allow a user to downgrade the security of their session IDs.
3. SimpleSAMLphp's session ID must not be related to any other session ID, and in particular, sessions must never be shared. So in the scenario where users can login via different methods (a login form or a SAML login), both methods should have their own session cookies and as such, it's irrelevant if their contents look completely different or not.
4. On the other hand, it does make sense to have session IDs generated the same way in SimpleSAMLphp regardless of what session backend we are using. And of course, it doesn't make much sense to use PHP's settings when generating session IDs for the _memcache_ session handler.

So I'm not entirely sure I'm fine with the idea, though of course I'm open to discussion 😄 

All in all, this brings up another (more) important issue in my opinion, which is the current method we use today to generate session IDs:

```
bin2hex(openssl_random_pseudo_bytes(16))
```

Unfortunately, [this is not secure](https://bugs.php.net/bug.php?id=70014) if you are running a version of PHP lower than 5.4.44, 5.5.28 or 5.6.12. Even worse, depending on how you deployed PHP (if you are using Apache2 prefork MPM or FastCGI), it could be that the only acceptable version of `openssl_random_pseudo_bytes()` in terms of security may be PHP 5.6.24 [due to another bug](https://bugs.php.net/bug.php?id=71915).  [`random_bytes()`](http://php.net/manual/en/function.random-bytes.php) is much more appropriate, but only available in PHP 7, so not a good replacement.

The only solution I could think of in this case is:

```
    if is_openssl_random_pseudo_bytes_secure()
        return openssl_random_pseudo_bytes()
    
    if is_random_bytes_available()
        // random_bytes() is available either because we run PHP 7 or because we installed the polyfill
        return random_bytes()
        
    throw Exception('Cannot generate secure session identifier')
```

This means those affected by the bug in `openssl_random_pseudo_bytes()` could at least install the [`paragonie/random_compat`](https://github.com/paragonie/random_compat) polyfill, which supports PHP > 5.2, and use that to generate session IDs, keeping them on the safe side.

@thijskh, @DRvanR, @tvdijen any input on this?

**Comment by tvdijen** [comment]
Not really my expertise to be honest..
Could mcrypt_create_iv() be an alternative for broken openssl_random_pseudo_bytes()?

**Comment by jaimeperez** [comment]
Taking into account that `mcrypt` is abandonware in practice and that PHP 7.2 will drop support for it, we should probably get away from it as much as we can...

**Comment by thijskh** [comment]
Why not always call `random_compat()` and include the polyfill for the backwards compatibility?

Although I do think that we need not worry about CVE-2015-8867, I believe it's clearly the responsibility of the deployer to keep his PHP installation patched.

**Comment by jaimeperez** [comment]
You are right as usual @thijskh. It's irrelevant what function we use to generate the ID, as we will always present it hex-encoded, so it should be really transparent for the user.

My main concern was to avoid requiring the polyfill if it's not strictly necessary (that is, if we are running PHP 7 and `random_bytes()` is already available, or if you are running the latest 5.6.x version where `openssl_random_pseudo_bytes()` is secure), but at the same time adding it as a dependency should be ok as it's a small one, and it also has the side effect of making some setups more secure than they would be otherwise.

What about the original question about session IDs? Any thoughts on that?

**Comment by tvdijen** [comment]
I guess it would qualify as a 'nice to have'... Those settings are PHP 7.1+ though...
Now that I'm reading a bit about this... Is there a reason why we generate an ID ourselves, since `session_create_id()` would automatically honor the settings from `php.ini`?

**Comment by jaimeperez** [comment]
>Now that I'm reading a bit about this... Is there a reason why we generate an ID ourselves, since `session_create_id()` would automatically honor the settings from `php.ini`?

I can't tell because I didn't make that decision, but I'd guess _consistency_. Basically, using the same regardless of the session backend in use, since `session_create_id()` is only suitable for PHP sessions.

In any case, it's probably a good idea to just use `random_bytes()` and include the _random_compat_ polyfill as a dependency...
