### ISSUE TITLE
Server port detection always adds port to domain if server variable contains an integer

### ISSUE THREAD

**Issue by kjkooistra-youwe** [simplesamlphp/simplesamlphp#594]
https://github.com/simplesamlphp/simplesamlphp/blob/master/lib/SimpleSAML/Utils/HTTP.php
Method: \SimpleSAML\Utils\HTTP::getServerPort()
Line: 103

If $_SERVER['SERVER_PORT'] contains an integer, which it does in my case, the condition ($port !== '443') will always return true, resulting in the port always being added to the domain.
In turn this results in an error when attempting to retrieve the metadata, since the metadata is not configured with the port (https://domain.tld/simplesaml/ does not match https://domain.tld:443/simplesaml/).

Solution 1: Cast $_SERVER['SERVER_PORT'] to string on line 103:
`$port = (isset($_SERVER['SERVER_PORT'])) ? (string)$_SERVER['SERVER_PORT'] : '80';`

Solution 2: Cast $_SERVER['SERVER_PORT'] to integer on line 103 and change the conditions to use an integer as well on lines 105 and 109.
`$port = (isset($_SERVER['SERVER_PORT'])) ? (int)$_SERVER['SERVER_PORT'] : '80';
if ($port !== 443) {
if ($port !== 80) {`

**Comment by jaimeperez** [comment]
Hi @kjkooistra-youwe!

This is weird indeed. I've never seen an integer being set in `$_SERVER['SERVER_PORT']`. The proper solution to cover your case would be to pass whatever is in the variable to `intval()`, so that we guarantee the resulting integer is correct, and then compare with integers instead of strings. Casting the types is less explicit and I see that as more error prone if the semantics of casting changes in future versions of PHP, while a simple function as `intval()` should always behave the same.

In any case, there is a very simple solution for your problem without the need to modify SimpleSAMLphp's source code: set the `baseurlpath` configuration option in `config/config.php` to your absolute URL without the port.

**Comment by kjkooistra-youwe** [comment]
Hello @jaimeperez 
Unfortunately this does not work automatically since the environment is multi-domain and has to search through multiple metadata configurations. I simply updated the code myself for now to solve the issue.

**Comment by jaimeperez** [comment]
That shouldn't be a problem. Remember that the configuration files are PHP code, so you can build an absolute URL to use for `baseurlpath`, including the right domain for each request. Metadata should be irrelevant in this case...

**Comment by kjkooistra-youwe** [comment]
Hence the "automatically". But fixing the issue removes the need to have to add additional configuration.

**Comment by jaimeperez** [comment]
I don't see what you mean, sorry. You always have to configure the software when you install it. Modifying the `config.php` file is something you have to do anyway, and that includes setting the proper value in `baseurlpath`. If that value cannot be fixed, you can add code to the file to compute it dynamically and get rid of the issue, which is what I meant before:

```
<?php
function whatIsMyDomain() {
    // do whatever you need to do to find the domain in the current request, for example:
    return $_SERVER['SERVER_NAME'];
}

$config = array(
    ...
    'baseurlpath' => 'https://'.whatisMyDomain().'/your/path/to/simplesaml',
    ...
);
```

It's as simple as that, and it's completely automatic.

If you mean something else, it would be nice if you could clarify, because then I'm not following. There is no setup where you couldn't avoid this issue by configuring SimpleSAMLphp properly, instead of modifying the code, which is something you should never do.

**Comment by kjkooistra-youwe** [comment]
I understand what you mean, but in my case the baseurlpath is set to the default 'simplesaml/' relative path. The internal logic appears to already add the domain automatically. This worked just fine in 1.13, but after updating to 1.14 I ran into this bug.

**Comment by jaimeperez** [comment]
Yes, if you don't specify a full URL in `baseurlpath`, it will guess it for you.

In 1.14 we've solved plenty of bugs regarding self-URL building, and that's probably why you are experiencing this now (and we'll need to fix this too).

All that I'm saying is that configuring `baseurlpath` properly, you can circumvent the issue while you wait for a proper fix to be released, without the need to modify the code yourself.

**Comment by tvdijen** [comment]
@jaimeperez Would this be the fix you've proposed earlier in this thread?

**Comment by thijskh** [comment]
If we support this (edge)case then we should definitely also have a testcase for it.

**Comment by tvdijen** [comment]
PR is open for reviews

**Comment by tvdijen** [comment]
Fix has been merged
