### ISSUE TITLE
Protect all files

### ISSUE THREAD

**Issue by flippamike** [simplesamlphp/simplesamlphp#599]
Hi People,

Maybe this question dosn't belong here but hope someone can point me in the right direction. Every php file is now protected with simplesamlphp and work great. What is the best way to protect image's or other files by direct acces? For example github.com/image.jpg or github.com/home.html so that when people are not signed in they will get redirected to the adfs login page.

I am using IIS.

Thanks

mike

**Comment by jaimeperez** [comment]
Hi @flippamike!

This is an issue tracker, not a support forum. If you need assistance configuring or using SimpleSAMLphp, please use the [mailing list](http://groups.google.com/group/simplesamlphp).

In any case, [this](http://php.net/manual/en/ini.core.php#ini.auto-prepend-file) might be helpful. It will work only on PHP scripts, though, so if you also want to protect static files like HTML or images, you'll need to find another way. An option would be to rewrite URLs for static resources so that they are passed to a PHP script that performs authentication if needed, and serves the requested content.
