### ISSUE TITLE
Crypto::pwHash() isn't a password hashing function

### ISSUE THREAD

**Issue by paragonie-scott** [simplesamlphp/simplesamlphp#602]
https://github.com/simplesamlphp/simplesamlphp/blob/b64ad1db9fe6a8ecf30a139e259a6d5f6c06bed9/lib/SimpleSAML/Utils/Crypto.php#L304-L349

See instead: [How to safely store a password](https://paragonie.com/blog/2016/02/how-safely-store-password-in-2016).

For PHP applications with a wide user base, your options (to preserve BC) are: bcrypt (`password_hash()` and `password_verify()`) or PBKDF2-SHA256 (`hash_pbkdf2()` or a home-rolled implementation).

A simple cryptographic hash function is not adequate for storing passwords.

**Comment by jaimeperez** [comment]
Scott, thanks for moving the discussion here.

I'm well aware of that. However, this function is legacy, intended to allow people having ancient (and broken) password hashes to keep authenticating their users. It's not used to _create_ new passwords, but to check existing (right, insecure) ones. Read it `pwdVerify()` if you want.

I agree that people should stop using password hashes that were not created properly with salt and a suitable algorithm such as Argon2 or Bcrypt. Unfortunately, we had to live with this the same way we had to live with keeping support for PHP 5.3, just because some OS vendors (RH, ahem) keep providing security fixes for it and don't spend time on providing more reasonable, up-to-date versions in their LTS releases.

For that very same reason, `password_hash()`, `password_verify()` and `hash_pbkdf2()` are not an option still. We could probably start using a polyfill for those running ancient PHP versions and be able to use them, but still, we would need to keep this to support those using those particular hashes.

In general, I doubt (hope) anybody is actually using the authentication sources that end up using this function to verify a password. If someone still does and we remove support for this, they can easily extend SimpleSAMLphp by copying and pasting this code into a new auth source, and keep using the vulnerable hashes.

In short, we can't avoid people doing something wrong. We could try, but they'll always find ways around it.

**Comment by tvdijen** [comment]
How this for a solution? https://github.com/tvdijen/simplesamlphp/commit/3c3341c11b8012d0acc362cf1d4775f653e00b39
It would be backwards compatible with current hashes, old code could go away for 2.0

**Comment by thijskh** [comment]
@dnmvisser

**Comment by tvdijen** [comment]
@jaimeperez

**Comment by tvdijen** [comment]
It should be possible to select something stronger than BCRYPT (default) when generating a new hash. i.e. argon2

**Comment by dnmvisser** [comment]
I remember the rationale for offering a choice was to accommodate whatever algos a local installation supported. But that meant including possibly insecure ones.
So hardwiring newly created hashes to `PASSWORD_BCRYPT` sounds good, also because the [minimum required PHP version for this algo](http://php.net/manual/en/intro.password.php) is 5.5.0, which happens to be the same as the requirement for SSP itself.
Looking at http://php.net/manual/en/password.constants.php it might be even better to hardwire it to `PASSWORD_DEFAULT`, which currently is `PASSWORD_BCRYPT` but "may change in newer PHP releases when newer, stronger hashing algorithms are supported".
In any case, newer/better algos such as `PASSWORD_ARGON2I` would currently require newer PHP versions, so these should probably be offered only if probing has established that they're actually available (similar to the old behavior). Not sure if that approach still works though.
