### ISSUE TITLE
Maximum function nesting level

### ISSUE THREAD

**Issue by chrisworfolksky** [simplesamlphp/simplesamlphp#624]
On attempting to login, I am getting:

    Fatal error: Maximum function nesting level of '100' reached, aborting! in /opt/docroot/app/src/simplesamlphp-1.12.0/lib/SimpleSAML/Error/Assertion.php on line 29

I have tried it with both ADFS and UserPass, and in both scenarios I get the same thing. Looking at the stack trace it is just bouncing around between Exception, Logger and Assertion. These are the calls where it is getting stuck in a loop:

    92	0.0725	2429016	SimpleSAML_Error_Assertion::onAssertion( $file = '/opt/docroot/app/src/simplesamlphp-1.12.0/lib/SimpleSAML/Logger.php', $line = 225, $message = 'is_string(self::$trackid)' )	../Logger.php:225
    93	0.0730	2592296	SimpleSAML_Error_Exception->logError( )	../Assertion.php:79
    94	0.0730	2617144	SimpleSAML_Logger::error( $string = 'SimpleSAML_Error_Assertion: Assertion failed: \'is_string(self::$trackid)\'' )	../Exception.php:177
    95	0.0730	2617192	SimpleSAML_Logger::log_internal( $level = 3, $string = 'SimpleSAML_Error_Assertion: Assertion failed: \'is_string(self::$trackid)\'', $statsLog = ??? )	../Logger.php:75
    96	0.0730	2617240	SimpleSAML_Logger::getTrackId( )	../Logger.php:191
    97	0.0730	2617336	assert ( 'is_string(self::$trackid)' )

I'm using the embedded version (i.e. not bringing it in via Composer). I've seen this on 1.12, but I've also tried upgrading to 1.14.14, which is the latest one at time of writing, and I'm getting the same error.

**Comment by jaimeperez** [comment]
Hi @chrisworfolksky,

This looks like an issue with your session and your PHP configuration, as it is halting on assertion errors. Make sure `assert.exception` is off in your `php.ini`.

On the other hand, the fact that this assertion in particular is failing indicates something terribly wrong. The track ID (which is what's generating the error) has two different ways to be initialized:

```php
$this->trackid = 'TR'.bin2hex(openssl_random_pseudo_bytes(4));
```

or:

```php
$this->trackid = bin2hex(openssl_random_pseudo_bytes(5));
```

depending on whether you are using a transient session or not. In any case, in both cases the track ID must be a string, so if you have something else than a string (making the assertion fail), it must have been generated in some weird way. In any case, the problem should go away if you just remove your cookies and start over. If the problem persists, then there must be something very wrong on your setup, because this works just fine.
