### ISSUE TITLE
How to set the destination

### ISSUE THREAD

**Issue by curkychen** [simplesamlphp/simplesamlphp#650]
Hi,
I am new to saml and simplesamlphp. I am developing the sp of my department website. I am now stuck with redirecting to the idp. I can not redirect to my campus idp when click the login, the error message shows The application you have accessed is not registered for use with this service.
When I check with the SAML tracer, I find out that the destination is wrong. 
The destination should be :"https://login.xxx.edu/idp/profile/SAML2/Redirect/SSO"
However in my page, it becomes "https://login.xxx.edu/idp/profile/SAML2/POST/SSO"

Any kinds of suggestion will be greatly appreciated. Thank you so much.

Also I am looking for tutorials of shibboleth or simplesamlphp for beginners. I am actually still kind of confusing about how to use shibboleth and simplesamlphp. Thank you so much.

**Comment by jagland** [comment]
Sounds to me like the IdP has received an AuthnRequest from an SP entity it does not have listed in it's metadata, you need to exchange metadata between the IdP and SP.  Talk to your campus IdP operator, as rather than doing a direct exchange then the might prefer you to register your SP with a SAML Federation e.g. InCommon and exchange metadata that way via the federations published metadata.

This appears to be the relevant section of the simpleSAMLphp documentation - https://simplesamlphp.org/docs/1.14/simplesamlphp-sp#section_4

**Comment by thijskh** [comment]
Thanks @jagland for the analysis. Also this is an issue tracker, not a support forim. Please refer to the [Mailing lists](https://simplesamlphp.org/lists) for support questions.
