### ISSUE TITLE
Bug! Check is secure connection SimpleSAML\Utils\HTTP::getServerHTTPS()

### ISSUE THREAD

**Issue by ihurskyi** [simplesamlphp/simplesamlphp#654]
This is not enough validation for 'https'. 
Please take a look for example on Yii2:

        **

> return isset($_SERVER['HTTPS']) && (strcasecmp($_SERVER['HTTPS'], 'on') === 0 || $_SERVER['HTTPS'] == 1)
>             || isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && strcasecmp($_SERVER['HTTP_X_FORWARDED_PROTO'], 'https') === 0;

**

**Comment by tvdijen** [comment]
The `X-forwarded-` headers can be forged really easily, so this doesn't add any protection... Unless I'm missing your point here?

**Comment by pmeulen** [comment]
Hi ihurskyi,

I take it you are referring to: https://github.com/simplesamlphp/simplesamlphp/blob/master/lib/SimpleSAML/Utils/HTTP.php#L69-L90
That function looks at the $_SERVER['HTTPS'] to determine HTTPS status. By default, this variable is set by the HTTP servers that I know of (Apache, nginx, IIS), which means that it cannot be manipulated by adding a header in the HTTP request. Like tvdijen commented, I don't think that is true for the HTTP_X_FORWARDED headers.

That makes the code example you provide is actually **less** strict because it makes the function return true when either the HTTPS variable is set or the HTTP_X_FORWARDED headers indicate https was used. And these header can in many cases be controlled by an attacker.

The HTTP_X_FORWARDED headers are used in combination with a reverse proxy, so if you have a reverse proxy that terminates TLS and that forward the HTTP request over HTTP to the SSP webserver then this function might indeed not behave as you expect. A solution could be to configure the SSP webserver such that it sets the HTTPS header based on the HTTP_X_FORWARDED_PROTO header. This is not something I want to see hard coded in SSP, because not everybody is in this situation

Otherwise I don't understand what the bug is.

**Comment by jaimeperez** [comment]
Hi @ihurskyi!

@tvdijen and @pmeulen have already given you a good explanation. If you need more details, you might want to take a look at #419, or search for `X-Forwarded` in the issues here to find the many discussions we've had already about this.

In any case, there's no bug in that method (at least not the one you are suggesting), and the code you are proposing is actually introducing a security issue.
