### ISSUE TITLE
Reauthenticate "Attributes" are ignored

### ISSUE THREAD

**Issue by fidli** [simplesamlphp/simplesamlphp#659]
In lib/SimpleSAML/IdP.php, line 307:
`$state['Attributes'] = $idp->authSource->getAttributes();`
makes method reauhtenticate() on  SimpleSAML_Auth_Source classes useless for "Attributes", because the saved attributes, that had been changed in reauthenticate have been overwritten from the session..

even calling 
`SimpleSAML_Auth_State::saveState($state, self::STAGEID);`
in reatuhenticate()

did not re-save the attributes...

**Comment by jaimeperez** [comment]
Hi @fidli!

That's because the persistent data in the state array (e.g. the attributes) must be consolidated to the session once the user has been authenticated. If the `reauthenticate()` method needs to do something that affects the authentication information in any way, it should call `SimpleSAML_Session::doLogin()` itself, similarly to how `SimpleSAML_Auth_Source::loginCompleted()` does it:

```php
        // save session state
        $session = SimpleSAML_Session::getSessionFromRequest();
        $authId = $state['SimpleSAML_Auth_Source.id'];
        $session->doLogin($authId, SimpleSAML_Auth_State::getPersistentAuthData($state));
```

This way you are marking explicitly a new authentication with new information, with that being the case if the attributes change for the user.
