### ISSUE TITLE
Removing "default-sp" from authsources.php seems to break installation

### ISSUE THREAD

**Issue by eubyte** [simplesamlphp/simplesamlphp#663]
I do not intend to use 'saml:SP' for my IdP installation, but when I remove 'default-sp' from authsources.php, most pages (e.g. frontpage_federation.php, etc.) become unavailable/white. Am I missing something? Any help/advice is greatly appreciated.

**Comment by thijskh** [comment]
What error is there in your webserver's logs?

**Comment by eubyte** [comment]
actually, no error -- but there is simply no content on the page(s)

**Comment by thijskh** [comment]
In the webserver's logs, not on the page(s).

**Comment by eubyte** [comment]
right, it 200 -- no errors

**Comment by thijskh** [comment]
If you get a white page it's very likely that PHP logs an error somewhere (maybe not where you're looking). You could try the syslog or enable the display_error setting of PHP to have it on the webpage instead of the logs.

This starts to look more like a support request than a concrete bug report. Please use the [mailing list](https://simplesamlphp.org/lists) for support request. You can file the bug report here if it's determined that it is indeed a bug and what the relevant log information is.

**Comment by eubyte** [comment]
Ok, thank you!
