### ISSUE TITLE
Validate request parameters

### ISSUE THREAD

**Issue by spaceone** [simplesamlphp/simplesamlphp#692]
It is possible to trigger a stacktrace by accessing: https://foo.com/simplesamlphp/saml2/idp/SSOService.php?SAMLRequest[0]=Foo

This was discovered in a security penetration testing by one of our customers. We already disabled that tracebacks are shown to end users. This issue should only fix the specific type checking.

Original feedback:
```
RISK CLASS
====================
Misconfiguration
BUSINESS RISK
====================
This ticket does not introduce a vulnerability by itself. The headers can be used to help identify security flaws which may exist as a result of the choice of technology exposed in these headers. This facilitates further steps.
DESCRIPTION
====================
The remote application does not properly handle application errors, and application stacktraces are displayed to the end user leading to information disclosure vulnerability.
REMEDIATION
=================
1) Implement a standard exception handling mechanism to intercept all errors.
2) Ensure that version of the used framework and web server are not being exposed.
PRECONDITION
==============
n/a
PROOF OF CONCEPT
====================
Request:
https://ucs-sso.eu.xyz.com/simplesamlphp/saml2/idp/SSOService.php?SAMLRequest[0]=DAVE
Response:
 
        <p style="margin: 1px">SimpleSAML_Error_Error: UNHANDLEDEXCEPTION</p>
        <pre style="padding: 1em; font-family: monospace;">Backtrace:
1 /usr/share/simplesamlphp/www/_include.php:43 (SimpleSAML_exception_handler)
0 [builtin] (N/A)
Caused by: Exception: Missing SAMLRequest or SAMLResponse parameter.
Backtrace:
2 /usr/share/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML2/HTTPRedirect.php:101 (SAML2_HTTPRedirect::receive)
1 /usr/share/simplesamlphp/modules/saml/lib/IdP/SAML2.php:293 (sspmod_saml_IdP_SAML2::receiveAuthnRequest)
0 /usr/share/simplesamlphp/www/saml2/idp/SSOService.php:19 (N/A)</pre>
REFERENCES
====================
http://cwe.mitre.org/data/definitions/388.html https://www.owasp.org/index.php/Error_Handling
```

**Comment by jaimeperez** [comment]
Hi @spaceone!

Unless I'm missing something, there's nothing wrong here. SSP installs an exception handler that intercepts all errors, this one in particular too. When the error is completely unexpected (as in this case), we can't do anything other than just inform the user.

I believe what the pentesters wanted to signal here is the fact that there's a backtrace printed out. However, that's a configuration decision (the `showerrors` configuration option in `config/config.php` should always be set to `false` on production environments) and even when enabled, the back traces are redacted so that the full path in the file system is not shown to the user, but only the relative path to the files in the SSP installation, so no private information is leaked.

**Comment by spaceone** [comment]
@jaimeperez We are already setting `showerrors` to false in the configuration, so we integrated the suggestions from the pentest. My bug report aims that another assertion is added in the code, that the `SAMLRequest` parameter must be a string. I am personally not interested in this, the customer only wanted that I send this upstream.

**Comment by jaimeperez** [comment]
Uhm, not sure what would be the value of such an error message. If this was something happening relatively often due to some faulty software, then it would make sense to make it explicit that the parameter must be a string. However, given that this was discovered during a penetration testing, the error is introduced manually and consciously, so I don't see much value in handling that case to provide better error reporting for an error that'll virtually never happen...

**Comment by spaceone** [comment]
Okay, it's my opinion, too. Thanks.

**Comment by jaimeperez** [comment]
Thanks in any case! And please let us know if you have any other findings that need our attention.
