### ISSUE TITLE
autoload.php violates chrome CSP

### ISSUE THREAD

**Issue by richbai90** [simplesamlphp/simplesamlphp#713]
I've followed the instructions in the documentation and have a working implementation, but when I put in the code to authenticate from an application I get a content security policy violation.

```PHP 
<?php
require_once (dirname(__FILE__) . '/../../../simplesamlphp/lib/_autoload.php');
$as = new SimpleSAML_Auth_Simple('supportworks');
$as->requireAuth();
```

I get the following error

```
Refused to connect to 'https://swadfs.sw.test/adfs/ls/?SAMLRequest=...' 
because it violates the following Content Security Policy directive: 
"default-src 'self'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.
```

**Comment by thijskh** [comment]
The way (simple)SAML works is that when your application starts an authentication request, a HTTP redirect to the IdP is done (Location-header).

You are setting a specific `Content-Security-Policy` header in your application. It seems that this CSP blocks an HTTP redirect. I have not seen this before but it could be changed behaviour of a browser implementation. What happens if you change the CSP header, e.g. add the IdP URL to the allowed list?

**Comment by richbai90** [comment]
This issue can be closed. The problem was 2 fold, one as you said the content-security-policy. Adding the following to my .htaccess file fixed that

`Header set Content-Security-Policy "default-src 'self' *.sw.test;`

Two, the application I was trying to integrate this into was using an ajax request to reach the file with the redirect violating the preflight check response. I also fixed that so that it would change the url not reach the file via ajax.

**Comment by jaimeperez** [comment]
Thanks for letting us know @richbai90! Glad you got it to work 😄
