### ISSUE TITLE
The logging handler 'file' is invalid

### ISSUE THREAD

**Issue by s0rin** [simplesamlphp/simplesamlphp#741]
It seems that since 1.15.0 the **logging.handler' => 'file'** isn't supported, here the error:

```
Exception encountered, of type "Exception"
[227fb1b9513f1648efd3013e] /kim/index.php/Spezial:PluggableAuthLogin Exception from line 378 of /var/simplesamlphp/lib/SimpleSAML/Logger.php: The logging handler 'file' is invalid.
Backtrace:
#0 /var/simplesamlphp/lib/SimpleSAML/Logger.php(413): SimpleSAML\Logger::createLoggingHandler()
#1 /var/simplesamlphp/lib/SimpleSAML/Logger.php(181): SimpleSAML\Logger::log(integer, string)
#2 /var/simplesamlphp/lib/_autoload_modules.php(68): SimpleSAML\Logger::warning(string)
#3 [internal function]: temporaryLoader(string)
#4 /var/www/html/extensions/SimpleSAMLphp/SimpleSAMLphp.php(126): spl_autoload_call(string)
#5 /var/www/html/extensions/SimpleSAMLphp/SimpleSAMLphp.php(38): SimpleSAMLphp->getSAMLClient()
#6 /var/www/html/extensions/PluggableAuth/PluggableAuthLogin.php(45): SimpleSAMLphp->authenticate(NULL, NULL, NULL, NULL)
#7 /var/www/html/includes/specialpage/SpecialPage.php(479): PluggableAuthLogin->execute(NULL)
#8 /var/www/html/includes/specialpage/SpecialPageFactory.php(577): SpecialPage->run(NULL)
#9 /var/www/html/includes/MediaWiki.php(282): SpecialPageFactory::executePath(Title, RequestContext)
#10 /var/www/html/includes/MediaWiki.php(735): MediaWiki->performRequest()
#11 /var/www/html/includes/MediaWiki.php(509): MediaWiki->main()
#12 /var/www/html/index.php(43): MediaWiki->run()
#13 {main}
```

**Comment by tvdijen** [comment]
The only reason I can think of for this to happen, looking at the code, is that your MediaWiki application has a class defined named 'file'...

**Comment by tvdijen** [comment]
See if this fixes your issue:
https://github.com/tvdijen/simplesamlphp/commit/610edb25e265887fc048f16bf8c1adc05c2adebb
And let us know!

**Comment by s0rin** [comment]
Indeed, this fixes the issue!

Thank you!


Am 08.12.2017 um 15:31 schrieb Tim van Dijen:

**Comment by tvdijen** [comment]
The fix has been merged into master and will hopefully end up in the next bugfix-release. Until then you have a workaround!

**Comment by neerolyte** [comment]
I've run in to this too and it's not obvious from the above what the suggested workaround is.

Because of the way we're deploying it's going to be impractical to patch SimpleSAMLphp.

Reading the code it seems like I can just pass the full name to the logging class, e.g instead of:

```php
    'logging.handler' => 'file',
```

use:

```php
    'logging.handler' => 'SimpleSAML\\Logger\\FileLoggingHandler',
```

are there any perceived issues with doing this?

**Comment by tvdijen** [comment]
That should be totally fine!

**Comment by neerolyte** [comment]
Great, thanks for confirming!

**Comment by forevermatt** [comment]
@tvdijen I also hit a situation where this bug was causing problems. (In my case, another library's autoloader was choking on trying to find a `syslog` class.)

It looks like there have been two bugfix releases since this was fixed. I'm not trying to complain, just to get a since of what to expect: do you have any plans or expectations regarding when this fix will be included in a 1.15.x release?

Thanks a bunch.

**Comment by tvdijen** [comment]
I'm afraid we've missed the fix over the last two bugfix-releases... I've just pushed it to the 1.15 branch, so it will be in the next bugfix-release

**Comment by forevermatt** [comment]
Great! And impressive response time, too.  :-)

**Comment by tvdijen** [comment]
What can I say, I'm a geek so a computer is rarely far away :'D
