### ISSUE TITLE
modules/authYubiKey/www/resources/logo.jpg contains Exif data

### ISSUE THREAD

**Issue by olivier1980** [simplesamlphp/simplesamlphp#803]
We have a security checker running on every build that checks all files for hidden data. Right now our build fails because of the **'modules/authYubiKey/www/resources/logo.jpg'** containing Exiv data. 

This seems like a security risk to me, should the image be replaced?

**Comment by jaimeperez** [comment]
Hi @olivier1980!

I assume you mean exif data. In that case, what exif data? I can only see size, orientation and resolution. Besides, what's the security risk here?

**Comment by olivier1980** [comment]
Hi, thanks for the quick reply. Exif data is a security risk depending on how secure/private your data needs to be. In this case, the image is harmless and we could probably tweak our Exif check on our end. 

Nonetheless, there are a couple of articles worth reading about this, which might convince you it would be better to strip Exif data from project files (if only for a more consistent- and smaller codebase):

- https://www.smartdatacollective.com/big-data-small-details-metadata-creates-security-risks/
- https://darkwebnews.com/security-guide/exif-data/

**Comment by thijskh** [comment]
Would be good to strip it because it serves no useful purpose but causes noise in these kind of scanners (which you may or may not agree with, but the noise is there).

**Comment by tvdijen** [comment]
I have removed the EXIF-data on master...
@olivier1980 could you confirm that your security checker is silenced now?

**Comment by olivier1980** [comment]
@tvdijen great, thanks! I will post an update next week when I get back to work

**Comment by jaimeperez** [comment]
Hi guys!

This is a good example of why automated security scanners are far from optimal. Of course, EXIF data **can** contain personal or sensitive information, and that could end up being a security risk under certain circumstances. However, blindly flagging the mere presence of EXIF data as a security risk while analyzing the security of software is plainly stupid.

I agree that this particular EXIF data serves no purpose and if we can get rid of it to avoid the noise and get better output from automated tools, that's good. But there is absolutely no security risk in that particular image having EXIF data, precisely because that EXIF data serves no purpose! This is like flagging as vulnerable every application printing values taken from a database, because those values **may** be sensitive. It just doesn't make any sense.

Anyway, my two cents.

**Comment by olivier1980** [comment]
@tvdijen our test works, thanks.

@jaimeperez I agree our scanner is not optimal, but we had to weigh the time and effort of doing a 'dumb' scan and a more sophisticated scan..In the end building a sophisticated scan would require more time for maintenance and tweaking when new security issues arise. 
So for now I'm glad we can keep using the dumb scan :)
