### ISSUE TITLE
Path for src and href to post.js and post.css is faulty

### ISSUE THREAD

**Issue by kfonce** [simplesamlphp/simplesamlphp#812]
When you specify a full url as baseurlpath (i.e. "https://saml.example.com/") the created path for the `post.js` and `post.css` in the default `post.php` template file is wrong.

As can be seen here:
https://github.com/simplesamlphp/simplesamlphp/blob/da119effdd152d6d9bbbec842eb1d517c768b563/templates/post.php#L7
https://github.com/simplesamlphp/simplesamlphp/blob/da119effdd152d6d9bbbec842eb1d517c768b563/templates/post.php#L9

Both lines start with a forward slash which will make the compiled path invalid and creates a fallback to "www.example.com" which was not the baseurlpath.

For me this resulted in the displaying of the `post.php` template page without the submit button being clicked automatically since the js script did not get loaded.

**Comment by thijskh** [comment]
Removal of the `/` is likely not the fix for your problem. Because **all** our templates currently have a `/` followed by the baseurlpath template variable.

(It is in fact listed as a TODO to remove that: https://github.com/simplesamlphp/simplesamlphp/blob/master/lib/SimpleSAML/XHTML/Template.php#L104)

Note that the baseurlpath template variable is not the same as the baseurlpath config variable, it's populated with the result of `getBasePath()`:
https://github.com/simplesamlphp/simplesamlphp/blob/master/lib/SimpleSAML/Configuration.php#L489

**Comment by jaimeperez** [comment]
Since the starting `/` is fine, as Thijs commented, I'm closing this issue. @kfonce please provide us with more information about your setup if you really think there is a bug somewhere.
