### ISSUE TITLE
as_logout ReturnTo fails with Invalid URL when ReturnTo has query string

### ISSUE THREAD

**Issue by geemang2000** [simplesamlphp/simplesamlphp#856]
I've tried urlencoding the ReturnTo param too. If I remove the query string it works. 

May 12 14:24:47 ACCESS ERROR [5b58d850b8] Caused by: SimpleSAML_Error_Exception: Invalid URL: https://somedomain/fed/v1/user/testspstart?partnername=some query string
May 12 14:24:47 ACCESS ERROR [5b58d850b8] Backtrace:
May 12 14:24:47 ACCESS ERROR [5b58d850b8] 2 /opt/spgateway/simpleSAMLphp/lib/SimpleSAML/Utils/HTTP.php:330 (SimpleSAML\Utils\HTTP::checkURLAllowed)
May 12 14:24:47 ACCESS ERROR [5b58d850b8] 1 /opt/development/spgw/icsModule/icsgw/www/as_logout.php:18 (require)
May 12 14:24:47 ACCESS ERROR [5b58d850b8] 0 /opt/spgateway/simpleSAMLphp/www/module.php:135 (N/A)
May 12 14:24:47 ACCESS ERROR [5b58d850b8] Error report with id f1cf9810 generated.

**Comment by tvdijen** [comment]
Please send your support requests to our [mailinglist](https://simplesamlphp.org/lists), because this is not the place for that. And please provide some more details if you do, because there's little to go on here..
Make sure that all parts of your query that need it are properly urlencoded, not just the returnTo-parameter.
