### ISSUE TITLE
Upgrading to simplesamlphp 1.15.4 and acquia

### ISSUE THREAD

**Issue by iefrati** [simplesamlphp/simplesamlphp#878]
I am trying to upgrade my version of simplesamlphp to the latest stable one that is available [here](https://simplesamlphp.org/download) 

An installation on MAMP is working just fine, no issues. The minute I push the code to my site on acquia everything breaks.

trying to hit site.com/simplesaml results with a 500 error and this in the log

`  thrown in /mnt/www/html/site/simplesamlphp/lib/_autoload.php on line 18 request_id="REMOVING THE ID"
[19-Jun-2018 17:52:58 UTC] PHP Fatal error:  Uncaught exception 'Exception' with message 'Unable to load Composer autoloader' in /mnt/www/html/site/simplesamlphp/lib/_autoload.php:18
Stack trace:
#0 /mnt/www/html/site/simplesamlphp/www/_include.php(32): require_once()
#1 /mnt/www/html/site/simplesamlphp/www/index.php(3): require_once('/mnt/www/html/s...')
#2 {main}
`

Anyone has any idea how should I debug/fix this?

**Comment by jaimeperez** [comment]
Hi @iefrati,

This is an issue tracker, not a support forum. It'd be better if you ask for support in our [mailing list](http://groups.google.com/group/simplesamlphp).

In any case, that looks like you don't have all the dependencies installed with composer. Since we distribute packages with the dependencies preinstalled, it must be something with your acquia installation. SimpleSAMLphp expects to find an `autoload.php` file either in the `SSP-ROOT/vendor/` directory, or in the directory where SimpleSAMLphp is installed. If you don't have it, then your installation is broken.
