### ISSUE TITLE
Allow setting secure cookie when server connection is http

### ISSUE THREAD

**Issue by jplahti** [simplesamlphp/simplesamlphp#879]
Checking of secure server connection with setting "session.cookie.secure = true" leads to unwanted behaviour on load balancer TLS-terminated environments, where the application server running SimpleSAMLphp sees internal http connections only and prevents setting cookie secure flag.

Please remove this check, because interpreting the secure flag on cookie should be left for the browser to deside. Or maybe even better add extra setting e.g. "behindsecureproxy", which can be used to fine tune the behaviour.

**Comment by jaimeperez** [comment]
Hi @jplahti,

The test serves a purpose: letting the admin know that there is a misconfiguration. If you are accessing SimpleSAMLphp through plain HTTP and `session.secure.cookie` is `true`, there is an incongruency there. Cookies marked secure (as you are requesting in the configuration) cannot be sent through plain HTTP, and that leads to lost sessions.

If that's causing issues in your particular deployment, then you haven't configured SimpleSAMLphp properly. Since you have a load balancer in front of your backend, and you want to set `session.cookie.secure` in the configuration, I assume all access to your app/SimpleSAMLphp must be done via HTTPS. In that case, you should configure the base URL accordingly. Look at the `baseurlpath` configuration option. We even have a comment explaining how to configure it in your specific deployment:

> The full url format is useful if your SimpleSAMLphp setup is hosted behind a reverse proxy. In that case you can specify the external url here.

**Comment by jplahti** [comment]
"baseurlpath" was configured correctly, but while melding configs from older version I had missed the new "application->baseURL" setting. Setting that fixed the issue.
