### ISSUE TITLE
Using AssertionConsumerServiceURL in a signed AuthRequest 

### ISSUE THREAD

**Issue by pescej** [simplesamlphp/simplesamlphp#884]
Hello. I would like to suggest reopening https://github.com/simplesamlphp/simplesamlphp/issues/355
due to a technically.

#355 was closed stating "if what you are proposing is to allow sending responses to endpoints that are not registered in the metadata. If that's the case, the SAML standard explicitly forbids this in the SAML 2.0 profiles document:"

I do not believe that this is the case. If you will allow me to make the following argument, I hope that you will agree with me.
The specification says "Whether the request is signed or not, the identity provider MUST ensure that any `<AssertionConsumerServiceURL>` or `<AssertionConsumerServiceIndex>` elements in the request are verified as belonging to the service provider to whom the response will be sent. Failure to do so can result in a man-in-the-middle attack."

To say that PingIdentity is wrong in their doc: https://ping.force.com/Support/PingFederate/Administration/Specifying-Assertion-Consumer-Service-in-AuthnRequest is an oversimplification.

The specification only says that the IDP must "ensure" that the `<AssertionConsumerServiceURL>` is verified as belonging to the service, NOT that the service is forbidden to provide it. 

PingIdentity's document says "When the AuthnRequest is not digitally signed, Ping Federate(PingFed) validates the AssertionConsumerServiceURL specified in the AuthnRequest, against the finite list that is configured on the IDP side." 
But if the request IS signed by the SP, then PingIdentity has VERIFIED that the <AssertionConsumerServiceURL> belongs to the service, and is therefore permitted by the specification to allow it.

Isn't the point of the SP signing the request, verifying that the content of the request is that of the SP?

As a developer, is it not unreasonable to want to test a new API with api/v2/callback, instead of the api/v1/callback in the metadata, so long as the request is signed by my SP's private key?

**Comment by jaimeperez** [comment]
Hi @pescej!

I'm sorry but I don't see any new argumentation here to reopen that issue (why not continuing the discussion there, by the way?).

> The specification only says that the IDP must "ensure" that the `<AssertionConsumerServiceURL>` is verified as belonging to the service, NOT that the service is forbidden to provide it.

Of course not, nobody is saying that.

> PingIdentity's document says "When the AuthnRequest is not digitally signed, Ping Federate(PingFed) validates the AssertionConsumerServiceURL specified in the AuthnRequest, against the finite list that is configured on the IDP side."
But if the request IS signed by the SP, then PingIdentity has VERIFIED that the belongs to the service, and is therefore permitted by the specification to allow it.

Let me go back to the relevant paragraph in the standard:

> [...]
> 533 MUST NOT be trusted except as advisory. **Whether the request is signed or not**, the identity provider
> 534 MUST ensure that any `<AssertionConsumerServiceURL>` or
> 535 `<AssertionConsumerServiceIndex>` elements in the request are verified as belonging to the service
> [...]

In other words, **it doesn't matter if the request is signed**, the IdP **must** verify the endpoint. If that doesn't matter, then that means that the fact that the signature is verified is not enough to _ensure that any `<AssertionConsumerServiceURL>` belongs to the service_. If a request is signed and fails to verify, then the request should be dropped. If it is verified indeed, that sentence in particular says that it doesn't matter, you **still** need to ensure the ACS belongs to the service. So you need an alternative way to do such verification, as **the signature is not enough**. The only way you have left to do that is checking the metadata.

In any case, this could be a bad choice of words while writing the standard, I won't deny that. Especially considering that Shibboleth also behaves that way. However, that wasn't the only reason to support not adding this as a feature, and I don't see you are arguing the rest of [my arguments](https://github.com/simplesamlphp/simplesamlphp/issues/355#issuecomment-205731113).

> Isn't the point of the SP signing the request, verifying that the content of the request is that of the SP?

Nobody is arguing against that.

> As a developer, is it not unreasonable to want to test a new API with api/v2/callback, instead of the api/v1/callback in the metadata, so long as the request is signed by my SP's private key?

Yes, it's perfectly reasonable that you want to test new endpoints. The same way it is reasonable to require you to exchange new metadata with the IdP including both v1 and v2 endpoints in order to use them. The same way it is reasonable not to degrade security mechanisms that could put plenty of people at risk just to save **one** metadata exchange during the development of a new product. I honestly don't think that's a valid argument.

Also, are you familiar with the [SAML 2.0 Interoperability Deployment Profile (a.k.a. SAML2Int)](https://kantarainitiative.github.io/SAMLprofiles/saml2int.html)? `SDP-SP07` is especially relevant here:

> The `AssertionConsumerServiceURL` value, if present, MUST match an endpoint location expressed in the SP’s metadata exactly, without requiring URL canonicalization/normalization.
