### ISSUE TITLE
PHP Fatal error:  Call to a member function loadTranslations()

### ISSUE THREAD

**Issue by kamoex84** [simplesamlphp/simplesamlphp#905]
PHP Fatal error:  Call to a member function loadTranslations() on null in /var/www/html/simplesamlphp/lib/SimpleSAML/Locale/Localization.php on line 221

**Comment by tvdijen** [comment]
Hey @kamoex84 ! I assume you're running the `master` branch?

**Comment by tvdijen** [comment]
Well, the short-term solution would be to use a released version..
`master` currently has some issues that I'm unable to resolve

**Comment by tvdijen** [comment]
@jaimeperez what would be the appropriate way to fix this?
`master` is working fine with backend set to `gettext/gettext`, not with `SimpleSAMLphp`. This is because the current code will always use Twig-templates when available (which rely on gettext)..
Should we add another condition so that Twig-templates will only be the preferred case when backend is `gettext/gettext`?

**Comment by kamoex84** [comment]
Duly noted, @tvdijen . Thanks.

**Comment by jaimeperez** [comment]
I think the proper solution would be to actually fix this so that it works. I'm pretty certain that it was working back in the day, but wouldn't bet money on it 😜 

Should be relatively simple. This is one of the advantages of patching twig to use our own translation functions: we can substitute the call to Oscar Otero's gettext implementation with a call to our own translation methods. Still, I don't have the code right in front of me so it might be that it's a bit more complicated than it should.

At the same time, I'm starting to wonder whether it's a good idea to have automatic detection of twig templates or not, since that would make it impossible to have both the old and the new UI coexist... It might actually be easier to disable that _automagical_ detection and force each UI to use its own translation subsystem.

**Comment by tvdijen** [comment]
A proper fix would always be better, but that probably goes over my head...
I think the best I can do right now is open a new PR as a successor of #717 and document the things that are broken on `master` right now..

**Comment by tvdijen** [comment]
@kamoex84: If you don't mind I'm closing this issue and we're continuing this in the bigger picture at #906...
Thanks for reporting this!

**Comment by tvdijen** [comment]
@jaimeperez Isn't this what's messing us up here?
https://github.com/simplesamlphp/simplesamlphp/blob/89bff5a399d26055f96ed100cb6995043c32a9ba/lib/SimpleSAML/XHTML/Template.php#L230

**Comment by jaimeperez** [comment]
Most likely, yes...

**Comment by jaimeperez** [comment]
So, the issue with _automagical_ discovery of twig or php templates is that you can't really separate two different user interfaces at the same time, because as soon as you migrate one page, it'll use the new twig template regardless of whether you want to use the new user interface or not (`usenewui` configuration option). Such automated discovery is useful when you just want to migrate existing templates in PHP to twig, but not when you want to have two different UIs.

The more I think about it, the more I believe it makes sense to remove the automated discovery. Doing so would also make it easier to go further in the UI changes we are planning, allowing us to have better unitary and functional tests. I can imagine an scenario like this, which shouldn't be a ton of work:

- Move the admin interface to a new _admin_ module. This would allow users to in fact disable completely the admin interface, which is a feature that we've been asked for multiple times. That would make it possible as well to clean a lot of stuff in other modules that doesn't really belong there, and also introduce another change:

- Introduce a request router. I've been playing lately with `phroute/phroute` and it's fast and easy to use. Introducing it in `module.php` would allow us to move away from PHP files that handle everything on their own, and more importantly, be able to capture the output programmatically, which leads us to proper unitary and functional tests, finally!

If we explore this way, we can then solve this issue by:

1. Removing the automatic discovery of twig files, so that PHP templates are always used unless we explicitly tell SimpleSAMLphp to use the new interface with `"usenewui" => true`.

2. Adding a router to `module.php` that works only when we're using the new UI (for now), mapping each request to new classes that produce output.

3. Removing the configuration option to select the i18n backend. If we keep each subsystem (PHP templates vs Twig templates) completely separate and isolated, each of them can have their own translation system. The user doesn't really need to choose, especially if the old JSON files are going away.

I know this is ambitious and involves quite some work, but I don't think it'd be that much, and the benefits of doing so would be huge. I can commit myself to work on a PoC before actually accepting this path forward, if we agree about it.

**Comment by tvdijen** [comment]
Just thinking out loud here...
Considering the fact we're already using Twig, i18n and are talking about routing, controllers and [polyfill](https://github.com/simplesamlphp/simplesamlphp/issues/566#issuecomment-310067645) in [several](https://github.com/simplesamlphp/simplesamlphp/issues/602#issuecomment-297424328) places, would using Symfony be a funny idea for a next-generation SSP?

**Comment by thijskh** [comment]
Gone with option 3 on `experiment/routing`
