### ISSUE TITLE
SimpleSAML/Logger::flush has fragile error handling resulting in 500 and no log

### ISSUE THREAD

**Issue by htto** [simplesamlphp/simplesamlphp#914]
If requesting the current session from the request fails due to session storage problems (e.g. SQL connection error like ```PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'idp'@'localhost' (using password: YES)```), the following code will throw an unhandled Exception und thus 500 to the end user:

```php
try {
    $s = \SimpleSAML_Session::getSessionFromRequest();
} catch (\Exception $e) {
    // loading session failed. We don't care why, at this point we have a transient session, so we use that
    self::error('Cannot load or create session: '.$e->getMessage());
    $s = \SimpleSAML_Session::getSessionFromRequest();
}
```

```
#0 lib/SimpleSAML/Store.php(52): SimpleSAML\Store\SQL->__construct()
#1 lib/SimpleSAML/SessionHandler.php(122): SimpleSAML\Store::getInstance()
#2 lib/SimpleSAML/SessionHandler.php(41): SimpleSAML\SessionHandler::createSessionHandler()
#3 lib/SimpleSAML/Session.php(321): SimpleSAML\SessionHandler::getSessionHandler()
#4 lib/SimpleSAML/Session.php(253): SimpleSAML_Session::getSession()
#5 lib/SimpleSAML/Logger.php(275): SimpleSAML_Session::getSessionFromRequest()
#6 [internal function]: SimpleSAML\Logger::flush()
#7 {main}
```

The problem is, that if the first getSessionFromRequest fails and is properly caught, the second one might still fail and is not caught. Unfortunately the error handler doesn't get triggered as well.

Since the fatal error causes an abort, not flushed before entries (like the causing inbound request) won't get logged. Instead (or additionally) to relying on the transient session, one could just (or as a fallback) set the trackId to some 'undefined' value if getting the session/transient session fails:

```php
try {
    $s = \SimpleSAML_Session::getSessionFromRequest();
    self::$trackid = $s->getTrackID();
} catch (\Exception $e) {
    self::$trackid = 'undefined';
 }
```

**Comment by thijskh** [comment]
Seems reasonable, could you submit it as a pull request?

**Comment by tvdijen** [comment]
If we would be properly catching the SQL-error, a subsequent call to getSessionFromRequest should _always_ return a transient session.. We should probably fix that, instead of the suggested fix.

**Comment by htto** [comment]
Thanks for the feedback so far. I'm with @tvdijen to properly handle the underlying error and always return a proper session value. Running into 500 isn't that nice, especially on the idp. The above snippet was more a circumvention of the 500.

**Comment by jaimeperez** [comment]
Hi @htto!

Thanks a lot for reporting this. It has now been fixed, hopefully for all cases.

The issue was a bit more complex than that. The problem here was not the `flush()` method itself, but the way transient sessions were created. `flush()` was only called during shutdown back in the day (that's no longer true, though), meaning at that point headers had already been sent, and there is no way that could cause an HTTP 500 error to be sent to the user. Those errors were caused before, since during session initialization, the constructor of the `Session` class would create a transient session in case of a failure like the one you were experiencing. However, it would also try to set the session ID (which is meaningless in a transient session), for which it needed to get the session handler. This would fail again, triggering our exception handler. Since the transient session was never recorded in the `Session` class, it was then not possible to use by the session handler or any code called by it (like the `SimpleSAML\Error\Error` class, responsible for actually printing the error).

This unfortunate chain of events was leading to a blank page in the browser, and errors logged in the web server's error log, instead of SimpleSAMLphp's.

I've fixed the issue by stopping to try to set the session ID during the creation of a transient session, and the problem appears to be gone. Please let us know if you observe any further issues.
