### ISSUE TITLE
No Identity provider available

### ISSUE THREAD

**Issue by wehzy** [simplesamlphp/simplesamlphp#941]
Hi,

I want to install Filesender on a server but I faced an issue on SimpleSAMLphp. There is no choice available to select. I'm a bit lost because I want to configure the username and password myself.

![image](https://user-images.githubusercontent.com/43643517/46148143-b6420480-c267-11e8-8646-469865f29744.png)

What can I do to solve my issue or to skip it ?

**Comment by tvdijen** [comment]
Hi @wehzy!
This is an issue-tracker, not a support form.. Although your question is probably more Filesender-related than SimpleSAML-related, your could give it a shot at one of our [mailinglists](https://simplesamlphp.org/lists).

To give you at least an answer, given the information you're giving:
I assume you're using SimpleSAMLphp as a _Service Provider_ to protect your Filesender-application. This means you're delegating authentication to a 3rd party, called an _Identity Provider_..

This raises a question, because you're saying: 
> I'm a bit lost because **I want to configure the username and password myself**

It's not impossible, but it implicates that you need to set up an Identity Provider yourself.. SimpleSAML can do that as well, but it requires a second instance..

The screenshot tells me you've installed a Service Provider that has no Identity Provider coupled to it..
Maybe I'm wrong or misinterpreting your question, but it's the best I can using the information you're giving, so I invite you to move your support request to the mailinglist.. Perhaps there are people with Filesender-experience there that can relate to your questions...
