### ISSUE TITLE
newUI: discopower-module has inline javascript

### ISSUE THREAD

**Issue by tvdijen** [simplesamlphp/simplesamlphp#950]
discopower still has on the fly composed javascript in lib/DiscoPower.php (handleRequest)

**Comment by ghalse** [comment]
This can be fixed by moving the logic to generate the tab list into a standalone PHP file that outputs a JSON structure. The rest of the code goes into a static .js file, and the tab list is built dynamically using $.ajax(). Ideally the latter gets bundled in with other Javascript to avoid too many <script> references.
