### ISSUE TITLE
Issues after updating from 1.15.4 to 1.16.2

### ISSUE THREAD

**Issue by RoSk0** [simplesamlphp/simplesamlphp#978]
After update I see:

SimpleSAML_Error_UnserializableException: Invalid configuration of the "metadata.sources" configuration option: Error fetching "/var/www/drupal/project/config/simplesamlphp/metadata/idp_metadata.xml" no error available in SimpleSAML_Auth_Source->initLogin() (line 198 of /var/www/drupal/project/releases/20181107-1/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Auth/Source.php)

But the code is actually live in "/var/www/drupal/project/current/../config/simplesamlphp". 
In /var/www/drupal/project/ "current" is a symbolic link to the actual release directory, in this case "releases/20181107-1". 

Will try to figure out what change is causing it.

**Comment by RoSk0** [comment]
Its obvious that lib/SimpleSAML/Utils/System.php resolvePath() can't resolve paths correctly in the configuration described above, but I still don't understand how it working in the first place...

**Comment by tvdijen** [comment]
Hi @RoSk0 !
What does your "metadata.sources" array look like?

**Comment by RoSk0** [comment]
Hi,

I don't have exact code atm, but it looks like this

```
[
  'type' => 'xml',
  'file' => 'var/www/drupal/project/current/../config/simplesamlphp/metadata/idp_metadata.xml',
]
```

**Comment by tvdijen** [comment]
Why would you use /../ in a path pointing to a file?
It should work though, but it doesn't make any sense...

What happens if you change it to `/var/www/drupal/project/config/simplesamlphp/metadata/idp_metadata.xml`?  It that works, I have a clue about what's going on

**Comment by RoSk0** [comment]
We use ".." in path because in 

```php
[
  'type' => 'xml',
  'file' => 'var/www/drupal/project/current/../config/simplesamlphp/metadata/idp_metadata.xml',
]
```

**current** is actually a symlink to "/var/www/drupal/project/releases/20181107-1/web" and properly resolved path in this case should be "/var/www/drupal/project/releases/20181107-1/config/simplesamlphp/metadata/idp_metadata.xml".

Is there  any **real** reasons not to use `realpath()` in `System:resolvePath()`? Because it will do the job properly

**Comment by RoSk0** [comment]
So the real bug or issue is that \SimpleSAML\Utils\System::resolvePath() can't resolve path's with the symlinks. 

It looks like our configuration is an edge case which is not supported by \SimpleSAML\Utils\System::resolvePath(): lets say we have $path = '/test/symlink/../path' where **symlink** is a symlink to "/test/some/path", so result of System::resolvePath() should be "/test/some/path" but because [dirname](https://secure.php.net/manual/en/function.dirname.php) 

>   dirname() operates naively on the input string, and is not aware of the actual filesystem, or path components such as "..".
it will not follow symlink as "realpath()" would do for example.

I found a workaround for this issue and resolved that path in the config.php which is properly loaded.

Not sure what to do with this issue though...

**Comment by tvdijen** [comment]
`/test/symlink/../path` should actually resolve to `/test/path`, because that's just how relative paths work... And that's exactly what's happening in your situation!
I'd say it works as designed (and as we've intended when fixing this in 1.16)

**Comment by jaimeperez** [comment]
Hi @RoSk0,

I'm afraid the problem here is essentially your setup. While it makes a lot of sense that you are downloading releases to their own directories and using a symlink to point to them with a fixed path, it doesn't make any sense to have the metadata and configuration stored inside the very same installation dir for SimpleSAMLphp. Both should be outside, in a stable directory that doesn't change when you upgrade from one release to another.

Apart from that, have you tried using a relative path instead of an absolute path? In the end, what you are doing makes no sense, because you are assuming a cross resolution of paths based on the current work dir. The path you specified in your configuration should, essentially, translate into `/var/www/drupal/project/config/simplesamlphp/metadata/idp_metadata.xml`, which is exactly what SimpleSAMLphp is doing. What you are expecting there is, however: _given that I am currently on `/var/www/drupal/project/releases/20181107/web/config`, and `/var/www/drupal/project/current` points to my current parent directory, ignore the latter and evaluate `../metadata` from the current directory_. Which is basically what relative paths are for. What you are trying to do wouldn't work on a shell, either.
