### ISSUE TITLE
Negotiate module documentation

### ISSUE THREAD

**Issue by duncanwebb** [simplesamlphp/simplesamlphp#983]
**Is your feature request related to a problem? Please describe.**

When testing the Negotiate module it works correctly until the logout link is selected and then only the fallback is shown, after sometime (maybe a day or so) it works again. 

I reckon that I need to implement the "Logout/Login loop and reauthenticating" code as described in the simplesamlphp/modules/negotiate/docs/negotiate.md page. However the documentation is a little unclear about where to add the code for the Logout/Login loop. If I use kerberos as a fallback in which files do I need to add the www and template code?

**Describe the solution you'd like**
More precise documentation with an example.

**Additional context**
For Debian you could add this for chromium. in /etc/chromium.d/default-flags
```bash
# Allow Kerberos SPN generation
export CHROMIUM_FLAGS="$CHROMIUM_FLAGS --auth-server-whitelist=.example.com"
```
and for firefox-esr in /etc/firefox-esr/firefox-esr.js
```javascript
// Enable negotiate authentication
pref("network.negotiate-auth.allow-non-fqdn", true);
pref("network.negotiate-auth.trusted-uris", ".example.com");
```

**Comment by tvdijen** [comment]
What you are experiencing is caused by [this](https://github.com/simplesamlphp/simplesamlphp/blob/0b089801dd36b92462dcc0603f170c84c6c1f2ef/modules/negotiate/lib/Auth/Source/Negotiate.php#L355) line of code in the logout-method:
`            $session->setData('negotiate:disable', 'session', true, 24 * 60 * 60);`

This effectively disables negotiate-login, because if we didn't you would end up looping and getting reauthenticated again.
Now, if you are able to set `negotiate:disable` back to false, you can enable negotiate login again

**Comment by tvdijen** [comment]
> and for firefox-esr in /etc/firefox-esr/firefox-esr.js
> 
> // Enable negotiate authentication
> pref("network.negotiate-auth.allow-non-fqdn", true);
> pref("network.negotiate-auth.trusted-uris", ".example.com");

The first one is support for an edge case that shouldn't be documented here.. The latter is already documented under 'Firefox'

**Comment by tvdijen** [comment]
The documentation is unclear because it depends on your implementation.. You're talking about a fallback to Kerberos, which makes no sense since Kerberos is what we're doing with the negotiate-module in the first place.. Also, we don't include any module called 'kerberos', so we cannot help you with that.

Perhaps rephrasing your question and sending it to the proper [mailinglist](https://simplesamlphp.org/lists) will get you further.

**Comment by duncanwebb** [comment]
Sorry I didn't mean to offend you.

The firefox case was for a system setting as opposed to a user and so can be easily deployed to multiple hosts (took quite while to figure out)

It makes sense to fall back to kerberos:Krb5 if a user is connecting through a VPN as negotiate may not work in this case. Also I can implement negotiate without negatively affecting any users as we currently use Kerberos. It doesn't really matter which fallback, example-userpass would do.

I'd rather not use mailing lists as they leak email addresses to spammers which results in wasted time filtering out spam messages and I am not sure which the proper mailing list is.

Thanks anyway.
