### ISSUE TITLE
IDP Metadata containing X509 certificate with BEGIN header leads to breaking methods getPublicKeys and checkSign

### ISSUE THREAD

**Issue by danowar2k** [simplesamlphp/simplesamlphp#999]
**Describe the bug**
If the IDP metadata contains a X509 certificate, e.g. for signing SAML responses, and the X509 certificate is in PEM format complete with enclosing BEGIN and END, the method getPublicKeys (https://github.com/simplesamlphp/simplesamlphp/blob/4e239ac76e450f2fe510ab2855c8f97d5b403c70/lib/SimpleSAML/Configuration.php#L1337)
removes the whitespace in the PEM header and footer. 
This produces "-----BEGINCERTIFICATE-----" etc. . If you try to extract a public key from the certificate with such a broken header, that doesn't work anymore.

But there is more: The then returned certificate with the wrong header is prepended and suffixed with another (!) PEM header and footer in https://github.com/simplesamlphp/simplesamlphp/blob/4e239ac76e450f2fe510ab2855c8f97d5b403c70/modules/saml/lib/Message.php#L159
Note that this happens even if the old header is not broken.

The question is: Does the SAML standard or something explicitly say that an X509Certificate element must only contain headerless PEM certificates? Or is this an oversight on the part of SimpleSAMLphp?

**To Reproduce**
1. Create IDP metadata containing a X509 certificate in PEM format.
2. Try to use it.

**Expected behavior**
I would expect a PEM certificate with a header and footer to not be altered by removing any whitespace from the header or footer.
I would also expect to not add the header and footer when it is already there.

**Additional context**
The problem was originally found and described at https://github.com/catalyst/moodle-auth_saml2/issues/272 which is using SimpleSAMLphp as a library.

**Comment by tvdijen** [comment]
The standard is actually not saying anything about it, but the PEM-cert without headers is the de facto industry standard.

**Comment by danowar2k** [comment]
Okay, so if without header is the de facto industry standard, why do you add the header in code?

**Comment by danowar2k** [comment]
By "fix" I mean instead of creating the header rather ensuring that the header exists, making the code idempotent.

**Comment by pmeulen** [comment]
Hi danowar2k,

The behaviour of SimpleSAMLphp is correct, although I see how this could be confusing if you are not aware why it is the way it is. 

The SAML metadata standard uses the KeyInfo that is defined in the xmldsig standard to specify the signing and encryption keys (see 2.4.1.1 of https://docs.oasis-open.org/security/saml/v2.0/saml-metadata-2.0-os.pdf). It is xmldsig that specifies that the X509Certificate "contains a base64-encoded [X509V3] certificate", and a X509V3 certificate is the DER/BER encoded X.509 certificate there. (see 4.5.4 of https://www.w3.org/TR/xmldsig-core/)

So if you a familiar with PEM encoded certificates it looks like the X509Certificate element in SAML metadata contains a certificate as you know it, but then without the PEM headers. Adding PEM headers to the X509Certificate would however be incorrect.

That SSP converts these certificates to PEM format internally because it uses APIs that require the certificates to be in this format. This is an implementation detail.

What we could add to SSP is a more helpful error message when the certificate, which must be a base64 encoded string, contains PEM headers. We could strip the PEM headers when we see them here, but I don't think that would be a good idea, because that could confuse people into putting certificate in SAML metadata in that format, and that would be incorrect, and not work with the other implementations out there.

**Comment by danowar2k** [comment]
Out of interest: If a standard references another recommendation, like xmldsig references the ITU X.509 document, does it always reference the concrete document version (like V3) or does it reference the abstract recommendation and therefore the newest version of it? I ask because V3 is long since superseded by other versions...

Anyway: I've read up on the details (as long as I could, standards are dry stuff), and now I understand. A X.509 certificate in PEM format would be base64-encoded with headers, but the documents never mention the PEM format. Therefore you expect the XML to adhere to that.

I'll just do some suggestions:
- Do some validation of IDP metadata files or the X509Certificate element before working with them and throw an error if the XML or element doesn't adhere to the format you expect
- Wrap the configuration array in an object where the validation takes place when it is constructed.
- I don't know, is the SAML 2.0 metadata document linked in the docs? Haven't found it...
